<style>
    .changeCarName .formSubmitWrapper{
        display:inline-block;
    }
    .nameBack{
        float:right;
    }
</style>


<?php $team = $authenticatedUser['Team']; ?>
<div class="mainUserBox myCarsBox">
    
    <h4 class="boxHeader"><?= $this->translate('Change car name'); ?></h4>
    
    <div class="col-md-12 pb20">
        <div class="myPeople peopleList driverList carMarketList pb20">

            <ul>
                <li class="active">
                    <?php echo $car['name']; ?> 
                </li>
            </ul>
            <div class="carCard carMarketCard active peopleMarketCard col-md-6">
               <div class="notifyInfo2">
                   <?= $this->translate('You are allowed to change name of your car every 30 days.');?>
                        <img src="/images/layout/gc_small.png" class=""> <?= $this->translate('members can change car name every 7 days.'); ?>
                        <br /><br />
                    <?php if(!$nextDateChange): 
                       echo $this->translate("You still have")." <b>1</b> ".$this->translate("name change left.");
                   else:
                       echo $this->translate("You can change car name on")." <b>".$nextDateChange->format('d/m/Y H:i')."</b>.";
                   endif;
                   ?>
                   <br />
                   <br />
               </div>
                <div class="changeCarName" id="changeCarName1">
                    <form method="POST">
                        <div class="form-group">
                            <i class="fa fa-info-circle pull-right" title="Allowed characters are letters,numbers, spaces, # and -. Allowed length is 4-30 characters."></i>
                            <label for="name" class="control-label"><?= $this->translate('New name'); ?></label>
                            <?php echo $form->getElement('name')->renderElement(); ?>
                        </div>
                        <?php echo $form->getElement('submit')->renderElement(); ?>
                        <a href="/account/my-cars" class="btn btn-default nameBack"><?=  $this->translate('Go back'); ?></a>
                    </form>
                </div>
            </div>
          
            <div class="carCard col-md-6 pr0 pl0">
                 <?php if(isset($car['Model']['photo'])&&strlen($car['Model']['photo'])){ ?>
                <img src="/media/cars/<?php echo $car['Model']['photo']; ?>" alt="<?php echo $car['Model']['name']; ?>" class="carCardPhoto" />
           <?php } 
                else{ ?>
                    <img src="http://dummyimage.com/340x220&amp;text=No+photo" class="carCardPhoto" />
                <?php
                }
                ?>
            <div class="clearfix"></div>
                    <?= TK_Helper::showCarParameters($car); ?>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

</div>