<?php if(isset($message))
    echo $message;
?>
<h2>Sell car</h2>
<?php if(isset($car['Model']['photo'])&&strlen($car['Model']['photo'])){ ?>
        <img src="/media/cars/<?php echo $car['Model']['photo']; ?>" alt="<?php echo $car['Model']['name']; ?>" style="width:300px;float:right;margin-right:100px;" />
   <?php } ?>
Car name: <?php echo $car['name']; ?> <br />
    <div class="changeCarName" id="changeCarName1">
	<?php // echo $formCar1->renderForm(); ?>
    </div>
    Marka: <?php echo $car['Model']['name']; ?><br />
    Przebieg: <?php echo $car['mileage']; ?><br />
    Wartość: <?php echo $car['value']; ?><br />
    Koszty utrzymania: <?php echo $car['upkeep']; ?><br />
<div class="clearfix"></div>
