<?php

/**
 * Team_Model_Doctrine_BaseTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $name
 * @property integer $driver1_id
 * @property integer $driver2_id
 * @property integer $pilot1_id
 * @property integer $pilot2_id
 * @property integer $car1_id
 * @property integer $car2_id
 * @property integer $sponsor_id
 * @property float $league_name
 * @property integer $cash
 * @property integer $this_week_rank
 * @property integer $last_week_rank
 * @property timestamp $last_name_change
 * @property Doctrine_Collection $Team
 * @property Team_Model_Doctrine_SponsorList $Sponsor
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Team_Model_Doctrine_BaseTeam extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('team_team');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('driver1_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('driver2_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('pilot1_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('pilot2_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('car1_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('car2_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('sponsor_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('league_name', 'float', 10, array(
             'type' => 'float',
             'length' => '10',
             'scale' => '2',
             ));
        $this->hasColumn('cash', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('this_week_rank', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('last_week_rank', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('last_name_change', 'timestamp', null, array(
             'type' => 'timestamp',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Team_Model_Doctrine_Finance as Team', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $this->hasOne('Team_Model_Doctrine_SponsorList as Sponsor', array(
             'local' => 'sponsor_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}