<?php

/**
 * Team_Model_Doctrine_SponsorListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Team_Model_Doctrine_SponsorListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Team_Model_Doctrine_SponsorListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Team_Model_Doctrine_SponsorList');
    }
}