<?php

/**
 * Team_Model_Doctrine_Team
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Team_Model_Doctrine_Team extends Team_Model_Doctrine_BaseTeam
{
     public function setUp()
    {
        parent::setUp();
        
	$this->hasMany('Car_Model_Doctrine_Car as Cars', array(
             'local' => 'id',
             'foreign' => 'team_id'));

	$this->hasMany('People_Model_Doctrine_People as Players', array(
             'local' => 'id',
             'foreign' => 'team_id'));
        
	$this->hasOne('User_Model_Doctrine_User as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
	
        
	$this->hasMany('League_Model_Doctrine_Season as Seasons', array(
             'local' => 'id',
             'foreign' => 'team_id'));
        
        
	$this->hasMany('Rally_Model_Doctrine_Crew as Crews', array(
             'local' => 'id',
             'foreign' => 'team_id'));
        
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}