<link rel="stylesheet" href="/css/cards.css" />
<link rel="stylesheet" href="/plugins/bxslider/jquery.bxslider.css" />
<script src="/plugins/bxslider/jquery.bxslider.js"></script>
<link rel="stylesheet" type="text/css" href="/plugins/jNotify/jNotify.jquery.css" media="screen" />
<script type="text/javascript" src="/plugins/jNotify/jNotify.jquery.min.js"></script>
<script>
    $(document).ready(function(){
        var slider = $('#manageCards').bxSlider({
            slideWidth: 145,
            slideHeight:190,
            minSlides: 4,
            maxSlides: 4,
            moveSlides: 1,
            pager:false
        });
        
        
        $('.manageCardBox div.playerCard').delegate('button.lockTheCard','click',function(){
            var element = $(this).parent();
            var id = $(this).attr('data-rel');
            var btn = $(this);
            var td = element.parent();
            $.ajax({
                type: "POST",
                dataType: "json",
                url: "/card/lock-card",
                data:{id: id},
                success: function(data) {
                   if(data.msg=='locked'){
                       element.prepend('<img src="/images/layout/lock.png" class="cardLock" />');
                       btn.html('<i class="fa fa-unlock"></i> Unlock the card');
                       btn.removeClass('btn-warning');
                       btn.addClass('btn-danger');
                       console.log($('.lockedCards td.lockedCardCol:empty'));
                       console.log($('.lockedCards td.lockedCardCol'));
                       element.appendTo('.lockedCards td.lockedCardCol:empty:eq(0)');
                        slider.reloadSlider();
                   }
                   
                   if(data.msg=='unlocked'){
                       $('#manageCards').prepend(element);
                       element.find('.cardLock').remove();
                       td.empty();
                       btn.html('<i class="fa fa-lock"></i> Lock the card');
                       btn.addClass('btn-warning');
                       btn.removeClass('btn-danger');
                        slider.reloadSlider();
                   }
                   if(data.error){
                    jError(
                        'Sorry, you have reached maximum amount of locked cards.',
                        {
                          autoHide : true,
                          TimeShown : 500,
                          HorizontalPosition : 'center',
                        }
                    );
                   }
                },
                error: function() {
                   
                }
            }); 
        });
    });
</script>
<?php 
    if(isset($_GET['msg'])){
        if($_GET['msg']=="not enough locked"){
            echo $this->showError($this->translate("You need 7 locked cards of the same type to transform."));
        }
    }
?>
<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Manage cards'); ?></h4>
    <div class='staticWrapper'>
        <?php if(isset($boughtPackageCars)): ?>
        <?= $this->showSuccess('You have bought playing cards package. Your new card(s) are listed below.'); ?>
        <div class="playerCards manageCardBox" id="boughtPackageCards">
            <?php foreach($boughtPackageCars as $boughtModel): ?>
                <div class="playerCard">
                <table>
                    <tr>
                        <th colspan="2">

                            <img src="/media/cars/<?= $boughtModel['photo']; ?>" />
                            <strong><?= $boughtModel['name']; ?></strong>
                        </th>
                    </tr>
                    <tr>
                        <td>Acceleration</td>
                        <td><?= $boughtModel['acceleration']; ?></td>
                    </tr>
                    <tr>
                        <td>V-max</td>
                        <td><?= $boughtModel['max_speed']; ?></td>
                    </tr>
                    <tr>
                        <td>Capacity</td>
                        <td><?= $boughtModel['capacity']; ?></td>
                    </tr>
                    <tr>
                        <td>Horsepower</td>
                        <td><?= $boughtModel['horsepower']; ?></td>
                    </tr>
                </table>
            </div>
            <?php endforeach; ?>
        </div>
            
        
        <?php endif; ?>
        Below you can see your play card list. Collect 7 cards of the same type and transform it into rally car. To help you achieving this, you are allowed to lock 7 cards. <br /> <br />
        <div class="playerCards manageCardBox" id="manageCards">
            <?php foreach($unlockedCards as $card): ?>
                <div class="playerCard" data-rel="<?= $card['id']; ?>">
                <?php if($card['locked']){ ?>
                <img src="/images/layout/lock.png" class="cardLock" />
                <?php } ?>
                <table>
                    <tr>
                        <th colspan="2">

                            <img src="/media/cars/<?= $card['Model']['photo']; ?>" />
                            <strong><?= $card['Model']['name']; ?></strong>
                        </th>
                    </tr>
                    <tr>
                        <td>Acceleration</td>
                        <td><?= $card['Model']['acceleration']; ?></td>
                    </tr>
                    <tr>
                        <td>V-max</td>
                        <td><?= $card['Model']['max_speed']; ?></td>
                    </tr>
                    <tr>
                        <td>Capacity</td>
                        <td><?= $card['Model']['capacity']; ?></td>
                    </tr>
                    <tr>
                        <td>Horsepower</td>
                        <td><?= $card['Model']['horsepower']; ?></td>
                    </tr>
                </table>
                <button class="lockTheCard btn btn-warning label" data-rel="<?= $card['id']; ?>"><i class="fa fa-lock"></i> Lock the card</button>
            </div>
            <?php endforeach; ?>
        </div>

        <style>
            .lockedCards .lockedCardRow > td{
                width:145px;
                height:175px;
                border:1px solid black;
            }
            .lockedCards{
                margin:0 auto;
            }
            .lockedCards .lockedCardRow .playerCard{
                position:relative;
            }
            .lockedCards .lockedCardRow .playerCard tr img{
                    max-width: 100%;
            width: auto;
            display: block;
            }
            .lockTheCard{
                margin:0 auto;
                margin-top:10px;
            }

            .bx-wrapper, .bx-viewport {
                height: 220px !important; //provide height of slider
            }
        </style>
        <table class="lockedCards manageCardBox">
            <tr class="lockedCardRow">
                <?php for($i=0;$i<4;$i++): 
                    if(isset($lockedCards[$i])){
                        $card = $lockedCards[$i];
                        ?>
                <td class="lockedCardCol">
                        <div class="playerCard" data-rel="<?= $card['id']; ?>">
                            <?php if($card['locked']){ ?>
                            <img src="/images/layout/lock.png" class="cardLock" />
                            <?php } ?>
                            <table>
                                <tr>
                                    <th colspan="2">

                                        <img src="/media/cars/<?= $card['Model']['photo']; ?>" />
                                        <strong><?= $card['Model']['name']; ?></strong>
                                    </th>
                                </tr>
                                <tr>
                                    <td>Acceleration</td>
                                    <td><?= $card['Model']['acceleration']; ?></td>
                                </tr>
                                <tr>
                                    <td>V-max</td>
                                    <td><?= $card['Model']['max_speed']; ?></td>
                                </tr>
                                <tr>
                                    <td>Capacity</td>
                                    <td><?= $card['Model']['capacity']; ?></td>
                                </tr>
                                <tr>
                                    <td>Horsepower</td>
                                    <td><?= $card['Model']['horsepower']; ?></td>
                                </tr>
                            </table>
                            <button class="lockTheCard label btn btn-danger" data-rel="<?= $card['id']; ?>"><i class="fa fa-unlock"></i> Unlock the card</button>
                        </div>
                </td>
                        <?php 
                        }
                        else{
                            echo "<td class='lockedCardCol'></td>";
                        }
                endfor; ?>
                
            </tr>

            <tr class="lockedCardRow">
                <?php for($i=4;$i<8;$i++): 
                    if(isset($lockedCards[$i])){
                        $card = $lockedCards[$i];
                        
                        ?>
                <td class="lockedCardCol">
                        <div class="playerCard" data-rel="<?= $card['id']; ?>">
                            <?php if($card['locked']){ ?>
                            <img src="/images/layout/lock.png" class="cardLock" />
                            <?php } ?>
                            <table>
                                <tr>
                                    <th colspan="2">

                                        <img src="/media/cars/<?= $card['Model']['photo']; ?>" />
                                        <strong><?= $card['Model']['name']; ?></strong>
                                    </th>
                                </tr>
                                <tr>
                                    <td>Acceleration</td>
                                    <td><?= $card['Model']['acceleration']; ?></td>
                                </tr>
                                <tr>
                                    <td>V-max</td>
                                    <td><?= $card['Model']['max_speed']; ?></td>
                                </tr>
                                <tr>
                                    <td>Capacity</td>
                                    <td><?= $card['Model']['capacity']; ?></td>
                                </tr>
                                <tr>
                                    <td>Horsepower</td>
                                    <td><?= $card['Model']['horsepower']; ?></td>
                                </tr>
                            </table>
                            <button class="lockTheCard  label btn btn-danger" data-rel="<?= $card['id']; ?>"><i class="fa fa-unlock"></i> Unlock the card</button>
                        </div>
                </td>
                        <?php 
                        }
                        else{
                            echo "<td class='lockedCardCol'></td>";
                        }
                endfor; ?>
            </tr>
        </table>
        
        <?php if($lockedSameType){ ?>
            <a href="/card/transform-cards/<?= $lockedSameType['Model']['id']; ?>" class="btn myBtn transformPlayCards">    
            Turn your play cards into <?= $lockedSameType['Model']['name']; ?>
            </a>
        <?php
        }
        ?>
    </div>
</div>


