<link rel="stylesheet" href="/css/cards.css" />
<link rel="stylesheet" href="/plugins/bxslider/jquery.bxslider.css" />
<script src="/plugins/bxslider/jquery.bxslider.js"></script>
<link rel="stylesheet" type="text/css" href="/plugins/jNotify/jNotify.jquery.css" media="screen" />
<script type="text/javascript" src="/plugins/jNotify/jNotify.jquery.min.js"></script>
<script>
    $(document).ready(function(){
        var slider = $('#manageCards').bxSlider({
            slideWidth: 145,
            slideHeight:190,
            minSlides: 4,
            maxSlides: 4,
            moveSlides: 1,
            pager:false
        });
        
        
        $('.manageCardBox div.playerCard').delegate('button.lockTheCard','click',function(){
            var element = $(this).parent();
            var id = $(this).attr('data-rel');
            var btn = $(this);
            var td = element.parent();
            $.ajax({
                type: "POST",
                dataType: "json",
                url: "/card/lock-card",
                data:{id: id},
                success: function(data) {
                   if(data.msg=='locked'){
                       element.prepend('<img src="/images/layout/lock.png" class="cardLock" />');
                       btn.html('<i class="fa fa-unlock"></i> <?= $this->translate('Unlock the card'); ?> ');
                       btn.removeClass('btn-warning');
                       btn.addClass('btn-success');
                       element.appendTo('.lockedCards td.lockedCardCol:empty:eq(0)');
                        slider.reloadSlider();
                   }
                   
                   if(data.msg=='unlocked'){
                       $('#manageCards').prepend(element);
                       element.find('.cardLock').remove();
                       td.empty();
                       btn.html('<i class="fa fa-lock"></i> <?= $this->translate('Lock the card'); ?>');
                       btn.addClass('btn-warning');
                       btn.removeClass('btn-success');
                        slider.reloadSlider();
                   }
                   
                   if(typeof(data.transform)!='undefined'){
                       //lockedCards
                       var id = data.transform.cm_id;
                       var name = data.transform.cm_name;
                       if(!$('.transformPlayCards').length){
                            var transformButton = '<a href="/card/transform-cards/'+id+'" class="btn myBtn transformPlayCards"><?= $this->translate('Turn your play cards into') ?> '+name+'</a>';
                            $('.lockedCards').after(transformButton);
                       }
                   }
                   else{
                       $('.transformPlayCards').remove();
                   }
                   
                   if(data.error){
                    jError(
                        'Sorry, you have reached maximum amount of locked cards.',
                        {
                          autoHide : true,
                          TimeShown : 500,
                          HorizontalPosition : 'center',
                        }
                    );
                   }
                },
                error: function() {
                   
                }
            }); 
        });
        
        $('.manageCardBox div.playerCard').delegate('a.deleteCard','click',function(){
            var name = $(this).attr('data-name');
            
            if(!confirm('Are you sure you want to delete '+name+' card? This decision is irreversible.')){ 
                return false 
            }
        });
    });
</script>
<?php 
    if(isset($_GET['msg'])){
        if($_GET['msg']=="not enough locked"){
            echo $this->showError($this->translate("You need 7 locked cards of the same type to transform."));
        }
        elseif($_GET['msg']=="card deleted"){
            echo $this->showSuccess($this->translate("Card was successfully deleted."));
        }
    }
?>
<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Manage cards'); ?></h4>
    <div class='staticWrapper'>
        <?php if(isset($boughtPackageCars)): ?>
        <?= $this->showSuccess('You have bought playing cards package. Your new card(s) are listed below.'); ?>
        <div class="playerCards manageCardBox" id="boughtPackageCards">
            <?php foreach($boughtPackageCars as $boughtModel): ?>
                <div class="playerCard">
                <table>
                    <tr>
                        <th colspan="2">

                            <img src="/media/cars/<?= $boughtModel['photo']; ?>" />
                            <strong><?= $boughtModel['name']; ?></strong>
                        </th>
                    </tr>
                    <tr>
                        <td><?= $this->translate('acceleration'); ?></td>
                        <td><?= $boughtModel['acceleration']; ?></td>
                    </tr>
                    <tr>
                        <td><?= $this->translate('v-max'); ?></td>
                        <td><?= $boughtModel['max_speed']; ?></td>
                    </tr>
                    <tr>
                        <td><?= $this->translate('capacity'); ?></td>
                        <td><?= $boughtModel['capacity']; ?></td>
                    </tr>
                    <tr>
                        <td><?= $this->translate('horsepower'); ?></td>
                        <td><?= $boughtModel['horsepower']; ?></td>
                    </tr>
                </table>
            </div>
            <?php endforeach; ?>
        </div>
            
        
        <?php endif; ?>
       <?= $this->translate('Below you can see your play card list. Collect 7 cards of the same type and transform it into rally car. To help you achieving this, you are allowed to lock 7 cards. Locked cards cannot be played with and they are protected from being lost.'); ?> <br /> <br />
        <div class="playerCards manageCardBox" id="manageCards">
            <?php foreach($unlockedCards as $card): ?>
                <div class="playerCard" data-rel="<?= $card['id']; ?>">
                <?php if($card['locked']){ ?>
                <img src="/images/layout/lock.png" class="cardLock" />
                <?php } ?>
                <table>
                    <tr>
                        <th colspan="2">

                            <img src="/media/cars/<?= $card['Model']['photo']; ?>" />
                            <strong><?= $card['Model']['name']; ?></strong>
                        </th>
                    </tr>
                    <tr>
                        <td><?= $this->translate('acceleration'); ?></td>
                        <td><?= $card['Model']['acceleration']; ?></td>
                    </tr>
                    <tr>
                        <td><?= $this->translate('v-max'); ?></td>
                        <td><?= $card['Model']['max_speed']; ?></td>
                    </tr>
                    <tr>
                        <td><?= $this->translate('capacity'); ?></td>
                        <td><?= $card['Model']['capacity']; ?></td>
                    </tr>
                    <tr>
                        <td><?= $this->translate('horsepower'); ?></td>
                        <td><?= $card['Model']['horsepower']; ?></td>
                    </tr>
                </table>
                <button class="lockTheCard btn btn-warning label" data-rel="<?= $card['id']; ?>"><i class="fa fa-lock"></i> <?= $this->translate('Lock the card'); ?></button>
                <a href="/card/delete-card/<?= $card['id'];?>" data-name="<?= $card['Model']['name']; ?>" class="deleteCard btn btn-danger label"><i class="fa fa-trash-o"></i> <?= $this->translate('Delete card'); ?></a>
            </div>
            <?php endforeach; ?>
        </div>
        <br />
        <table class="lockedCards manageCardBox">
            <tr class="lockedCardRow">
                <?php for($i=0;$i<4;$i++): 
                    if(isset($lockedCards[$i])){
                        $card = $lockedCards[$i];
                        ?>
                <td class="lockedCardCol">
                        <div class="playerCard" data-rel="<?= $card['id']; ?>">
                            <?php if($card['locked']){ ?>
                            <img src="/images/layout/lock.png" class="cardLock" />
                            <?php } ?>
                            <table>
                                <tr>
                                    <th colspan="2">

                                        <img src="/media/cars/<?= $card['Model']['photo']; ?>" />
                                        <strong><?= $card['Model']['name']; ?></strong>
                                    </th>
                                </tr>
                                <tr>
                                    <td><?= $this->translate('acceleration'); ?></td>
                                    <td><?= $card['Model']['acceleration']; ?></td>
                                </tr>
                                <tr>
                                    <td><?= $this->translate('v-max'); ?></td>
                                    <td><?= $card['Model']['max_speed']; ?></td>
                                </tr>
                                <tr>
                                    <td><?= $this->translate('capacity'); ?></td>
                                    <td><?= $card['Model']['capacity']; ?></td>
                                </tr>
                                <tr>
                                    <td><?= $this->translate('horsepower'); ?></td>
                                    <td><?= $card['Model']['horsepower']; ?></td>
                                </tr>
                            </table>
                            <button class="lockTheCard label btn btn-success" data-rel="<?= $card['id']; ?>"><i class="fa fa-unlock"></i> <?= $this->translate('Unlock the card'); ?></button>
                <a href="/card/delete-card/<?= $card['id'];?>" data-name="<?= $card['Model']['name']; ?>" class="deleteCard btn btn-danger label"><i class="fa fa-trash-o"></i> <?= $this->translate('Delete card'); ?></a>
                        </div>
                </td>
                        <?php 
                        }
                        else{
                            echo "<td class='lockedCardCol'></td>";
                        }
                endfor; ?>
                
            </tr>

            <tr class="lockedCardRow">
                <?php for($i=4;$i<8;$i++): 
                    if(isset($lockedCards[$i])){
                        $card = $lockedCards[$i];
                        
                        ?>
                <td class="lockedCardCol">
                        <div class="playerCard" data-rel="<?= $card['id']; ?>">
                            <?php if($card['locked']){ ?>
                            <img src="/images/layout/lock.png" class="cardLock" />
                            <?php } ?>
                            <table>
                                <tr>
                                    <th colspan="2">

                                        <img src="/media/cars/<?= $card['Model']['photo']; ?>" />
                                        <strong><?= $card['Model']['name']; ?></strong>
                                    </th>
                                </tr>
                                <tr>
                                    <td><?= $this->translate('acceleration'); ?></td>
                                    <td><?= $card['Model']['acceleration']; ?></td>
                                </tr>
                                <tr>
                                    <td><?= $this->translate('v-max'); ?></td>
                                    <td><?= $card['Model']['max_speed']; ?></td>
                                </tr>
                                <tr>
                                    <td><?= $this->translate('capacity'); ?></td>
                                    <td><?= $card['Model']['capacity']; ?></td>
                                </tr>
                                <tr>
                                    <td><?= $this->translate('horsepower'); ?></td>
                                    <td><?= $card['Model']['horsepower']; ?></td>
                                </tr>
                            </table>
                            <button class="lockTheCard  label btn btn-success" data-rel="<?= $card['id']; ?>"><i class="fa fa-unlock"></i> <?= $this->translate('Unlock the card'); ?></button>
                <a href="/card/delete-card/<?= $card['id'];?>" data-name="<?= $card['Model']['name']; ?>" class="deleteCard btn btn-danger label"><i class="fa fa-trash-o"></i> <?= $this->translate('Delete card'); ?></a>
                        </div>
                </td>
                        <?php 
                        }
                        else{
                            echo "<td class='lockedCardCol'></td>";
                        }
                endfor; ?>
            </tr>
        </table>
        
        <?php if($lockedSameType){ ?>
            <a href="/card/transform-cards/<?= $lockedSameType['Model']['id']; ?>" class="btn myBtn transformPlayCards">    
            <?= $this->translate('Turn your play cards into'); ?> <?= $lockedSameType['Model']['name']; ?>
            </a>
        <?php
        }
        ?>
    </div>
</div>


