<?php

/**
 * Market_Model_Doctrine_BaseCarOffer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $car_id
 * @property integer $team_id
 * @property datetime $start_date
 * @property datetime $finish_date
 * @property integer $asking_price
 * @property integer $highest_bid
 * @property boolean $active
 * @property boolean $car_moved
 * @property boolean $canceled
 * @property string $user_ip
 * @property Doctrine_Collection $Bids
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Market_Model_Doctrine_BaseCarOffer extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('market_car_offer');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('car_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('team_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('start_date', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('finish_date', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('asking_price', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('highest_bid', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('car_moved', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('canceled', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('user_ip', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Market_Model_Doctrine_CarBid as Bids', array(
             'local' => 'id',
             'foreign' => 'offer_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}