<?php

/**
 * Market_Model_Doctrine_CarDuplicate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Market_Model_Doctrine_CarDuplicate extends Market_Model_Doctrine_BaseCarDuplicate
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Market_Model_Doctrine_CarOffer as Offer', array(
             'local' => 'offer_id',
             'foreign' => 'id'));

        $this->hasOne('Market_Model_Doctrine_CarBid as Bid', array(
             'local' => 'bid_id',
             'foreign' => 'id'));
    }
}