<?php

/**
 * Market_Model_Doctrine_PeopleDuplicateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Market_Model_Doctrine_PeopleDuplicateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Market_Model_Doctrine_PeopleDuplicateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Market_Model_Doctrine_PeopleDuplicate');
    }
}