<?php

/**
 * News_Model_Doctrine_NewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class News_Model_Doctrine_NewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object News_Model_Doctrine_NewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('News_Model_Doctrine_News');
    }
}