<?php if(isset($message))
    echo $message;
?>
<h2>Sell news</h2>
<?php if(isset($news['Model']['photo'])&&strlen($news['Model']['photo'])){ ?>
        <img src="/media/newss/<?php echo $news['Model']['photo']; ?>" alt="<?php echo $news['Model']['name']; ?>" style="width:300px;float:right;margin-right:100px;" />
   <?php } ?>
News name: <?php echo $news['name']; ?> <br />
    <div class="changeNewsName" id="changeNewsName1">
	<?php // echo $formNews1->renderForm(); ?>
    </div>
    Marka: <?php echo $news['Model']['name']; ?><br />
    Przebieg: <?php echo $news['mileage']; ?><br />
    Wartość: <?php echo $news['value']; ?><br />
    Koszty utrzymania: <?php echo $news['upkeep']; ?><br />
<div class="clearfix"></div>
<form method="POST">
    <label for="asking_price">Asking price</label>
    <?php echo $form->getElement('asking_price')->renderElement(); ?>

    <label for="asking_price">Days on the market</label>
    <?php echo $form->getElement('days')->renderElement(); ?>
    
    <label for="selling_fee">Selling fee</label>
    <?php echo $form->getElement('selling_fee')->renderElement(); ?>

    <?php echo $form->getElement('submit')->renderElement(); ?>
</form>
<script>
    $(document).ready(function(){
        $('#asking_price').keyup(function(){
            var asking_price = $(this).val();
            if($.isNumeric(asking_price)){
                var selling_fee = Math.round(0.0125*asking_price);
                if(selling_fee > 5000){
                    selling_fee = 5000;
                }
                if(selling_fee < 150){
                    selling_fee = 150;
                }
                
                $('#selling_fee').val(selling_fee);
            }
            else{
                $('#selling_fee').val('');
            }
        });
        
    });
</script>