<?php
if(isset($_GET['msg'])){
    if($_GET['msg']=="bought"){
        $this->showSuccess($this->translate('Gold membership was succesfully bought. Enjoy our').'<img src="/images/layout/gc_small.png"> features until '.TK_Text::timeFormat($authenticatedUser['gold_member_expire'],'d/m/Y H:i'));
    }
    elseif($_GET['msg']=="no prem"){
        $this->showError($this->translate("Sorry,you don't have enough premium.")." <a href='/account/premium'>".$this->translate('Buy more premium')."</a>");
    }
    
}?>
<div class="mainUserBox">
        <h4 class="boxHeader"><?= $this->translate('Gold membership'); ?></h4>
        <div class='goldMembershipWrapper'>
            <?= $this->translate('Gold membership is a package which allows you to benefit of additional in-game features. Check what privileges'); ?> <img src="/images/layout/gc_small.png"> <?= $this->translate('users poses.'); ?>
            <table class='goldMembershipTable'>
                <thead>
                    <tr>
                        <th></th>
                        <th><?= $this->translate('Basic user'); ?></th>
                        <th><img src="/images/layout/gc_small.png" /> <?= $this->translate('user'); ?></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><?= $this->translate('Creating friendly rally'); ?></td>
                        <td>10 <img class="coin" src="/images/layout/coin.png" /></td>
                        <td><?= $this->translate('3 rallies every month for free. Every next costs 5'); ?> <img class="coin" src="/images/layout/coin.png" /></td>
                    </tr>
                    <tr>
                        <td colspan="3" class="gmFeatureDesc">
                            <?= $this->translate('Invite your friends and check who is the fastest or create a public rally and challenge random players.'); ?>
                        </td>
                    </tr>
                    <tr>
                        <td><?= $this->translate('Joining friendly rally'); ?></td>
                        <td>10 <img class="coin" src="/images/layout/coin.png" /></td>
                        <td><?= $this->translate('3 rallies every month for free. Every next costs 5');?> <img class="coin" src="/images/layout/coin.png" /></td>
                    </tr>
                    <tr>
                        <td colspan="3" class="gmFeatureDesc">
                            <?= $this->translate('Join friendly rally, give yourself a chance to beat other drivers and earn additional game cash.');?>
                        </td>
                    </tr>
                    <tr>
                        <td><?= $this->translate('Detailed financial report'); ?></td>
                        <td><span class='red'><i class="fa fa-times"></i></span></td>
                        <td><span class='green'><i class="fa fa-check"></i></span></td>
                    </tr>
                    <tr>
                        <td colspan="3" class="gmFeatureDesc">
                            <?= $this->translate("Don't know where this cash cames from? No problem. In our detailed report you can see exact source of every income and expense."); ?>
                        </td>
                    </tr>
                    <tr>
                        <td><?= $this->translate('Joining big rally'); ?></td>
                        <td>15 <img class="coin" src="/images/layout/coin.png" /></td>
                        <td>5 <img class="coin" src="/images/layout/coin.png" /></td>
                    </tr>
                    <tr>
                        <td colspan="3" class="gmFeatureDesc">
                            <?= $this->translate('Try to beat other drivers and compete for great prizes like unique cars and premium points.'); ?>
                        </td>
                    </tr>
                    <tr>
                        <td><?= $this->translate('Forum and transfer boxes');?></td>
                        <td><span class='red'><i class="fa fa-times"></i></span></td>
                        <td><span class='green'><i class="fa fa-check"></i></span></td>
                    </tr>
                    <tr>
                        <td colspan="3" class="gmFeatureDesc">
                            <?= $this->translate('Never miss out your transfer offer or important thread. With forum and transfer boxes you see all important information immediately after log in.');?>
                        </td>
                    </tr>
                    <tr>
                        <td><?= $this->translate('Advertisments on site');?></td>
                        <td><span class='green'><i class="fa fa-check"></i></span></td>
                        <td><span class='red'><i class="fa fa-times"></i></span></td>
                    </tr>
                    <tr>
                        <td colspan="3" class="gmFeatureDesc">
                            <?= $this->translate('Get rid of all annoying advertisments on your FastRally account.'); ?>
                        </td>
                    </tr>
                </tbody>
            </table>
            
        
        
            <?php if($authenticatedUser['gold_member']): ?>
                <div class="goldCoinBox">
                    <?= $this->translate('You are currently a');?> <img src="/images/layout/gc_small.png"> <?= $this->translate('member. Your membership expires at'); ?> <?= TK_Text::timeFormat($authenticatedUser['gold_member_expire'],'d/m/y H:i'); ?>
                    <br />
                    <?= $this->translate('Your account balance');?>: <?= $authenticatedUser['premium']; ?><img class="coin" src="/images/layout/coin.png">
                </div>
            <?php else: ?>
                <div class="notGoldCoinBox label-danger">
                    <?= $this->translate('You are not a');?> <img src="/images/layout/gc_small.png"> <?= $this->translate('member. Buy your package now.'); ?>
                    <br />
                    <?= $this->translate('Your account balance');?>: <?= $authenticatedUser['premium']; ?><img class="coin" src="/images/layout/coin.png">
                </div>
            <?php endif; ?>
            </div>
        <div class="buyGoldBox">
            
            <form class="form-horizontal" method="POST">
                    <h3 for='gold'><?= $this->translate('Buy');?>  <img src="/images/layout/gc_big.png"> <?= $this->translate('Package'); ?></h3> <br />
                        <!--<img class="coin" src="/images/layout/coin.png" /></label>-->
                    <?php echo $form->getElement('gold')->renderElementFromMulti('<img src="/images/layout/coin.png" />'); ?>
                    
                    <div class='clearfix'></div>
                <?php echo $form->getElement('submit')->renderElement(); ?>
            </form>
        </div>
</div>
<script>
    $(document).ready(function(){
        $('.buyGoldBox .radio input').on('click',function(){
            var input = $(this);
            var wrapper = input.parent().parent();
            console.log(wrapper);
            if(input.is(':checked')){
                $('.buyGoldBox .radio').removeClass('active');
                wrapper.addClass('active');
            }
        });
    });
</script>