<link rel="stylesheet" type="text/css" href="/plugins/wowslider/engine1/style.css" />
<script type="text/javascript" src="/plugins/wowslider/engine1/jquery.js"></script>
<div class="lastNewses mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('News') ;?></h4>
    <?php foreach($lastNewses as $news): ?>
    <div class="newsItem">
        <div class="newsTitle">
            <?php echo $news['title']; ?>
            <div class="newsDate">
                <?php echo TK_Text::timeFormat($news['publish_date'], 'd/m/Y H:i'); ?>
            </div>
        </div>
        <div class="newsContent"><?php echo $news['content']; ?></div>
    </div>

    <?php endforeach; ?>
</div>
