<script>
    $(document).ready(function(){
	$('#btnChangeCarNameButton1').click(function(){
	    if($('#changeCarName1').is(":visible")){
	       $('#changeCarName1').hide(); 
	    }
	    else{
	       $('#changeCarName1').show(); 
	    }
	});
        $('.bxslider').bxSlider();
    });
</script>

<script src="/plugins/bxslider/jquery.bxslider.js"></script>
<link href="/plugins/bxslider/jquery.bxslider.css" rel="stylesheet" />

<?php $team = $authenticatedUser['Team']; ?>
<div class="mainUserBox myCarsBox">
    <h4 class="boxHeader"><?= $this->translate('Garage'); ?></h4>
    <?php 
        if(isset($_GET['msg'])){
            if($_GET['msg']=="car on market"){
                $this->showError($this->translate("This car is already on market"));
            }
            elseif($_GET['msg']=="no cash"){
                $this->showError($this->translate("Sorry. You don't have enough money to pay selling fee."));
            }
            elseif($_GET['msg']=="no money"){
                $this->showError($this->translate("Sorry. You don't have enough money to pay scrapping fee."));
            }
            elseif($_GET['msg']=="no money"){
                $this->showError($this->translate("Sorry. You can't scrap car which is on the market."));
            }
            elseif($_GET['msg']=="not enough money"){
                $this->showError($this->translate("Sorry. You don't have enough money to pay scrapping fee and all your bids"));
            }
            elseif($_GET['msg']=="car bought"){
                $this->showSuccess($this->translate("You have successfully bought a car. You can now see it in your garage."));
            }
            
            elseif($_GET['msg']=="in rally"){
                $this->showError($this->translate("Sorry. You can't sell a car which is signed up for rally."));
            }
            elseif($_GET['msg']=="scrap in rally"){
                $this->showError($this->translate("Sorry. You can't scrap a car which is signed up for rally."));
            }
            elseif($_GET['msg']=="name changed"){
                $this->showSuccess($this->translate("Car name successfully changed."));
            }
            elseif($_GET['msg']=="car scrapped"){
                $this->showSuccess($this->translate("Car has successfully been scrapped."));
            }
        }
    ?>
    <div class="myCars peopleList carList col-md-12">
        
        <ul class="bxslider carSlider">
            <?php foreach($cars as $key => $car): ?>
            <li data-rel="<?= $car['id']; ?>"><?php echo $car['name']; ?>
            
                <div class="carCard" data-id="<?= $car['id']; ?>">
            <div class="col-md-6">
                
        <!--    Car name: <?php echo $car['name']; ?> <a href="javascript:void(0)" id="btnChangeCarNameButton1">change name</a><br />
            <div class="changeCarName" id="changeCarName1">
                <?php // echo $formCar1->renderForm(); ?>
            </div>-->
                <?= TK_Helper::showCarParameters($car); ?>
                
            <div class="clearfix"></div>
            <div class="carBtn">
                <?php if(!$car['on_market']): ?>
                    <a class="btn sellPlayer myBtn sellCar" type="button" data-toggle="modal" data-target="#sellCar" href="javascript:void(0)" data-name="<?= $car['name']; ?>"  rel="<?php echo $car['id']; ?>"> <i class="fa fa-money"></i> <?= $this->translate('Sell car'); ?></a>
                <?php else: ?>
                    <a href="#" class="btn sellPlayer myBtn sellCar" disabled><?= $this->translate('Car on market');?></a>
                <?php endif; ?>
                <a class="btn sellPlayer myBtn changeCarName" href="/car/change-name/<?= $car['id']; ?>">
                    <i class="fa fa-edit"></i> <?= $this->translate('Change name');?>
                </a>
                    
                    <br />
                <a class="scrapCar" onclick="if(!confirm('Are you sure you want to scrap this car? \r\n This will cost you 1% of car value')){return false;}" href="/car/scrap-car/<?= $car['id']; ?>" title="Scrap your car. This will cost you 1% of its value">
                    <i class="fa fa-trash-o"></i> <?= $this->translate('Scrap this car');?> 
                </a>
            </div>

            </div>
                    <div class="col-md-6">
            <?php if(isset($car['Model']['photo'])&&strlen($car['Model']['photo'])){ ?>
                <img src="/media/cars/<?php echo $car['Model']['photo']; ?>" alt="<?php echo $car['Model']['name']; ?>" class="carCardPhoto" />
           <?php } 
                else{ ?>
                    <img src="http://dummyimage.com/340x220&amp;text=No+photo" class="carCardPhoto" />
            <?php } ?>           
                    </div>
            <div class="clearfix"></div>
        </div>
            </li>
        <?php endforeach; ?>
        </ul>
    </div>

    <div id="sellCar" class="modal fade" role="dialog">
      <div class="modal-dialog">

            <form method="POST" action="/car/sell-car">
                <!-- Modal content-->
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"><?= $this->translate('Sell car'); ?> <span id="sellCarName"></span></h4>
                  </div>
                  <div class="modal-body">
                        <div class="form-group">
                            <label for="asking_price" class="control-label"><?= $this->translate('Asking price'); ?></label>
                            <?php echo $form->getElement('asking_price')->renderElement(); ?>
                        </div>

                        <div class="form-group">
                            <label for="asking_price" class="control-label"><?= $this->translate('Days on the market'); ?></label>
                            <?php echo $form->getElement('days')->renderElement(); ?>
                        </div>

                        <div class="form-group">
                            <label for="selling_fee" class="control-label"><?= $this->translate('Selling fee'); ?></label>
                            <?php echo $form->getElement('selling_fee')->renderElement(); ?>
                        </div>
                        <input type="hidden" name="car_id" id="car_id" /> 

                  </div>
                  <div class="modal-footer">
                    <?php echo $form->getElement('submit')->renderElement(); ?>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->translate('Close'); ?></button>
                  </div>
                </div>
            </form>

      </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $('#asking_price').keyup(function(){
            var asking_price = $(this).val();
            if($.isNumeric(asking_price)){
                var selling_fee = Math.round(0.0125*asking_price);
                if(selling_fee > 5000){
                    selling_fee = 5000;
                }
                if(selling_fee < 150){
                    selling_fee = 150;
                }
                
                $('#selling_fee').val(selling_fee);
            }
            else{
                $('#selling_fee').val('');
            }
        });
        
        
        $('.sellCar').click(function(){
           var rel = $(this).attr('rel');
           $('#car_id').val(rel);
           $('#sellCarName').html($(this).attr('data-name'));
        });
    });
</script>