<script>
    $(document).ready(function(){
	$('#btnChangeCarNameButton1').click(function(){
	    if($('#changeCarName1').is(":visible")){
	       $('#changeCarName1').hide(); 
	    }
	    else{
	       $('#changeCarName1').show(); 
	    }
	});
    });
</script>


<?php $team = $authenticatedUser['Team']; ?>
<div class="mainUserBox myCarsBox">
    <h4 class="boxHeader"><?= $this->translate('My cars'); ?></h4>
    <?php 
        if(isset($_GET['msg'])){
            if($_GET['msg']=="car on market"){
                $this->showError($this->translate("This car is already on market"));
            }
            elseif($_GET['msg']=="no cash"){
                $this->showError($this->translate("Sorry. You don't have enough money to pay selling fee."));
            }
            elseif($_GET['msg']=="car bought"){
                $this->showSuccess($this->translate("You have successfully bought a car. You can now see it in your garage."));
            }
            
            elseif($_GET['msg']=="in rally"){
                $this->showError($this->translate("Sorry. You can't sell car who is signed up for rally."));
            }
            
            elseif($_GET['msg']=="name changed"){
                $this->showSuccess($this->translate("Car name successfully changed."));
            }
        }
    ?>
    <div class="myCars">
    <?php foreach($cars as $key => $car): ?>
        <div class="carCard">

            <?php if(isset($car['Model']['photo'])&&strlen($car['Model']['photo'])){ ?>
                <img src="/media/cars/<?php echo $car['Model']['photo']; ?>" alt="<?php echo $car['Model']['name']; ?>" class="carCardPhoto" />
           <?php } 
                else{ ?>
                    <img src="http://dummyimage.com/340x220&amp;text=No+photo" class="carCardPhoto" />
            <?php } ?>
            <strong><?= $car['name']; ?></strong>
            
           
            <div class="col-md-6">
                
        <!--    Car name: <?php echo $car['name']; ?> <a href="javascript:void(0)" id="btnChangeCarNameButton1">change name</a><br />
            <div class="changeCarName" id="changeCarName1">
                <?php // echo $formCar1->renderForm(); ?>
            </div>-->
                <ul>
                    <li>
                        <?= $this->translate('Mileage');?>: <?php echo $car['mileage']; ?>
                    </li>
                    <li>
                        <?= $this->translate('Value');?>:<?php echo $car['value']; ?>
                    </li>
                    <li>
                        <?= $this->translate('Upkeep');?>: <?php echo $car['upkeep']; ?>
                    </li>
                </ul>
                <div class="clearfix"></div>
            <div class="carBtn">
                <?php if(!$car['on_market']): ?>
                    <a class="btn sellCar" type="button" data-toggle="modal" data-target="#sellCar" href="javascript:void(0)" data-name="<?= $car['name']; ?>"  rel="<?php echo $car['id']; ?>"> <i class="fa fa-money"></i> <?= $this->translate('Sell car'); ?></a>
                <?php else: ?>
                    <a href="#" class="btn" disabled><?= $this->translate('Car is on the market');?></a>
                <?php endif; ?>
                <a class="btn" href="/car/change-name/id/<?= $car['id']; ?>">
                    <i class="fa fa-edit"></i> <?= $this->translate('Change name');?>
                </a>
            </div>

            </div>
            <div class="col-md-6 pr0 pl0 carParametersWrapper">

                <div class="carParameters">
                 <table>
                    <tr>
                        <td><?= $this->translate('brand'); ?></td>
                        <td><?php echo $car['Model']['name']; ?></td>
                    </tr>
                    <tr>
                        <td><?= $this->translate('capacity'); ?></td>
                        <td><?php echo $car['Model']['capacity'];?></td>
                    </tr>
                    <tr>
                        <td><?= $this->translate('horse power'); ?></td>
                        <td><?php echo $car['Model']['horsepower'];?></td>
                    </tr>
                    <tr>
                        <td><?= $this->translate('v-max'); ?></td>
                        <td><?php echo $car['Model']['max_speed'];?></td>
                    </tr>
                    <tr>
                        <td><?= $this->translate('acceleration'); ?></td>
                        <td><?php echo $car['Model']['acceleration'];?></td>
                    </tr>

                </table>
            </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <?php endforeach; ?>
    </div>

    <div id="sellCar" class="modal fade" role="dialog">
      <div class="modal-dialog">

            <form method="POST" action="/car/sell-car">
                <!-- Modal content-->
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"><?= $this->translate('Sell car'); ?> <span id="sellCarName"></span></h4>
                  </div>
                  <div class="modal-body">
                        <div class="form-group">
                            <label for="asking_price" class="control-label"><?= $this->translate('Asking price'); ?></label>
                            <?php echo $form->getElement('asking_price')->renderElement(); ?>
                        </div>

                        <div class="form-group">
                            <label for="asking_price" class="control-label"><?= $this->translate('Days on the market'); ?></label>
                            <?php echo $form->getElement('days')->renderElement(); ?>
                        </div>

                        <div class="form-group">
                            <label for="selling_fee" class="control-label"><?= $this->translate('Selling fee'); ?></label>
                            <?php echo $form->getElement('selling_fee')->renderElement(); ?>
                        </div>
                        <input type="hidden" name="car_id" id="car_id" /> 

                  </div>
                  <div class="modal-footer">
                    <?php echo $form->getElement('submit')->renderElement(); ?>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->translate('Close'); ?></button>
                  </div>
                </div>
            </form>

      </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $('#asking_price').keyup(function(){
            var asking_price = $(this).val();
            if($.isNumeric(asking_price)){
                var selling_fee = Math.round(0.0125*asking_price);
                if(selling_fee > 5000){
                    selling_fee = 5000;
                }
                if(selling_fee < 150){
                    selling_fee = 150;
                }
                
                $('#selling_fee').val(selling_fee);
            }
            else{
                $('#selling_fee').val('');
            }
        });
        
        
        $('.sellCar').click(function(){
           var rel = $(this).attr('rel');
           $('#car_id').val(rel);
           $('#sellCarName').html($(this).attr('data-name'));
        });
    });
</script>