
<?php $financeTypes = TeamService::getInstance()->getFinanceTypes(); ?>
<div class="mainUserBox ">
    <h4 class="boxHeader"><?= $this->translate('My finances'); ?></h4>
    <div class="myFinances">
        <div class="accountBalance">
            <?= $this->translate('Account balance'); ?>:  <strong><?php echo $team['cash'];?>$ </strong>
        </div>
        <br /><br />

        <h5><?= $this->translate('This week'); ?></h5>
        <div class="col-md-6 incomeBox">
            <span class="financeSubHeader"><?= $this->translate('Incomes'); ?></span> 
            <br />
            <?php 
            foreach($financialReportSimple['income'] as $simpleReport): 
                echo $financeTypes[$simpleReport['detailed_type']]." - ".$simpleReport['amount']; ?>$<br />

            <?php endforeach; ?>
        </div>
        <div class="col-md-6 expenseBox">
            <span class="financeSubHeader"><?= $this->translate('Expenses'); ?></span> <br />
            <?php 
            foreach($financialReportSimple['expense'] as $simpleReport2): 
                echo $financeTypes[$simpleReport2['detailed_type']]." - ".$simpleReport2['amount']; ?>$<br />
            <?php endforeach; ?>
        </div>
        <div class="clearfix"></div>
        <h5><?= $this->translate('Last week'); ?></h5>
        <div class="col-md-6 incomeBox">
            <span class="financeSubHeader"><?= $this->translate('Incomes'); ?></span> 
            <br />
            <?php 
            foreach($financialReportSimpleLastWeek['income'] as $simpleReport): 
                echo $this->translate($financeTypes[$simpleReport['detailed_type']])." - ".$simpleReport['amount']; ?>$<br />

            <?php endforeach; ?>
        </div>
        <div class="col-md-6 expenseBox">
            <span class="financeSubHeader"><?= $this->translate('Expenses'); ?></span> <br />
            <?php 
            foreach($financialReportSimpleLastWeek['expense'] as $simpleReport2): 
                echo $financeTypes[$simpleReport2['detailed_type']]." - ".$simpleReport2['amount']; ?>$<br />
            <?php endforeach; ?>
        </div>
        <div class="clearfix"></div>
        <div class="advancedFinanceReport">
        <?php if($authenticatedUser['gold_member']): ?>
            <h5><?= $this->translate('Advanced report'); ?></h5>
            <table class="table" id="advancedFinancialReport">
                <thead>
                    <tr>
                        <th>Amount</th>
                        <th>Description</th>
                        <th>Detailed type</th>
                        <th>Type</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($financialReportAdvanced as $advancedReport):
                    ?>
                <tr>
<!--                    <div class="<?php echo ($advancedReport['income'])?'advancedReportIncome label label-success':'advancedReportExpense label label-danger';?>">
                        <i class="fa fa-money" title="Amount"></i>-->
                        <td>
                            <?= $advancedReport['amount']; ?>
                        </td>
                        <td>
                            <?= $this->translate($advancedReport['description']); ?>
                        </td>
                        <td> 
                            <?php if($advancedReport['income']){ ?>
                                <span class="label label-success">Income</span>
                            <?php } else { ?>
                                <span class="label label-danger">Expense</span>
                            <?php } ?>
                            <?; ?>
                        </td>
                        <td>
                            <?= $this->translate($financeTypes[$advancedReport['detailed_type']]); ?>
                        </td>
                        <td>
                            <?= $advancedReport['save_date']; ?>
                        </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
            </table>
                    <div class="clearfix"></div>
             <script src="/plugins/datatables/jquery.dataTables.js"></script>
                <link rel="stylesheet" href="/plugins/datatables/jquery.dataTables.css">       
                <script>
                    $(document).ready(function(){
                        $('#advancedFinancialReport').DataTable({

                       "bLengthChange": false,
                        "pagingType": "numbers",
                        "lengthMenu": [[-1], ["All"]],
        "order": [[ 3, "desc" ]],
        
  "columns": [
    null,
    null,
    null,
    null,
    
    { "width": "15%" },
  ]
                        });
                    });
                </script>
            <?php else: ?>
            <div class="noGoldAvancedReport">
                <h5><?= $this->translate('Advanced report'); ?></h5>
                <div class="goldOverlay">
                    <a href="#">
                        <img src="/images/layout/gc_big.png">
                    </a>
                </div>
            </div>
            <?php endif; ?>
        </div>
        
    </div>
</div>