Stan konta : <?php echo $team['cash'];?>$ 
<br /><br /><br />

<h3>Raport finansowy</h3>
<hr />
<h2>Simple report</h2>

<div class="col-md-6">
    <h4>Wpływy</h4>
    <?php foreach($financialReportAdvanced as $advancedReport): 
        endforeach; ?>
</div>
<div class="col-md-6">
    <h4>Wydatki</h4>
</div>

<h2>Advanced report </h2>
<div class="col-md-6">
    <h4>Wpływy</h4>
</div>
<div class="col-md-6">
    <h4>Wydatki</h4>
</div>