<div class="mainUserBox myPeopleWrapper">
    <h4 class="boxHeader">My people</h4> 
    <div class="myPeople">
        <?php foreach($teamPeople as $person): ?>
            <div class="peopleCard">
                <strong><?php echo $person['last_name']." ".$person['first_name']; ?></strong><br />
                <div class="col-md-5 peopleLeft">
                    <table>
                        <tr>
                            <td>
                                Job:
                            </td>
                            <td>
                                <?php
                                    if($person['job']=="driver"):
                                        echo '<img src="/images/layout/driving-wheel.png" title='.$person['job'].'  lt='.$person['job'].' />';
                                    else:
                                        echo '<i class="fa fa-book" title='.$person['job'].' ></i>';
                                    endif;
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Age:
                            </td>
                            <td>
                                <?php echo $person['age']; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Value:
                            </td>
                            <td>
                                <?php echo $person['value']; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Salary:
                            </td>
                            <td>
                                <?php echo $person['salary']; ?>
                            </td>
                        </tr>
                    </table>
                     <div class="peopleBtn">
                        <?php if(!$person['on_market']): ?>
                            <a class="btn" href="/people/sell-player/id/<?php echo $person['id']; ?>"><i class="fa fa-money"></i> Sell player</a>
                        <?php else: ?>
                            Player is on the market
                        <?php endif; ?>
                     </div>
                </div>
                <div class="col-md-7 peopleRight">
                    <?php if($person['job'] == "driver"): ?>
                    <table>
                        <tr>
                            <td>Composure</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'composure'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Speed</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'speed'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Regularity</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'regularity'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Reflex</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'reflex'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Driving on gravel</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'on_gravel'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Driving on tarmac</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'on_tarmac'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Driving on snow</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'on_snow'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Driving in rain</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'in_rain'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Talent</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'talent'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Form</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'form'); ?>
                            </td>
                        </tr>
                    </table>
                    <?php else: ?>
                    <table>
                        <tr>
                            <td>Composure</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'composure'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Dictate rhytm</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'dictate_rhytm'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Diction</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'diction'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Route description</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'route_description'); ?>
                            </td>
                        </tr>

                        <tr>
                            <td>Talent</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'talent'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Form</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'form'); ?>
                            </td>
                        </tr>
                    </table>
                    <?php endif; ?>

                </div>




                        <div class="clearfix"></div>


            </div>
        <?php endforeach; ?>
    </div>
</div>