<?php 
        if(isset($_GET['msg'])){
            if($_GET['msg']=="player on market"){
                $this->showError($this->translate('This player is already on market'));
            }
            elseif($_GET['msg']=="no cash"){
                $this->showError($this->translate("Sorry. You don't have enough money to pay selling fee."));
            }
            elseif($_GET['msg']=="in rally"){
                $this->showError($this->translate("Sorry. You can't sell player who is signed up for rally."));
            }
            elseif($_GET['msg']=="free agent acquired"){
                $this->showSuccess($this->translate("Free agent has been acquired."));
            }
        }
    ?>
<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('My people'); ?></h4> 
    
    <div class="myPeople peopleList driverList col-md-12">
        <ul>
            <li><?= $this->translate('Drivers'); ?></li>
            <?php foreach($teamPeople['Drivers'] as $key => $person): ?>
            <li data-rel="<?= $person['id']; ?>" <?php echo ($key==0)?'class="active"':'';?>><?php echo $person['last_name']." ".$person['first_name']; ?></li>
            <?php endforeach; ?>
        </ul>
        <?php foreach($teamPeople['Drivers'] as $key=>$person): ?>
            <div class="peopleCard <?php echo ($key==0)?'active':'';?>" data-id="<?= $person['id']; ?>">
                <div class="col-md-4 peopleLeft">
                    <table>
                        <tr>
                            <td>
                                <?= $this->translate('Job'); ?>:
                            </td>
                            <td>
                                <?= $person['job']; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->translate('Age'); ?>:
                            </td>
                            <td>
                                <?php echo $person['age']; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->translate('Value'); ?>:
                            </td>
                            <td>
                                <?php echo $person['value']; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->translate('Salary'); ?>:
                            </td>
                            <td>
                                <?php echo $person['salary']; ?>
                            </td>
                        </tr>
                        <?php if($person['on_market']): ?>
                        <tr>
                            <td>
                                <?= $this->translate('Status'); ?>:
                            </td>
                            <td>
                                <?= $this->translate('On market'); ?>
                            </td>
                        </tr>
                        <?php endif; ?>
                     
                    </table>
                    <div class="peopleBtn">
                        <?php if(!$person['on_market']): ?>
                            <a class="btn sellPlayer myBtn" type="button" data-toggle="modal" data-target="#sellPlayer" href="javascript:void(0)" data-name='<?php echo $person['last_name']." ".$person['first_name']; ?>' rel='<?php echo $person['id']; ?>'><?= $this->translate('SELL'); ?></a>
                       <?php endif; ?>
                     </div>
                </div>
                <div class="col-md-8 peopleRight">
                    <?= TK_Helper::showPersonDetails($person,true); ?>

                </div>

                <div class="clearfix"></div>


            </div>
        <?php endforeach; ?>
    </div>
    <div class="myPeople peopleList pilotList col-md-12">
        <ul>
            <li><?= $this->translate('Pilots'); ?></li>
            <?php foreach($teamPeople['Pilots'] as $key => $person): ?>
            <li data-rel="<?= $person['id']; ?>" <?php echo ($key==0)?'class="active"':'';?>><?php echo $person['last_name']." ".$person['first_name']; ?></li>
            <?php endforeach; ?>
        </ul>
        <?php foreach($teamPeople['Pilots'] as $key=>$person): ?>
            <div class="peopleCard <?php echo ($key==0)?'active':'';?>" data-id="<?= $person['id']; ?>">
                <div class="col-md-4 peopleLeft">
                    <table>
                        <tr>
                            <td>
                                <?= $this->translate('Job'); ?>:
                            </td>
                            <td>
                                <?= $person['job']; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->translate('Age'); ?>:
                            </td>
                            <td>
                                <?php echo $person['age']; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->translate('Value'); ?>:
                            </td>
                            <td>
                                <?php echo $person['value']; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->translate('Salary'); ?>:
                            </td>
                            <td>
                                <?php echo $person['salary']; ?>
                            </td>
                        </tr>
                        <?php if($person['on_market']): ?>
                        <tr>
                            <td>
                                <?= $this->translate('Status'); ?>:
                            </td>
                            <td>
                                <?= $this->translate('On market'); ?>
                            </td>
                        </tr>
                        <?php endif; ?>
                     
                    </table>
                    <div class="peopleBtn">
                        <?php if(!$person['on_market']): ?>
                            <a class="btn sellPlayer myBtn" type="button" data-toggle="modal" data-target="#sellPlayer" href="javascript:void(0)" data-name='<?php echo $person['last_name']." ".$person['first_name']; ?>' rel='<?php echo $person['id']; ?>'><?= $this->translate('SELL'); ?></a>
                       <?php endif; ?>
                     </div>
                </div>
                <div class="col-md-8 peopleRight">
                    <?= TK_Helper::showPersonDetails($person,true); ?>

                </div>

                <div class="clearfix"></div>


            </div>
        <?php endforeach; ?>
    </div>
</div>

    <div id="sellPlayer" class="modal fade" role="dialog">
      <div class="modal-dialog">

          
          
            <form method="POST" action="/people/sell-player">
        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title"><?= $this->translate('Sell player'); ?> <span id="sellPlayerName"></span></h4>
          </div>
          <div class="modal-body">
                <div class="form-group">
                    <label for="asking_price" class="control-label"><?= $this->translate('Asking price'); ?></label>
                    <?php echo $form->getElement('asking_price')->renderElement(); ?>
                </div>

                <div class="form-group">
                    <label for="asking_price" class="control-label"><?= $this->translate('Days on the market'); ?></label>
                    <?php echo $form->getElement('days')->renderElement(); ?>
                </div>

                <div class="form-group">
                    <label for="selling_fee" class="control-label"><?= $this->translate('Selling fee'); ?></label>
                    <?php echo $form->getElement('selling_fee')->renderElement(); ?>
                </div>
                <input type="hidden" name="player_id" id="player_id" value="<?= $person['id']; ?>" /> 

          </div>
          <div class="modal-footer">
            <?php echo $form->getElement('submit')->renderElement(); ?>
            <button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->translate('Close'); ?></button>
          </div>
        </div>
            </form>

      </div>
    </div>

<script>
    $(document).ready(function(){
        $('#asking_price').keyup(function(){
            var asking_price = $(this).val();
            if($.isNumeric(asking_price)){
                var selling_fee = Math.round(0.0125*asking_price);
                if(selling_fee > 5000){
                    selling_fee = 5000;
                }
                if(selling_fee < 150){
                    selling_fee = 150;
                }
                
                $('#selling_fee').val(selling_fee);
            }
            else{
                $('#selling_fee').val('');
            }
        });
        
        
        $('.sellPlayer').click(function(){
           var rel = $(this).attr('rel');
           $('#player_id').val(rel);
           $('#sellPlayerName').html($(this).attr('data-name'));
        });
        
        $('.driverList li:not(:first-of-type)').click(function(){
            var rel = $(this).attr('data-rel');
            $('.driverList li.active').removeClass('active');
            $('.driverList .peopleCard').removeClass('active');
            $('.driverList .peopleCard').hide();
            
            
            $('.driverList [data-id="'+rel+'"]').show();
            $('.driverList [data-id="'+rel+'"]').addClass('active');
            $(this).addClass('active');
        });
        
        
        $('.pilotList li:not(:first-of-type)').click(function(){
            var rel = $(this).attr('data-rel');
            $('.pilotList li.active').removeClass('active');
            $('.pilotList .peopleCard').removeClass('active');
            $('.pilotList .peopleCard').hide();
            
            
            $('.pilotList [data-id="'+rel+'"]').show();
            $('.pilotList [data-id="'+rel+'"]').addClass('active');
            $(this).addClass('active');
        });
    });
</script>