<?php
    if(isset($_GET['msg'])){
        if($_GET['msg']=="success"&&is_numeric($_GET['amount'])){
            $this->showSuccess($this->translate('You have successfully bought')." ".$_GET['amount']." ".$this->translate('coins'));
        }
    }
?>
<div class="mainUserBox">
        <h4 class="boxHeader"><?= $this->translate('My premium'); ?></h4>
        <div class="goldCoinBox">
            <?php if($authenticatedUser['gold_member']): ?>
                <?= $this->translate('You are currently a'); ?> <img src="/images/layout/gc_small.png"> <?= $this->translate('member. Your membership expires at');?> <?= TK_Text::timeFormat($authenticatedUser['gold_member_expire'],'d/m/y H:i'); ?>
            <?php else: ?>
            
            <?php endif; ?>
            <br />
            <?= $this->translate('Your account balance'); ?>: <?= (int)$authenticatedUser['premium']; ?><img class="coin" src="/images/layout/coin.png">
        </div>
        <div class="addMorePremium">
            <?= $this->translate('Add more'); ?> <img class="coin" src="/images/layout/coin.png" />
            <form class="form-horizontal" method="POST">
                <?php echo $form->getElement('premium')->renderElement(); ?>
                <?php echo $form->getElement('submit')->renderElement(); ?>
            </form>
        </div>
        <h6 class="h4">Premium prices</h6>
        <table class="table">
            <tr>
                <td>100 <img class="coin" src="/images/layout/coin.png" /></td>
                <td rel="2f">
                    <?php
                    try{
                        $currency->setValue(round(2*$rateRow['rate'],2));
                        echo $currency;
                    }
                    catch(Exception $e){
                        echo "&pound; 2.00";
                    }
                    ?> 
                </td>
                <td></td>
            </tr>
            <tr>
                <td>315 <img class="coin" src="/images/layout/coin.png" /></td>
                <td rel="6f">
                    <?php
                    try{
                        $currency->setValue(round(6*$rateRow['rate'],2));
                        echo $currency;
                    }
                    catch(Exception $e){
                        echo "&pound; 6.00";
                    }
                    ?> 
                </td>
                <td>5% more</td>
            </tr>
            <tr>
                <td>550 <img class="coin" src="/images/layout/coin.png" /></td>
                <td rel="10f">
                    <?php
                    try{
                        $currency->setValue(round(10*$rateRow['rate'],2));
                        echo $currency;
                    }
                    catch(Exception $e){
                        echo "&pound; 10.00";
                    }
                    ?> 
                </td>
                <td>10% more</td>
            </tr>
            <tr>
                <td>1150 <img class="coin" src="/images/layout/coin.png" /></td>
                <td rel="20f">
                    <?php
                    try{
                        $currency->setValue(round(20*$rateRow['rate'],2));
                        echo $currency;
                    }
                    catch(Exception $e){
                        echo "&pound; 20.00";
                    }
                    ?> 
                </td>
                <td>15% more</td>
            </tr>
        </table>
		
		<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="TYLEQLX6DV4D8">
<table>
<tr><td><input type="hidden" name="on0" value="Amount">Amount</td></tr><tr><td>
	<input type="radio" name="os0" value="100 points -" />100 points - £2.00 GBP
	<input type="radio" name="os0" value="315 points -" />315 points - £6.00 GBP
	<input type="radio" name="os0" value="550 points -" />550 points - £10.00 GBP
	<input type="radio" name="os0" value="1150 points" />1150 points £20.00 GBP
 </td></tr>
</table>
<input type="hidden" name="currency_code" value="GBP">
<input type="image" src="https://www.sandbox.paypal.com/en_US/GB/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online.">
<img alt="" border="0" src="https://www.sandbox.paypal.com/en_GB/i/scr/pixel.gif" width="1" height="1">
</form>


</div>