<?php
    if(isset($_GET['msg'])){
        if($_GET['msg']=="success"&&is_numeric($_GET['amount'])){
            $this->showSuccess($this->translate('You have successfully bought')." ".$_GET['amount']." ".$this->translate('coins'));
        }
    }
?>
<div class="mainUserBox">
        <h4 class="boxHeader"><?= $this->translate('My premium'); ?></h4>
        <div class="staticWrapper">
        <div class="goldCoinBox goldCoinBoxInfo">
            <?php if($authenticatedUser['gold_member']): ?>
                <?= $this->translate('You are currently a'); ?> <img src="/images/layout/gc_small.png"> <?= $this->translate('member. Your membership expires at');?> <?= TK_Text::timeFormat($authenticatedUser['gold_member_expire'],'d/m/y H:i'); ?>
            <?php else: ?>
            
            <?php endif; ?>
            <br />
            <?= $this->translate('Your account balance'); ?>: <?= (int)$authenticatedUser['premium']; ?><img class="coin" src="/images/layout/coin.png">
        </div>

        <h6 class="h4">Premium prices</h6>
        <table class="table">
            <tr>
                <td>100 <img class="coin" src="/images/layout/coin.png" /></td>
                <td rel="2f">
                    <?php
                    try{
                        $currency->setValue(round(2*$rateRow['rate'],2));
                        echo $currency;
                    }
                    catch(Exception $e){
                        echo "&pound; 2.00";
                    }
                    ?> 
                </td>
                <td></td>
            </tr>
            <tr>
                <td>315 <img class="coin" src="/images/layout/coin.png" /></td>
                <td rel="6f">
                    <?php
                    try{
                        $currency->setValue(round(6*$rateRow['rate'],2));
                        echo $currency;
                    }
                    catch(Exception $e){
                        echo "&pound; 6.00";
                    }
                    ?> 
                </td>
                <td>5% more</td>
            </tr>
            <tr>
                <td>550 <img class="coin" src="/images/layout/coin.png" /></td>
                <td rel="10f">
                    <?php
                    try{
                        $currency->setValue(round(10*$rateRow['rate'],2));
                        echo $currency;
                    }
                    catch(Exception $e){
                        echo "&pound; 10.00";
                    }
                    ?> 
                </td>
                <td>10% more</td>
            </tr>
            <tr>
                <td>1150 <img class="coin" src="/images/layout/coin.png" /></td>
                <td rel="20f">
                    <?php
                    try{
                        $currency->setValue(round(20*$rateRow['rate'],2));
                        echo $currency;
                    }
                    catch(Exception $e){
                        echo "&pound; 20.00";
                    }
                    ?> 
                </td>
                <td>15% more</td>
            </tr>
        </table>
        <div class="addMorePremium">
            <h2> <?= $this->translate('Add more'); ?> <img class="coin" src="/images/layout/coin.png" /></h2>
                    
            <form class="form-horizontal" method="POST" action="/order/process">
               
                <div class="buyPremiumBox">
                    <div class="amountBox">
                        <strong>1. Select amount</strong>
                        <hr />
                        <div class="clearfix"></div>
                        <?php echo $form->getElement('premium')->renderElement(); ?>
                    </div>
                    <div class="clearfix"></div>
                    <div class="providerBox">
                        <strong>2. Choose payment option</strong>
                        <hr />
                        <div class="clearfix"></div>
                        <?php echo $form->getElement('provider')->renderElement(); ?>
                    </div>
                    <?php echo $form->getElement('submit')->renderElement(); ?>
                </div>
            </form>
        </div>
        </div>
        
		


</div>
<script>
    $(document).ready(function(){
        $('.providerBox .radioElemWrapper').on('click',function(){
            var input = $(this).find('input');
//            var wrapper = input.parent();
            var wrapper = $(this);
            input.attr('checked',true);
            $('.providerBox .radioElemWrapper').removeClass('active');
            wrapper.addClass('active');
        });
        
        $('.amountBox .radioElemWrapper input').on('click',function(){
            var input = $(this);
            var wrapper = input.parent();
            if(input.is(':checked')){
                $('.amountBox .radioElemWrapper').removeClass('active');
                wrapper.addClass('active');
            }
        });
    });
</script>