<div class="mainUserBox myCarsBox">
    <h4 class="boxHeader">Sponsor</h4>
    <div class='sponsorListInfo'>
        <i class='fa fa-info-circle'></i> &nbsp;
        <?= $this->translate('Sponsors donate your team every week with $5000. Every sponsor provides the same amount of money.'); ?> </div>
    <div class="sponsorList">
        <?php foreach($sponsors as $sponsor): ?>
        
            <div class="sponsor <?php echo ($sponsor['id']==$user['Team']['sponsor_id'])?"active":""; ?>" data-rel='<?php echo $sponsor['id']; ?>'>
                <form method="POST">
                        <h5><?php echo $sponsor['name']; ?></h5>
                        <div class="col-md-3">
                            <img src="/media/sponsor/<?php echo $sponsor['logo']; ?>" alt="<?php echo $sponsor['name']; ?>" title="<?php echo $sponsor['name']; ?>" />
                            <?php if($sponsor['id']!=$user['Team']['sponsor_id']){ ?>
                                <input type="submit" class="btn btn-primary submitSponsor" value="<?= $this->translate('Choose'); ?> <?= $sponsor['name']; ?>" name="submit_sponsor" />
                            <?php }
                            else{ ?>
                                <a href="/team/cancel-sponsorship" class="removeSponsor btn btn-danger">Cancel sponsorship</a>
                            <?php }
                            ?>
                            <input type="hidden" value="<?= $sponsor['id']; ?>" name="sponsor_id" id='sponsor_id' />
                        </div>
                        <div class="col-md-9">
                            <span><?php echo $sponsor['description']; ?></span>
                        </div>

                </form>
            </div>

        <?php endforeach; ?>
    </div>
</div>