<form method='POST'>
<label>Driver 1</label>
<?php echo $form->getElement('driver1_id')->renderElement(); ?>
<label>Driver 2</label>
<?php echo $form->getElement('driver2_id')->renderElement(); ?>
<label>Pilot 1</label>
<?php echo $form->getElement('pilot1_id')->renderElement(); ?>
<label>Pilot 2</label>
<?php echo $form->getElement('pilot2_id')->renderElement(); ?>
<label>Car 1</label>
<?php echo $form->getElement('car1_id')->renderElement(); ?>
<label>Car 2</label>
<?php echo $form->getElement('car2_id')->renderElement(); ?>
<?php echo $form->getElement('submit')->renderElement(); ?>
</form>