<script>
    $(document).ready(function(){
        var grid = new Datatable();
            grid.init({
                src: $("#datatable_ajax"),
                dataTable: {   
                "aoColumns": [
                        { sWidth: '5%' },
                        { sWidth: '5%' },
                        { sWidth: '15%' },
                        { sWidth: '10%' },
                        { sWidth: '10%' },
                        { sWidth: '5%' },
                        { sWidth: '5%' },
                        { sWidth: '5%' },
                        { sWidth: '5%' },
                        { "bSortable": false, sWidth: '15%' }
                    ],
                    "aLengthMenu": [
                        [20, 50, 100, 150, -1],
                        [20, 50, 100, 150, "All"] // change per page values here
                    ],
                    "iDisplayLength": 20, // default record count per page
                    "bServerSide": true, // server side processing
                    "bLengthChange": false,
                    "bFilter": true,
                    "bDestroy": true,
                    "bProcessing": true,
                    "sAjaxSource": "/admin/rally/list-rally-data", // ajax source
                    "aaSorting": [[ 3, "desc" ]] // set first column as a default sort by asc
                }
            });
               grid.getDataTable().yadcf([
                    {
                      column_number: 1,
                      filter_type: "text"
                    },
                    {
                      column_number: 2,
                      filter_type: "text"
                    },
                    {
                      column_number: 3,
                      filter_type: "range_date"
                    },
                    {
                        column_number: 4,
                        data: [{
                            value: '1',
                            label: 'Active'
                        }, {
                            value: '0',
                            label: 'Inactive'
                        }],
                    },
                    {
                        column_number: 5,
                        data: [{
                            value: '1',
                            label: 'Tak'
                        }, {
                            value: '0',
                            label: 'Nie'
                        }],
                    },
                    {
                        column_number: 6,
                        data: [{
                            value: '1',
                            label: 'Tak'
                        }, {
                            value: '0',
                            label: 'Nie'
                        }],
                    },
                    {
                        column_number: 7,
                        data: [{
                            value: '1',
                            label: 'Tak'
                        }, {
                            value: '0',
                            label: 'Nie'
                        }],
                    },
                    {
                        column_number: 8,
                        data: [{
                            value: '1',
                            label: 'Tak'
                        }, {
                            value: '0',
                            label: 'Nie'
                        }],
                    }
        
        ]);
                
        customDataTableFunctions();
    });
</script>
<div class="row">
    <div class="col-md-12">
        <h3 class="page-title">
        List rally
        </h3>
        <ul class="page-breadcrumb breadcrumb">
                <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">
                        Home </a>
                        <i class="fa fa-angle-right"></i>
                </li>
                <li>
                        <a href="#">List rally</a>
                </li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                        <i class="fa fa-shopping-cart"></i>Rally list
                </div>
                <div class="actions">
                    <a href="/admin/rally/add-league-rally" class="btn blue yellow-stripe">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-480">
                        Add league rally </span>
                    </a>
                    <a href="/admin/rally/add-rally" class="btn default yellow-stripe">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-480">
                        Add rally </span>
                    </a>
                    
                    <a href="/admin/rally/add-big-rally" class="btn red yellow-stripe">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-480">
                        Add big rally </span>
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-container">
                    <table class="table table-striped table-bordered table-hover" id="datatable_ajax">
                        <thead>
                            <tr role="row" class="heading">
                                <th><input type="checkbox" class="group-checkable"></th>
                                <th>Id</th>
                                <th>Nazwa</th>
                                <th>Data rajdu</th>
                                <th>Aktywny</th>
                                <th>Duże nagrody</th>
                                <th>Rajd ligowy</th>
                                <th>Towarzyski</th>
                                <th>Skończony</th>
                                <th>Options</th>
                            </tr>
                            <tr role="row" class="filter">
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th>
                                    <div class="margin-bottom-5">
                                            <button class="btn btn-sm yellow filter-submit margin-bottom"><i class="fa fa-search"></i> Search</button>
                                    </div>
                                    <button class="btn btn-sm red filter-cancel"><i class="fa fa-times"></i> Reset</button>
                                </th>
                            </tr> 
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>