<script>
    $(document).ready(function(){
        var grid = new Datatable();
            grid.init({
                src: $("#datatable_ajax"),
                dataTable: {   
                "aoColumns": [
                        { sWidth: '5%' },
                        { sWidth: '15%' },
                        { sWidth: '20%' },
                        { sWidth: '20%' },
                        { sWidth: '20%' },
                        { "bSortable": false, sWidth: '15%' }
                    ],
                    "aLengthMenu": [
                        [20, 50, 100, 150, -1],
                        [20, 50, 100, 150, "All"] // change per page values here
                    ],
                    "iDisplayLength": 20, // default record count per page
                    "bServerSide": true, // server side processing
                    "sAjaxSource": "/admin/rally/show-rally-stages-data/<?php echo $rally['id']; ?>", // ajax source
                    "aaSorting": [[ 1, "desc" ]] // set first column as a default sort by asc
                }
            });
               grid.getDataTable().yadcf([
                    {
                      column_number: 1,
                      filter_type: "text"
                    },
                    {
                      column_number: 2,
                      filter_type: "text"
                    },
                    {
                      column_number: 3,
                      filter_type: "text"
                    },
                    {
                      column_number: 4,
                      filter_type: "text"
                    }
        
        ]);
                
        customDataTableFunctions();
    });
</script>
<div class="row">
    <div class="col-md-12">
        <h3 class="page-title">
        List user
        </h3>
        <ul class="page-breadcrumb breadcrumb">
                <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">
                        Home </a>
                        <i class="fa fa-angle-right"></i>
                </li>
                <li>
                        <a href="/admin/rally/list-rally">
                        List rally </a>
                        <i class="fa fa-angle-right"></i>
                </li>
                <li>
                        <a href="#">List user</a>
                </li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <!-- Begin: life time stats -->
        <div class="portlet blue box">
                <div class="portlet-title">
                        <div class="caption">
                                <i class="fa fa-shopping-cart"></i>Stage list <?php echo $rally['name']; ?>
                        </div>
                </div>
                <div class="portlet-body">
                        <div class="table-container">
                                <div class="table-actions-wrapper">
                                    <a href="/admin/rally/add-stage/<?php echo $rally['id']; ?>" class="btn  yellow">
                                        <i class="fa fa-plus"></i>
                                        <span class="hidden-480">
                                            Add stage 
                                        </span>
                                    </a>
                                </div>
                                <table class="table table-striped table-bordered table-hover" id="datatable_ajax">
                                <thead>
                                <tr role="row" class="heading">
                                        <th>
                                                <input type="checkbox" class="group-checkable">
                                        </th>
                                        <th>
                                                 Record&nbsp;#
                                        </th>
                                        <th>
                                                 Name
                                        </th>
                                        <th>
                                                 Length
                                        </th>
                                        <th>
                                                 Min time
                                        </th>
                                        <th>
                                                 Options
                                        </th>
                                </tr>
                                <tr role="row" class="filter">
                                        <th>
                                        </th>
                                        <th>
                                        </th>
                                        <th>
                                        </th>
                                        <th>
                                        </th>
                                        <th>

                                        </th>
                                        <th>
                                            <div class="margin-bottom-5">
                                                    <button class="btn btn-sm yellow filter-submit margin-bottom"><i class="fa fa-search"></i> Search</button>
                                            </div>
                                            <button class="btn btn-sm red filter-cancel"><i class="fa fa-times"></i> Reset</button>

                                        </th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                                </table>
                        </div>
                </div>
        </div>
    </div>
</div>