<script>
    $(document).ready(function(){
        $(".form_advance_datetime").datetimepicker({
            format: "dd-mm-yyyy",
            autoclose: true,
            startDate: '<?php echo date('Y-m-d',strtotime('+1 day')); ?>',
            minView: 2,
            pickerPosition: "bottom-right",
            minuteStep: 15,
            todayHighlight: true
        });
        
        $('#date').on('change',function(){
            var date = $('#date').val();
           $.ajax({
                url: '/rally/check-availability',
                dataType: 'json',
                data: {
                    date: date
                },
//                error: function() {
//                   $('#info').html('<p>An error has occurred</p>');
//                },
//                dataType: 'jsonp',
                success: function(data) {
                    if(data.result.success=='true'){
                        $('#driverWrapper').html(data.result.driver_id);
                        $('#pilotWrapper').html(data.result.pilot_id);
                        $('#carWrapper').html(data.result.car_id);
                        $('#myMessage').html(data.result.message);
                    }
                    
                    
//                   var $title = $('<h1>').text(data.talks[0].talk_title);
//                   var $description = $('<p>').text(data.talks[0].talk_description);
//                   $('#info')
//                      .append($title)
//                      .append($description);
                },
                type: 'POST'
            });
        });
    });
</script>
  <script src="/assets/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script>
<link rel="stylesheet" href="/assets/global/plugins/bootstrap-datetimepicker/css/datetimepicker.css">
<style>
    table img{
        max-width:100px;
    }
    table img.sponsor{
        float:left;
        width:60px;
    }
    </style>
<a href="/rally/list-friendly-rally">Powrót do listy rajdów</a>
<div>
    <form method="POST">
    <label for="name">Name</label>
    <?php echo $form->getElement('name')->renderElement(); ?>
    <label for="description">Description</label>
    <?php echo $form->getElement('description')->renderElement(); ?>
    <label for="invite_only">Invite only</label>
    <?php echo $form->getElement('invite_only')->renderElement(); ?>
    <label for="date">Rally date</label>
    <?php echo $form->getElement('date')->renderElement(); ?>
    
    <hr />
    <div id="myMessage" class='error'>
        
    </div>
    <span>Please note: to create a friendly rally you need to have free driver,pilot and car. One crew is allowed to drive only one friendly rally/day. If you don't have free crew on that date, please choose another date of rally.</span>
    <div>My rally settings</div>
    
    <div id='crewAddWrapper'>
        <label for="driver_id">Driver</label>
        <span id="driverWrapper">
            <?php echo $joinForm->getElement('driver_id')->renderElement(); ?>
        </span>
        <label for="pilot_id">Pilot</label>
        <span id="pilotWrapper">
            <?php echo $joinForm->getElement('pilot_id')->renderElement(); ?>
        </span>
        <label for="car_id">Car</label>
        <span id="carWrapper">
            <?php echo $joinForm->getElement('car_id')->renderElement(); ?>
        </span>
        <label for="risk">Risk</label>
        <?php echo $joinForm->getElement('risk')->renderElement(); ?>

        <?php echo $form->getElement('submit')->renderElement(); ?>
    </div>
    </form>
</div>