<script>
    $(document).ready(function(){
        $(".form_advance_datetime").datetimepicker({
            format: "dd-mm-yyyy",
            autoclose: true,
            startDate: '<?php echo date('Y-m-d',strtotime('+1 day')); ?>',
            minView: 2,
            pickerPosition: "bottom-right",
            minuteStep: 15,
            todayHighlight: true
        });
        
        $('#date').on('change',function(){
            var date = $('#date').val();
           $.ajax({
                url: '/rally/check-availability',
                dataType: 'json',
                data: {
                    date: date
                },
//                error: function() {
//                   $('#info').html('<p>An error has occurred</p>');
//                },
//                dataType: 'jsonp',
                success: function(data) {
                    if(data.result.success=='true'){
                        $('#driverWrapper').html(data.result.driver_id);
                        $('#pilotWrapper').html(data.result.pilot_id);
                        $('#carWrapper').html(data.result.car_id);
                        $('#myMessage').html(data.result.message);
                    }
                    
                    
//                   var $title = $('<h1>').text(data.talks[0].talk_title);
//                   var $description = $('<p>').text(data.talks[0].talk_description);
//                   $('#info')
//                      .append($title)
//                      .append($description);
                },
                type: 'POST'
            });
        });
    });
</script>
  <script src="/assets/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script>
<link rel="stylesheet" href="/assets/global/plugins/bootstrap-datetimepicker/css/datetimepicker.css">
<style>
    table img{
        max-width:100px;
    }
    table img.sponsor{
        float:left;
        width:60px;
    }
    </style>
    
<div class="mainUserBox createFriendlyBox">
    <h4 class="boxHeader">Create friendly rally</h4>
<?php if(isset($message)){
        echo $this->showError($message);
    } ?>
    <div>
        <!--Cost of this = 10 CC <br />-->
        <form  method="POST">
            <div class='form-group'>
                <label class='control-label col-md-2' for="name">Name</label>
                <div class='col-md-9'>
                    <?php echo $form->getElement('name')->renderElement(); ?>
                </div>
            </div>
            <div class='form-group'>
                <label class='control-label col-md-2' for="description">Description</label>
                <div class='col-md-9'>
                    <?php echo $form->getElement('description')->renderElement(); ?>
                </div>
            </div>
            <div class='form-group'>
                <?php echo $form->getElement('invite_only')->renderElement(); ?>
            </div>
            <div class='form-group'>
                <label class='control-label col-md-2' for="date">Rally date</label>
                <div class='col-md-9'>
                    <?php echo $form->getElement('date')->renderElement(); ?>
                </div>
            </div>
        <hr />
        <div id="myMessage" class='error'>

        </div>
        <span class='friendlyNote'><strong>Please note:</strong> to create a friendly rally you need to have free driver,pilot and car. One crew is allowed to drive only one friendly rally/day. If you don't have free crew on that date, please choose another date of rally.</span>
        <div id='crewAddWrapper'>
            <label for="driver_id">Driver</label>
            <span id="driverWrapper">
                <?php echo $joinForm->getElement('driver_id')->renderElement(); ?>
            </span>
            <label for="pilot_id">Pilot</label>
            <span id="pilotWrapper">
                <?php echo $joinForm->getElement('pilot_id')->renderElement(); ?>
            </span>
            <label for="car_id">Car</label>
            <span id="carWrapper">
                <?php echo $joinForm->getElement('car_id')->renderElement(); ?>
            </span>
            <label for="risk">Risk</label>
            <?php echo $joinForm->getElement('risk')->renderElement(); ?>
            
            <div class='goldCoinBox'>
                <h4>Create friendly rally</h4>
                <?php if(!$authenticatedUser['gold_member']): ?>
                    <div class="balance">
                        Balance: <?= (int)$authenticatedUser['premium']; ?><img class="coin" src="/images/layout/coin.png" /> <br />
                    </div>
                     Cost:  10<img class="coin" src="/images/layout/coin.png" />
               <?php else: ?>
                    You are a <img src="/images/layout/gc_small.png" /> member. You are allowed to create 2 friendly rallies every 30 days.
                    <?php 
                    if($recentUserFriendlies['cnt']>=2){
                       $oldestFriendly = new DateTime($recentUserFriendlies['created_at']);
                       $oldestFriendly->add(new DateInterval('P30D'));
                       echo "<br/> You have to wait until <strong>".$oldestFriendly->format('d/m/Y H:i')."</strong> to create another free friendly rally."; 
                    
                       ?>
                    <br />
                    <div class="balanceWrapper">
                        <div class="balance">
                            Balance: <?= (int)$authenticatedUser['premium']; ?><img class="coin" src="/images/layout/coin.png" /> <br />
                        </div>
                         Cost:  10<img class="coin" src="/images/layout/coin.png" />
                         <div class="clearfix"></div>
                    </div>
                    <?php
                    }
                    ;?>
                    
                <?php endif; ?>
            </div>
            <?php echo $form->getElement('submit')->renderElement(); ?>
        </div>
        </form>
    </div>
</div>