<h3>Lista rajdów</h3>
 <a href="/rally/create-friendly-rally/">Stwórz rajd towarzyski</a>
           
<table>
    <tr>
	<th>Nazwa rajdu</th>
	<th>Data</th>
	<th>Dostępny do zapisu</th>
    </tr>
<?php foreach($rallies as $rally): ?>
    <tr>
	<td>
            <?php if((is_array($futureTeamRallies)&&in_array($rally['id'],$futureTeamRallies))||$rally['id']==$futureTeamRallies){
                echo "In rally "; 
            } ?>
	    <a href="/rally/show-friendly-rally/slug/<?php echo $rally['slug']; ?>"><?php echo $rally['name'];?></a>
            <?php if($rally['big_awards']==1): ?>
                <img src="/images/b_letter.gif" alt="Big awards" />
            <?php endif; ?>
	</td>
	<td>
	    <?php echo TK_Text::timeFormat($rally['date'],'d-m-Y H:i'); ?>
	</td>
	<td>
	    <?php 
            if($rally['Friendly']['invite_only']){
                echo "nie";
            }
            else{
                echo "tak";
            }
            ?>
	</td>
    </tr>
<?php endforeach; ?>
</table>