<div class="mainUserBox rallyList">
    <h4 class="boxHeader"><?= $this->translate('Friendly rallies'); ?></h4>
    <a class='createFriendly btn btn-primary' href="/rally/create-friendly-rally/"><?= $this->translate('Create friendly rally'); ?></a>
           
<table>
<?php foreach($rallies as $rally): ?>
    <tr>
	<td>
	    <a href="/rally/show-friendly-rally/slug/<?php echo $rally['slug']; ?>"><?php echo $rally['name'];?></a>
            <?php if($rally['big_awards']==1): ?>
                <img src="/images/b_letter_small.gif" title="<?= $this->translate('Big awards');?>" alt="<?= $this->translate('Big awards');?>" />
            <?php endif; ?>
	</td>
	<td>
	    <?php echo TK_Text::timeFormat($rally['date'],'d-m-Y H:i'); ?>
	</td>
	<td>
	    <?php 
            if($rally['Friendly']['invite_only']){
                echo "<span class='label label-danger'>".$this->translate('Private')."</span>";
            }
            else{
                echo "<span class='label label-success'>".$this->translate('Public')."</span>";
            }
            ?>
	</td>
        <td>
            <?php if((is_array($futureTeamRallies)&&in_array($rally['id'],$futureTeamRallies))||$rally['id']==$futureTeamRallies){
                echo "<span class='label label-info'>".$this->translate('Joined')."</span>"; 
            } ?>
                <?php if((is_array($myInvitations)&&in_array($rally['id'],$myInvitations))){
                echo "<span class='label label-warning'>".$this->translate('Invited')."</span>"; 
            } ?>
        </td>
    </tr>
<?php endforeach; ?>
</table>
</div>