<h3>Lista rajdów</h3>
<table>
    <tr>
	<th>Nazwa rajdu</th>
	<th>Data</th>
    </tr>
<?php foreach($rallies as $rally): ?>
    <tr>
	<td>
            <?php if((is_array($futureTeamRallies)&&in_array($rally['id'],$futureTeamRallies))||$rally['id']==$futureTeamRallies){
                echo "In rally "; 
            } ?>
	    <a href="/rally/show-rally/name/<?php echo $rally['slug']; ?>"><?php echo $rally['name'];?></a>
            <?php if($rally['big_awards']==1): ?>
                <img src="/images/b_letter.gif" alt="Big awards" />
            <?php endif; ?>
	</td>
	<td>
	    <?php echo TK_Text::timeFormat($rally['date'],'d-m-Y H:i'); ?>
	</td>
    </tr>
<?php endforeach; ?>
</table>