<div class="mainUserBox rallyList">
    <h4 class="boxHeader">Friendly rallies</h4>
    <a class='createFriendly btn btn-primary' href="/rally/create-friendly-rally/">Create friendly rally</a>
           
<table>
<?php foreach($rallies as $rally): ?>
    <tr>
	<td>
	    <a href="/rally/show-friendly-rally/slug/<?php echo $rally['slug']; ?>"><?php echo $rally['name'];?></a>
            <?php if($rally['big_awards']==1): ?>
                <img src="/images/b_letter.gif" alt="Big awards" />
            <?php endif; ?>
	</td>
	<td>
	    <?php echo TK_Text::timeFormat($rally['date'],'d-m-Y H:i'); ?>
	</td>
	<td>
	    <?php 
            if($rally['Friendly']['invite_only']){
                echo "<span class='label label-danger'>Private</span>";
            }
            else{
                echo "<span class='label label-success'>Public</span>";
            }
            ?>
	</td>
        <td>
            <span class='label label-info'>Joined</span>
        </td>
    </tr>
<?php endforeach; ?>
</table>
</div>