<style>
    .rallyList table{
        margin-left:20px;
    }
    .rallyList td:not(:first-of-type){
        padding:5px 20px;
    }
    .rallyList td.big{
        padding-right:10px;
    }
    .rallyList td.rallyName{
        padding-left:0px;
    }
</style>
<div class="mainUserBox rallyList">
    <h4 class="boxHeader"><?= $this->translate('My rallies'); ?></h4>
    <table>
        <?php foreach($rallies as $rally): ?>
            <tr>
                <td>
                    <?php echo TK_Text::timeFormat($rally['date'],'d-m-Y H:i'); ?>
                </td>
                <td>
                    <a href="/rally/show-rally/slug/<?php echo $rally['slug']; ?>"><?php echo $rally['name'];?></a>
                    <?php if($rally['big_awards']==1): ?>
                        <img src="/images/b_letter.gif" alt="Big awards" />
                    <?php endif; ?>
                </td>
                
                <td>
                    <?= count($rally['Crews'])." ".$this->translate("crews"); ?>
                </td>
                <td>
                    <?php if((is_array($futureTeamRallies)&&in_array($rally['id'],$futureTeamRallies))||$rally['id']==$futureTeamRallies){
                        echo "<span class='label label-info'>".$this->translate('Joined')."</span>"; 
                    } ?>
                        <?php if((is_array($myInvitations)&&in_array($rally['id'],$myInvitations))){
                        echo "<span class='label label-warning'>".$this->translate('Invited')."</span>"; 
                    } ?>
                </td>
                <td>
                    <?php if($rally['date']<=date('Y-m-d H:i:s')){ ?>
                        <a href="/rally/rally-result/id/<?= $rally['id']; ?>" class="label label-primary"><?= $this->translate('See results'); ?></a>
                    <?php } ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>