<style>
    .rallyList table{
        margin-left:20px;
    }
    .rallyList td:not(:first-of-type){
        padding:5px 20px;
    }
    .rallyList td.big{
        padding-right:10px;
    }
    .rallyList td.rallyName{
        padding-left:0px;
    }
</style>
<div class="mainUserBox rallyList">
    <h4 class="boxHeader">Lista rajdów</h4>
    <table>
        <?php foreach($rallies as $rally): ?>
            <tr>
                <td>
                    <?php echo TK_Text::timeFormat($rally['date'],'d/m/Y H:i'); ?>
                </td>
                <td class="big">
                    
                    <?php if($rally['big_awards']==1): ?>
                        <img src="/images/b_letter_small.gif" alt="Big awards" />
                    <?php endif; ?>
                </td>
                <td class="rallyName">
                    <a href="/rally/show-rally/slug/<?php echo $rally['slug']; ?>"><?php echo $rally['name'];?></a>
                    
                </td>
                <td>
                    <?= count($rally['Crews'])." crews"; ?>
                </td>
                <td>
                    <?php if($rally['date']<=date('Y-m-d H:i:s')){ ?>
                        <a href="/rally/rally-result/id/<?= $rally['id']; ?>" class="label label-primary">See results</a>
                    <?php } ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>