
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <?php if(isset($message)){ ?>
     <div class="alert alert-danger alert-dismissable">
         <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php 
            echo $message; 
            ?>
     </div>
  <?php } ?>
<h2><?php echo $friendly['Rally']['name']; ?></h2>
<?php echo $friendly['description']; ?>
<hr />
Zaproszeni: <br />
<?php 
if(isset($invitedUsers)){
    foreach($invitedUsers as $invitedUser): 
        echo $invitedUser['User']['username']."<br />";
    endforeach; 
}
    
    ?>
<h3>Uczestnicy</h3>
<?php foreach($friendly['Participants'] as $participant): 
        echo $participant['User']['username'];
    
    endforeach; ?>
<?php if(isset($form)){ ?>
<h2>Invite your friend</h2>
<form method="POST">
    <label for="name">Friend's name</label>
    <?php echo $form->getElement('name')->renderElement(); ?>
    <?php echo $form->getElement('submit')->renderElement(); ?>
</form>

<?php } ?>

<?php if(isset($joinForm)){ ?>
<h2>Join friendly rally</h2>
<span>You have been invited to this rally.</span>
<form method="POST">
    <label for="driver_id">Driver</label>
    <?php echo $joinForm->getElement('driver_id')->renderElement(); ?>
    <label for="pilot_id">Pilot</label>
    <?php echo $joinForm->getElement('pilot_id')->renderElement(); ?>
    <label for="car_id">Car</label>
    <?php echo $joinForm->getElement('car_id')->renderElement(); ?>
    <label for="risk">Risk</label>
    <?php echo $joinForm->getElement('risk')->renderElement(); ?>
    <?php echo $joinForm->getElement('submit')->renderElement(); ?>
</form>

<?php } ?>

 <script>
  $(function() {
    $( "#name" ).autocomplete({
      source: function( request, response ) {
        $.ajax({
          url: "/user/find-user",
          dataType: "json",
          type: "get",
          data: {
            q: request.term
          },
          success: function( data ) {
            response( data );
          }
        });
      },
      minLength: 3
    });
  });
  </script>
