<script>
    $(document).ready(function(){
       $('.rallyButtons a').click(function(){
          $('.rallyButtons a.active').removeClass('active');
          $(this).addClass('active');
          $('.mainUserBox.active').hide();
          $('.mainUserBox.active').removeClass('active');
          $('#'+$(this).attr('rel')).show();
          $('#'+$(this).attr('rel')).addClass('active');
       });
    });

</script>
<?php $rally = $friendly['Rally'];
$startDate2 = clone $startDate;
?>
<?php $surfaces = $rally['Surfaces']; ?>
<div class="mainUserBox showRallyWrapper">
    <h4 class="boxHeader"><?php echo $friendly['Rally']['name']; ?></h4> 
   
    <div class="showRallyBox <?php if(!$rally['finished']) echo "active"?> mainUserBox" id="details">
         <?php
            if(isset($message)){
                if(!$message['status'])
                    $this->showError($message['message']);
                else
                    $this->showSuccess($message['message']);
            }

            if(isset($_GET['msg'])){
                if($_GET['msg']=="user invited")
                    $this->showSuccess('User was succesfully invited.');
                elseif($_GET['msg']=="joined")
                    $this->showSuccess('You have joined this rally.');
                elseif($_GET['msg']=='signup finish'){
                    $this->showError($this->translate('Sorry. Sign ups for this rally are closed.'));
                }
            }
        ?>
        <div class='rallyInfo mb20'>
            <?= nl2br($friendly['description'])."<br /><br />"; ?>
        
            <table>
                <tr>
                    <td>
                        <?php if(!$rally['big_awards']){ 
                            echo $this->translate('Prize pool').": ".number_format($prizePool)."$"; 
                            } ?>
                    </td>
                    <td>
                        <?= $this->translate('Surface');?> : 
                    </td>
                </tr>
                <tr>
                    <td>
                         <?= $this->translate('Signed crews'); ?> : <?php echo $crewCounter; ?>
                    </td>
                    <td>
                         <?php 
                            if(isset($surfaces[0])){
                                echo $surfaces[0]['surface']." ".round($surfaces[0]['percentage'])."%";
                            }
                         ?>
                    </td>
                </tr>
                <tr>
                    <td>
                         <?= $this->translate('Race start');?> : <?php echo $startDate->format('d/m/Y H:i'); ?>
                    </td>
                    <td>
                         <?php 
                            if(isset($surfaces[1])){
                                echo $surfaces[1]['surface']." ".round($surfaces[1]['percentage'])."%";
                            }
                         ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?= $this->translate('Sign up finish');?> : <?php echo $signUpFinish->format('d/m/Y H:i'); ?>
                    </td>
                    <td>
                         <?php 
                            if(isset($surfaces[2])){
                                echo $surfaces[2]['surface']." ".round($surfaces[2]['percentage'])."%";
                            }
                         ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?= $this->translate('Rally type'); ?> :  <?php echo $friendly['invite_only']?"<span class='label label-danger'>Private</span>":"<span class='label label-success'>Public</span>"; ?>
                    </td>
                    <td>
                         <?= $this->translate('Created by'); ?> : <?php echo $friendly['User']['username']; ?><br />
                    </td>
                </tr>
                
            </table>
        </div>
        
        <?php if(isset($isParticipant)&&$isParticipant): ?>
        
            <span class="label label-success bigLabel"><?= $this->translate('You already participate in this rally.'); ?></span>
        <?php endif; ?>
        <br />
        <?php if(isset($form)){ ?>
        
            <div class='goldCoinBox inviteFriendFriendly'>
                <strong><?= $this->translate('Invite your friend'); ?></strong>
                <form method="POST">
                    <br />
                    <div class='formElemWrapper'>
                        <?php echo $form->getElement('name')->renderElement(); ?>
                    </div>
                    <br />
                    <?php echo $form->getElement('submit')->renderElement(); ?>
                </form>
            </div>

<?php } ?>

<?php if(isset($joinForm)){ 
    if($friendly['User']['id']!=$authenticatedUser['id']){ 
    ?>
        <span class="label label-warning bigLabel"><?= $this->translate('You have been invited to this rally.'); ?></span>
        <br /><br />
    <?php } ?>
        <div class="clearfix mb20"></div>
        <form method="POST">
            <div class="sign-up-rally">
                <h3>Sign up</h3>
                    <div class='formElemWrapper'>
                        <label for='driver_id' class="col-md-3 control-label" type='text'><?= $this->translate('Driver'); ?></label>
                        <?php echo $joinForm->getElement('driver_id')->renderElement(); ?>
                    </div>
                    <div class='formElemWrapper'>
                        <label for='pilot_id' class="col-md-3 control-label"  type='text'><?= $this->translate('Pilot'); ?></label>
                        <?php echo $joinForm->getElement('pilot_id')->renderElement(); ?>
                    </div>     
                    <div class='formElemWrapper'>
                        <label for='car_id' class="col-md-3 control-label"  type='text'><?= $this->translate('Car'); ?></label>
                        <?php echo $joinForm->getElement('car_id')->renderElement(); ?>
                    </div>
                    <div class='formElemWrapper'>
                        <label for='risk' class="col-md-3 control-label"  type='text'><?= $this->translate('Risk'); ?></label>
                        <?php echo $joinForm->getElement('risk')->renderElement(); ?>
                    </div>
            </div>
            <div class='goldCoinBox'>
                <h4><?= $this->translate('Join friendly rally'); ?></h4>
                <?php if(!$authenticatedUser['gold_member']): ?>
                    <div class="balance">
                        Balance: <?= (int)$authenticatedUser['premium']; ?><img class="coin" src="/images/layout/coin.png" /> <br />
                    </div>
                     Cost:  
                     <?php if($authenticatedUser['gold_member']){
                         echo 5;
                     }
                     else{
                         echo 10;
                     }
                     ?>
                     <img class="coin" src="/images/layout/coin.png" />
               <?php else: ?>
                    <?= $this->translate('You are a');?> <img src="/images/layout/gc_small.png" /> <?= $this->translate('member. You are allowed to join 3 friendly rallies every 30 days.');?>
                    <?php 
                    if($recentUserFriendlies['cnt']>=3){
                       $oldestFriendly = new DateTime($recentUserFriendlies['created_at']);
                       $oldestFriendly->add(new DateInterval('P30D'));
                       echo "<br/>".$this->translate('You have to wait until')."<strong>".$oldestFriendly->format('d/m/Y H:i')."</strong> ".$this->translate('to join another free friendly rally.'); 

                       ?>
                    <br />
                    <div class="balanceWrapper">
                        <div class="balance">
                            <?= $this->translate('Balance');?>: <?= (int)$authenticatedUser['premium']; ?><img class="coin" src="/images/layout/coin.png" /> <br />
                        </div>
                         <?= $this->translate('Cost'); ?>:  
                         <?php if($authenticatedUser['gold_member']){
                            echo 5;
                        }
                        else{
                            echo 10;
                        }
                        ?>
                         <img class="coin" src="/images/layout/coin.png" />
                         <div class="clearfix"></div>
                    </div>
                    <?php
                    }
                    ;?>

                <?php endif; ?>
            </div>
            <div class="sign-up-rally">

                <div class='formSubmitWrapper'>
                    <?php echo $joinForm->getElement('submit')->renderElement(); ?>
                </div>

            </div>
        </form>
        

<?php } ?>
    </div>
    <div class="showRallyBox mainUserBox" id="stages">
        <h3 class="h4">Stage list</h3>
        <div class='stageListInfo'>
            <div class='col-md-6'>
                Name
            </div>
            <div class='col-md-3'>
                  Length
            </div>
            <div class='col-md-3'>
                Time
            </div>
        </div>
        <div class='clearfix'></div>
        <div class="stageList" id="accordion" role="tablist" aria-multiselectable="true">
            
            <?php foreach($rallyStagesResults as $key => $stage):
                if(count($stage['Results'])>0){
                    $hasResults = true;
                }
                else{
                    $hasResults = false;
                }
                ?>
            <div class='stageRow <?php echo $hasResults?'':'inactive'; ?>'>
               <div class="stageListInfo">  
                            <div class='col-md-1'>
                                <?= "SS".($key+1) ?>
                            </div>
                            <div class='col-md-5'>
                                <?= $stage['name']; ?>
                            </div>
                            <div class='col-md-3'>
                                  <?= $stage['length']; ?> km 
                            </div>
                            <div class='col-md-3'>
                                <i class="fa fa-clock-o"></i> 
                                  <?php 
                                  if($key!=0){
                                      $startDate2->add(new DateInterval('PT15M'));
                                  }
                                  echo $startDate2->format("H:i"); 
                                  ?>
                            </div>
                            <div class='clearfix'></div>
                        </div>
            </div>
            <?php endforeach; ?>
          </div>
        
        
        
        
        
    </div>
    <?php if(!$rally['finished']){ ?>
        <div class="showRallyBox mainUserBox" id="invited">
        <h3 class="h4">Invited crews</h3>
            <?php

            if(!$friendly['invite_only']){
                echo $this->translate("This rally is open for all");
            }
            else{
                if(count($friendly['Invitations'] )==0)
                    echo $this->translate("No teams invited yet");
                ?>
                <table class="rallyCrews">
                    <?php foreach($friendly['Invitations'] as $key => $invited): ?>
                            <tr>
                                <td>
                                    <?= ($key+1)."."; ?>
                                </td>
                                <td>
                                    <?php echo $invited['User']['Team']['name']; ?>
                                </td>
                                <td>
                                    <?php echo $invited['User']['username']; ?>
                                </td>
                            </tr>
                    <?php endforeach; ?>

                    </table>
            <?php } ?>
        </div>
    <?php } ?>
    <div class="showRallyBox mainUserBox" id="crews">
        <h3 class="h4">Signed crews</h3>
        <table class="rallyCrews">
            <thead>
                <tr>
                    <td></td>
                    <td><?= $this->translate('Crew');?></td>
                    <td><?= $this->translate('Car');?></td>
                    <td><?= $this->translate('Team');?></td>
                </tr>
            </thead>
            <tbody>
                <?php foreach($rally['Crews'] as $key => $crew): ?>
                        <tr>
                            <td>
                                <?= ($key+1)."."; ?>
                            </td>
                            <td>
                                <?php echo $crew['Driver']['last_name']." ".$crew['Driver']['first_name']; ?> - 
                                <?php echo $crew['Pilot']['last_name']." ".$crew['Pilot']['first_name']; ?>
                            </td>
                            <td>
                                <?php echo $crew['Car']['name']; ?>
                            </td>
                            <td>
                                <?php echo $crew['Team']['name']; ?>
                            </td>
                        </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="showRallyBox mainUserBox" id="prizes">
        <h3 class="h4"><?= $this->translate('Prizes'); ?></h3>
        <table class="prizeTable">
            <?php foreach($rallyPrizes as $position => $rallyPrize): ?>
            <tr>
                <td>
                    <?= $position; ?>.
                </td>
                <td>
                    <?= number_format($rallyPrize); ?> $
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
    <div class="showRallyBox rallyResultWrapper mainUserBox <?php if($rally['finished']) echo "active"?>" id="result">
        
        
        <h3 class="h4">Overall results</h3>
        <table class="mb20">
            <?php foreach($rallyResults as $result): ?>
                <tr>
                    <td>
                        <?php if($result['out_of_race']==0){
                            echo $result['position'];
                        }
                        ?>
                    </td>
                    <td>
                        <?php echo $result['Crew']['Team']['name']; ?>
                    </td>
                    <td>
                        <?php echo $result['Crew']['Driver']['last_name']." ".$result['Crew']['Driver']['first_name']; ?> - 
                        <?php echo $result['Crew']['Pilot']['last_name']." ".$result['Crew']['Pilot']['first_name']; ?>
                    </td>
                    <td>
                         <?php if($result['out_of_race']==0){
                            echo $result['total_time'];
                        }
                        else{
                            echo $this->translate("Accident on stage no")." ".$result['stage_out_number'];
                        }
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
        <h3 class="h4">Stage results</h3>
        <div class='stageListInfo'>
            <div class='col-md-6'>
                Name
            </div>
            <div class='col-md-3'>
                  Length
            </div>
            <div class='col-md-3'>
                Time
            </div>
        </div>
        <div class='clearfix'></div>
        <div class="stageList" id="accordion" role="tablist" aria-multiselectable="true">
            
            <?php foreach($rallyStagesResults as $key => $stage):
                if(count($stage['Results'])>0){
                    $hasResults = true;
                }
                else{
                    $hasResults = false;
                }
                ?>
            <div class='stageRow <?php echo $hasResults?'':'inactive'; ?>'>
                <div role="tab" id="stage<?= $stage['id']; ?>">
                    <a role="button" class='showAccordion collapsed <?php echo $hasResults?'':'inactive'; ?>' data-toggle="collapse" data-parent="#accordion" href="#stage<?= $stage['id']; ?>info" aria-expanded="true" aria-controls="stage<?= $stage['id']; ?>info">
                        <div class="stageListInfo">  
                            <div class='col-md-1'>
                                <?= "SS".($key+1) ?>
                            </div>
                            <div class='col-md-5'>
                                <?= $stage['name']; ?>
                            </div>
                            <div class='col-md-3'>
                                  <?= $stage['length']; ?> km 
                            </div>
                            <div class='col-md-3'>
                                <i class="fa fa-clock-o"></i> 
                                  <?php 
                                  if($key!=0){
                                      $startDate->add(new DateInterval('PT15M'));
                                  }
                                  echo $startDate->format("H:i"); 
                                  ?>
                            </div>
                            <div class='clearfix'></div>
                        </div>
                    </a>
                </div>
                <div id="stage<?= $stage['id']; ?>info" class="panel-collapse collapse" role="tabpanel" aria-labelledby="stage<?= $stage['id']; ?>info">
                  <div class="panel-body">
                      <table class="rallyStages">
                          <?php foreach($stage['Results'] as $key => $result): ?>
                                  <tr>
                                      <td>
                                          <?= ($key+1)."."; ?>
                                      </td>
                                      <td>
                                          <?php echo $result['Crew']['Team']['name']; ?>
                                      </td>
                                      <td>
                                          <?php echo $result['Crew']['Driver']['last_name']." ".$result['Crew']['Driver']['first_name']; ?> - 
                                          <?php echo $result['Crew']['Pilot']['last_name']." ".$result['Crew']['Pilot']['first_name']; ?>
                                      </td>
                                      <td>
                                           <?php 
                                           if($result['out_of_race']==0){
                                              echo $result['base_time'];
                                              if($result['Accident']){
                                                  echo '<br /><br /><i class="fa fa-exclamation-circle"></i> '.$result['Accident']['name'];
                                              }
                                          }
                                          else{
                                              echo "Out of race - ".$result['Accident']['name'];
                                          }
                                          ?>
                                      </td>
                                  </tr>
                          <?php endforeach; ?>
                      </table>
                  </div>
                </div>
            </div>
            <?php endforeach; ?>
          </div>
        
    </div>
    <div class="rallyButtons">
        <ul>
            
            <?php if($rally['finished']): ?>
                <li>
                    <a href="#" class="active" rel="result"><?= $this->translate('Results'); ?></a>
                </li>
            <?php endif ; ?>
            <li>
                <a class="<?php if(!$rally['finished']) echo "active"?>" rel="details" href="#"><?= $this->translate('Details'); ?></a>
            </li>
            <li>
                <a href="#" rel="stages"><?= $this->translate('Stages'); ?></a>
            </li>
            <?php if(!$rally['finished']){ ?>
                <li>
                    <a href="#" rel="invited"><?= $this->translate('Invited crews'); ?></a>
                </li>
            <?php } ?>
            <li>
                <a href="#" rel="crews"><?= $this->translate('Signed crews'); ?></a>
            </li>
            <li>
                <a href="#" rel="prizes"><?= $this->translate('Prize pool'); ?></a>
            </li>
        </ul>
    </div>
    
<!--<h3>Uczestnicy</h3>-->
<?php /*/* foreach($friendly['Participants'] as $participant): 
    if(is_null($participant['deleted_at'])){
        echo $participant['User']['username']."<br />";
    }
    endforeach; 
    // if rally has participants
    // and current user is a participant
    if(isset($participant)&&$participant&&$isParticipant){
        ?>
<a href="/rally/remove-friendly-rally-participant/<?php echo $friendly['Rally']['slug'];?>">Wyrejestruj sie</a>
<?php
    }*/
    
    ?>

</div>
 <script>
  $(function() {
    $( "#name" ).autocomplete({
      source: function( request, response ) {
        $.ajax({
          url: "/user/find-user",
          dataType: "json",
          type: "get",
          data: {
            q: request.term
          },
          success: function( data ) {
            response( data );
          }
        });
      },
      minLength: 3
    });
  });
  </script>
