<?php

/**
 * Car_Model_Doctrine_Car
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Car_Model_Doctrine_Car extends Car_Model_Doctrine_BaseCar
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Team_Model_Doctrine_Team as Car1Team', array(
             'local' => 'id',
             'foreign' => 'car1_id'));
	
	$this->hasOne('Team_Model_Doctrine_Team as Car2Team', array(
             'local' => 'id',
             'foreign' => 'car2_id'));
	
	$this->hasMany('Rally_Model_Doctrine_Crew as CarRallies', array(
             'local' => 'id',
             'foreign' => 'car_id'));
	
    }
}