<?php

/**
 * Car_Model_Doctrine_CarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Car_Model_Doctrine_CarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Car_Model_Doctrine_CarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Car_Model_Doctrine_Car');
    }
}