<footer>
    <div class="copyright">Copyright &copy; 2015 by Kardi Mobile</div>
    <div class="footerMenu">
        <ul>
            
            <li>
                <a href="/support">Support</a>
            </li>
            <li>
                <a href="/privacy-policy">Privacy policy</a>
            </li>
            <li>
                <a href="/rules">Rules</a>
            </li>
<!--            <li>
                <a href="#">Contact</a>
            </li>-->
        </ul>
        
        <a href="<?= $this->getSetting('facebookUrl'); ?>" class="fb social_icon_link">
            <i class="fb fa fa-facebook" aria-hidden="true"></i>
        </a>
        <a href="<?= $this->getSetting('twitterUrl'); ?>" class="twitter social_icon_link">
            <i class="fa fa-twitter" aria-hidden="true"></i>
        </a>
    </div>
    <div class="clearfix"></div>
</footer>