<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="robots" content="index,follow" />
<meta name="author" content="kardimobile.pl" />
<title>Rally</title>

<script src="/js/jquery-2.1.3.min.js"></script>
<script src="/js/bootstrap.min.js"></script>


 
 <!--jQuery files--> 
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<link rel="shortcut icon" type="image/ico" href="/images/layout/favicon.ico?v=4" />
<link rel="stylesheet" type="text/css" media="all" href="/css/bootstrap.css">
<link rel="stylesheet" type="text/css" media="all" href="/css/custom.css">
<link rel="stylesheet" type="text/css" media="all" href="/plugins/jquery.cookiebar/jquery.cookiebar.css">
<link href="/plugins/glDatePicker/styles/glDatePicker.darkneon.css" rel="stylesheet" type="text/css">

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
   
<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>

<script type="text/javascript" src="/plugins/jquery.cookiebar/jquery.cookiebar.js"></script>
<script src="/plugins/glDatePicker/glDatePicker.min.js"></script>

<!--<script type="text/javascript" src="/plugins/jMenu/js/jMenu.jquery.js"></script>-->
<!--[if lt IE 9]>
 <script src="/js/html5shiv.js" type="text/javascript"></script>
 <script src="/js/respond.min.js" type="text/javascript"></script>
<![endif]-->

<script>
    $(document).ready(function(){
        $.cookieBar();
    })
    </script>