<script>
    $(document).ready(function(){
                $('.flagSelect li.selected a').click(function(){
                    if($('.flagSelect li:not(.selected)').is(':visible')){
                        $('.flagSelect li:not(.selected)').hide();
                    }
                    else{
                        $('.flagSelect li').show();
                    }
                }) ;
    });
    </script>
<a href='/'>
    <img src="/images/layout/logo-fastrally.png" class="logo" />
</a>
<div class="topToolbar">
    <form method="POST" action="/user/login">
        <div class='topToolbarTop'>
            
            <div class="pull-left">
                <input required type="text" name="login" class="textInput" placeholder='<?= $this->translate('Login'); ?>'/>
                <input required type="password" name="password" class="textInput" placeholder='<?= $this->translate('Password'); ?>' />
                <button type="submit" name="submit" class='logIn btn'><?= $this->translate('LOGIN'); ?></button>
                <?php
                if(isset($loginForm)&&$loginForm->getElement('recaptcha')){
                    echo $loginForm->getElement('recaptcha')->renderElement();
                }
                ?> 
                <div class="clearfix"></div>
            </div>
            <span class='flagSelect'>
                <ul>
                    <?php if(!isset($_COOKIE['lang'])){ ?>
                        <li class="selected">
                            <a href="#">
                                <img src='/images/layout/gb.png' />
                                <i class="fa fa-sort-desc"></i>
                            </a>

                        </li>
                        <li>
                            <a href="/index/set-lang/pl/">
                                <img src='/images/layout/pl.png' />
                            </a>
                        </li>
                    <?php                        
                    }
                    else{
                        if($_COOKIE['lang']=="pl"){ ?>
                        
                        <li class="selected">
                            <a href="#">
                                <img src='/images/layout/pl.png' />
                                <i class="fa fa-sort-desc"></i>
                            </a>
                        </li>
                         <li>
                            <a href="/index/set-lang/gb/">
                                <img src='/images/layout/gb.png' />
                            </a>

                        </li>
                        <?php
                        }
                        elseif($_COOKIE['lang']=="gb"){ ?>
                            <li class="selected">
                                <a href="#">
                                    <img src='/images/layout/gb.png' />
                                    <i class="fa fa-sort-desc"></i>
                                </a>

                            </li>
                            <li>
                                <a href="/index/set-lang/pl/">
                                    <img src='/images/layout/pl.png' />
                                </a>
                            </li>
                        <?php
                        }
                    } 
                    ?>
                </ul>
                
            </span>
        </div>
                <div class="clearfix"></div>
        <div class='topToolbarBottom'>
            <input type="checkbox" name="rememberMe" id='rememberMe'/> 
            <label for='rememberMe'><?= $this->translate('Remember me'); ?></label>
            <a href="/forgot-password"><?= $this->translate("Can't login?"); ?></a>

        </div>
    </form>
<!--                <select>
        <option value='gb'><img src='/images/layout/gb.png' /></option>
        <option value='gb'><img src='/images/layout/pl.png' /></option>
    </select>-->
</div>
        <div class="clearfix"></div>