<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="robots" content="index,follow" />
<meta name="author" content="kardimobile.pl" />
<title>Rally</title>

<script src="/js/jquery-2.1.3.min.js"></script>
<script src="/js/bootstrap.min.js"></script>


 
 <!--jQuery files--> 
<script type="text/javascript" src="/plugins/jMenu/js/jquery-ui.js"></script>
<script type="text/javascript" src="/plugins/jMenu/js/jMenu.jquery.js"></script>

<link rel="stylesheet" type="text/css" media="all" href="/css/bootstrap.css">
<link rel="stylesheet" type="text/css" media="all" href="/css/custom.css">
<link href="/plugins/glDatePicker/styles/glDatePicker.darkneon.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" media="all" href="/css/rally-custom.css">
<link rel="stylesheet" type="text/css" media="all" href="/assets/css/style.css">

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
   
<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>

<script src="/plugins/glDatePicker/glDatePicker.min.js"></script>