<?php 
if(isset($authenticatedUser)&&$authenticatedUser){ ?>
<script type="text/javascript">
  $(document).ready(function(){
    // simple jMenu plugin called
    $("#jMenu").jMenu();
 
    // more complex jMenu plugin called
    $("#jMenu").jMenu({
      ulWidth : 'auto',
      effects : {
        effectSpeedOpen : 300,
        effectTypeClose : 'slide'
      },
      animatedText : false
    });
  });
</script>
<div class="col-md-3">
    Premium : <?php echo (int)$authenticatedUser['premium']; ?><br />
    User : <?php echo $authenticatedUser['username']; ?>
</div>
<div class="clearfix"></div>
<!--<div class="companyAccountMenu">-->
    

    
<!--    <a href="/account/premium">Premium</a>
    <a href="/user/logout">Wyloguj</a>-->
<!--    <a href="/people/create-random-player/type/pilot">Create random pilot</a>
    <a href="/car/create-random-car">Create random car</a>
    <a href="/people/create-random-player/type/driver">Create random driver</a>-->
<!--</div>-->
<ul id="jMenu">
        <li>
            <a href="#">Office</a>
            <ul>
                <li>
                    <a href="/account/my-account">My account</a>
                </li>
                <li>
                    <a href="/account/my-drivers">Moi ludzie</a>
                </li>
                <li>
                    <a href="/account/my-cars">Moje auta</a>
                </li>
                <li>
                    <a href="/account/sponsor">Sponsor</a>
                </li>
                <li>
                    <a href="/account/my-training-report">Raport z treningu</a> 
                </li>
                <li>
                    <a href="/account/my-finances">Moje finanse</a> 
                </li>
            </ul>
        </li>
        <li>
            <a href="#">My rallies</a>
            <ul>
                <li>
                    <a href="/rally/list-rally">Rallies</a>
                </li>
                <li>
                    <a href="/rally/list-friendly-rally">Friendly rallies</a>
                </li>
                <li>
                    <a href="/league/show-table">Moja tabela</a> 
                </li>
                
            </ul>
        </li>
        <li>
            <a href="#">Market</a>
            <ul>
                <li>
                    <a href="/market/my-cars-market">My cars on market</a> 
                </li>
                <li>
                    <a href="/market/show-car-market">Rynek samochodowy</a> 
                </li>
                <li>
                    <a href="/market/car-dealer">Salon samochodowy</a>
                </li>
                <li>
                    <a href="/market/show-market">Rynek transferowy</a> 
                </li>
                <li>
                    <a href="/market/my-players-market">My players on market</a> 
                </li>
                <li>
                    <a href="/market/my-player-offers">My player offers</a> 
                </li>
                <li>
                    <a href="/market/my-car-offers">My car offers</a> 
                </li>
                
            </ul>
        </li>
        <li>
            <a href="#">Community</a>
            <ul>
                <li>
                    <a href="/forum/show-forum">Forum</a> 
                </li>
                <li>
                    <a href="/market/show-car-market">Top world list</a> 
                </li>
                <li>
                    <a href="/market/car-dealer">National ranking</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#">Premium</a>
            <ul>
                <li>
                    <a href="/market/my-cars-market">Moje premium</a> 
                </li>
                <li>
                    <a href="/market/show-car-market">Korzysci z premium</a> 
                </li>
                <li>
                    <a href="/market/car-dealer">Zarob zlote monety</a>
                </li>
                <li>
                    <a href="/market/show-market">Zlote monety</a> 
                </li>
            </ul>
        </li>
        <li>
            <a href="#">Help</a>
            <ul>
                <li>
                    <a href="/market/my-cars-market">Faq</a> 
                </li>
                <li>
                    <a href="/market/show-car-market">Privacy Policy</a> 
                </li>
                <li>
                    <a href="/market/car-dealer">Rules</a>
                </li>
                <li>
                    <a href="/market/show-market">Support</a> 
                </li>
            </ul>
        </li>
        <li>
             <a href="/user/logout">Wyloguj</a>
        </li>
    </ul>
    <?php
}
else{
?>

	    <div class="companyAccountMenu">
		<a href="/user/register">Register</a>
		<a href="/user/login">Login</a>
		<a href="/account/my-account">My account</a>

		<a href="/rally/list-rally">Rallies</a>
<!--		<a href="/people/create-random-player/type/pilot">Create random pilot</a>
		<a href="/car/create-random-car">Create random car</a>
		<a href="/people/create-random-player/type/driver">Create random driver</a>-->
	    </div>

<?php } ?>
<div class="clearfix"></div>