

<?php 
if(isset($authenticatedUser)&&$authenticatedUser){ ?>
<div class="col-md-3">
    Premium : <?php echo (int)$authenticatedUser['premium']; ?><br />
    User : <?php echo $authenticatedUser['username']; ?>
</div>
<div class="clearfix"></div>
<div class="companyAccountMenu">
    <a href="/account/my-account">My account</a>

    <a href="/rally/list-rally">Rallies</a>
    <a href="/rally/list-friendly-rally">Friendly rallies</a>
    <a href="/account/my-drivers">Moi ludzie</a>
    <a href="/account/premium">Premium</a>
    <a href="/market/car-dealer">Salon samochodowy</a>
    
    <a href="/account/my-cars">Moje auta</a>
    <a href="/account/sponsor">Sponsor</a>
    <a href="/account/my-training-report">Raport z treningu</a> 
    <a href="/account/my-finances">Moje finanse</a> 
    <a href="/league/show-table">Moja tabela</a> 
    <a href="/market/show-market">Rynek transferowy</a> 
    <a href="/market/show-car-market">Rynek samochodowy</a> 
    <a href="/market/my-players-market">My players on market</a> 
    <a href="/market/my-cars-market">My cars on market</a> 
    <a href="/market/my-player-offers">My player offers</a> 
    <a href="/market/my-car-offers">My car offers</a> 
    <a href="/user/logout">Wyloguj</a>
<!--    <a href="/people/create-random-player/type/pilot">Create random pilot</a>
    <a href="/car/create-random-car">Create random car</a>
    <a href="/people/create-random-player/type/driver">Create random driver</a>-->
</div>
    <?php
}
else{
?>

	    <div class="companyAccountMenu">
		<a href="/user/register">Register</a>
		<a href="/user/login">Login</a>
		<a href="/account/my-account">My account</a>

		<a href="/rally/list-rally">Rallies</a>
<!--		<a href="/people/create-random-player/type/pilot">Create random pilot</a>
		<a href="/car/create-random-car">Create random car</a>
		<a href="/people/create-random-player/type/driver">Create random driver</a>-->
	    </div>

<?php } ?>
<div class="clearfix"></div>