<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="robots" content="index,follow" />
<meta name="author" content="kardimobile.pl" />
<title>Rally</title>

<script src="/js/jquery-2.1.3.min.js"></script>
<script src="/js/bootstrap.min.js"></script>


<link rel="stylesheet" type="text/css" href="/plugins/jMenu/css/jmenu.css" media="screen" />
 
<!-- jQuery files -->
<script type="text/javascript" src="/plugins/jMenu/js/jquery-ui.js"></script>
<script type="text/javascript" src="/plugins/jMenu/js/jMenu.jquery.min.js"></script>

<link rel="stylesheet" type="text/css" media="all" href="/css/custom.css">
<link rel="stylesheet" type="text/css" media="all" href="/css/bootstrap.css">
<link rel="stylesheet" type="text/css" media="all" href="/css/rally-custom.css">
<link rel="stylesheet" type="text/css" media="all" href="/assets/css/style.css">

<link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
