<a href='/'>
    <img src="/images/layout/logo-fastrally.png" class="logo" />
</a>
<div class="topToolbar">
    <form method="POST" action="/user/login">
        <div class='topToolbarTop'>
            <input type="text" name="login" class="textInput" placeholder='Login'/>
            <input type="password" name="password" class="textInput" placeholder='Password' />
            <button type="submit" name="submit" class='logIn btn'>LOGIN</button>
            <span class='flagSelect'>
                <img src='/images/layout/gb.png' />
            </span>
        </div>
        <div class='topToolbarBottom'>
            <input type="checkbox" id='rememberMe'/> 
            <label for='rememberMe'>Remember me</label>
            <a href="#">Can't login?</a>

        </div>
    </form>
<!--                <select>
        <option value='gb'><img src='/images/layout/gb.png' /></option>
        <option value='gb'><img src='/images/layout/pl.png' /></option>
    </select>-->
</div>