<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="robots" content="index,follow" />
<meta name="author" content="kardimobile.pl" />
<title>Rally</title>

<script src="/js/jquery-2.1.3.min.js"></script>
<script src="/js/bootstrap.min.js"></script>

<link rel="stylesheet" type="text/css" media="all" href="/css/bootstrap.css">
<link rel="stylesheet" type="text/css" media="all" href="/css/custom.css">
<link rel="stylesheet" type="text/css" media="all" href="/plugins/jquery.cookiebar/jquery.cookiebar.css">
<link rel="stylesheet" type="text/css" media="all" href="/plugins/jReject/jquery.reject.css">
<script type="text/javascript" src="/plugins/jReject/jquery.reject.js"></script>
 
<link rel="shortcut icon" type="image/ico" href="/images/layout/favicon.ico?v=4" />
 <!--jQuery files--> 
<script type="text/javascript" src="/plugins/jMenu/js/jquery-ui.js"></script>
<script type="text/javascript" src="/plugins/jMenu/js/jMenu.jquery.min.js"></script>
<script type="text/javascript" src="/plugins/jquery.cookiebar/jquery.cookiebar.js"></script>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
   
<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>

<!--[if lt IE 9]>
 <script src="/js/html5shiv.js" type="text/javascript"></script>
 <script src="/js/respond.min.js" type="text/javascript"></script>
<![endif]-->


<script>
    $(document).ready(function(){
        $.cookieBar();
        
        $.reject({  
            reject: {  
                all: false,
//                chrome: true,
                msie: 9 // Microsoft Internet Explorer  
            }  
        });
    });
</script>