<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Monitor samochodów - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Na tej stronie znajdują się informacje o aktywnych ofertach samochodów powiązanych z Twoim zespołem. <br /><br />
            Możesz tam znaleźć wszystkie oferty samochodów, które licytujesz i wszystkie oferty Twoich samochodów. <br />
            
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>