<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Dealer samochodowy - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Ta strona pozwala na zakup nowego samochodu prosto z salonu. <br /><br />
            Cena każdego samochodu ustawiana jest przez dealera samochodowego. Ich cena odpowiada rzeczywistej wartości w grze tzn. samochód wyceniony na $56000 jest lepszy od samochodu wycenionego na $41000. <br /><br />
            Miej na uwadze,że nie każdy samochód jest dostępny w salonie jak i to,że kupno samochodu jest decyzją nieodwracalną. <br /> Zanim kupisz nowy samochód, upewnij się,że stać Cię nie tylko na jego zakup ale i też na jego utrzymanie. <br />

        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>