<div class="mainUserBox">

    <h4 class="boxHeader"><?= $this->translate('Moje auta - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Na tej stronie możesz zobaczyć swój garaż z samochodami. <br /> Na każdej karcie umieszczone są następujące informacje: <br /> <br />
            <strong>1. Nazwa samochodu</strong> - Twoja własna nazwa samochodu  <br />
            <strong>2. Marka samochodu</strong><br />
            <strong>3. Poj. skokowa</strong> <br />
            <strong>4. Moc</strong> <br />
            <strong>5. V-max</strong> - prędkość maksymalna <br />
            <strong>6. Przyspieszenie</strong> - informuje jak szybko Twoje auto przyspiesza od 0 do 100km/h <br />
            <strong>7. Przebieg</strong> - pokazuje ilość km przejechanych przez samochód. Zbyt wysoki przebieg wpływa na Twoją pozycje w rajdach. <br />
            <strong>8. Wartość samochodu</strong> <br />
            <strong>9. Koszty utrzymania</strong> - koszty utrzymania samochodu są pobierane z konta Twojej drużyny co tydzień. Są one kalkulowane na podstawie wartości samochodu. <br />
            <strong>10. Sprzedaj</strong> - pozwala wystawić samochód na rynku transferowym. Ostrożnie! Ta decyzja jest nieodwracalna.<br />
            <strong>11. Zmień nazwe</strong> - pozwala zmienić nazwe samochodu raz na dany okres czasu. <br />
            <strong>12. Zezłomuj samochód</strong> - usuwa niechciane auto z Twojego garażu. Akcja ta pomniejszy Twoje tygodniowe wydatki ale kosztuje jednorazowo 1% wartości samochodu.  <br />

        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>