<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Finances - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            On this page you can see your financial report.  <br /><br />
            Incomes and expenses are splitted into following categories : <br />
            
            1. Income from rallies<br />
            2. Sponsor cash<br />
            3. Transfer income<br />
            4. Player salaries<br />
            5. Car upkeep<br />
            6. Transfer expense<br />
            7. Car purchase<br />
            8. Other incomes<br />
            9. Other expenses' <br /><br />
            It is important to keep your team's balance positive. If you keep negative balance for 5 consecutive weeks your club will become a bankrupt and your account will be deleted. <br /><br />
            Gold Member players have access to detailed financial report which allows them to control their budget better <br />
           
            
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>