<div class="mainUserBox">

    <h4 class="boxHeader"><?= $this->translate('Moje finanse - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Ta strona przedstawia Twój raport finansowy. <br /><br />
            Wpływy i wydatki podzielone są na następujące kategorie: <br />
            
            1. Income from rallies - wpływy z rajdów <br />
            2. Sponsor cash - pieniądze od sponsora<br />
            3. Transfer income - wpływy transferowe<br />
            4. Player salaries - pensje zawodników<br />
            5. Car upkeep - koszty utrzymania samochodów<br />
            6. Transfer expense - wydatki transferowe<br />
            7. Car purchase - kupno samochodów<br />
            8. Other incomes - pozostałe przychody<br />
            9. Other expenses - pozostałe wydatki <br /><br />
            Ważne aby finanse zespołu były zawsze dodatnie. Jeżeli ujemny stan konta utrzyma się przez 5 kolejnych tygodni Twój klub zbankrutuje a Twoje konto zostanie usunięte <br /><br />
            Posiadacze pakietu Gold mają dostęp do szczegółowego raportu finansowego, który pozwala im lepiej kontrolować swoje finanse <br />

            
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>