<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Forum - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Forum is a place,where you can share your thoughts and talk with FastRally community. <br /><br />
            It is divided into 5 categories : <br />
            1. <strong>General talk</strong> - here you can talk about everything which does not fit into the rest of categories. <br />
            2. <strong>Friendly rallies</strong> - if you want to find participants for your friendly rallies or ask others for invitations,this is the section for you . <br />
            3. <strong>Question & answers</strong> - this is the section where everybody could ask question about FastRally. More experienced managers will always be there to help you with their experience. <br />
            4. <strong>Off topic</strong> - you can talk over any issue non related to FastRally here.<br />
            5. <strong>Suggestions</strong> - have you got any ideas how to improve FastRally? Share it with others. We closely monitor this section to make FastRally as user friendly as possible. Be sure that every idea placed here is considered by our FastRally crew.<br />
            <br />
            In forum section Gold Member users can see also <i class="fa fa-star"></i> icon which brings a category to your favourite list. This allows managers to see those categories' last threads on their Office Homepage <br />
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>