<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Forum - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Forum jest miejscem, w którym możesz dzielić się swoimi przemyśleniami i rozmawiać z innymi członkami społeczności FastRally <br /><br />
            Jest ono podzielone na 5 kategorii : <br />
            1. <strong>Ogólne</strong> - tutaj możesz rozmawiać o wszystkim co związane z FastRally. <br />
            2. <strong>Rajdy towarzyskie</strong> - jeżeli szukasz chętnych do Twojego rajdu towarzyskiego albo poprosić o zaproszenie, to jest sekcja dla Ciebie. <br />
            3. <strong>Pytania i odpowiedzi</strong> - to jest sekcja w której każdy może zadać pytanie o FastRally.Bardziej doświadczeni menedżerzy zawsze tam będą,aby dzielić się z Tobą swoją wiedzą. <br />
            4. <strong>Off topic</strong> - możesz tutaj porozmawiać o wszystkim co nie jest związane z FastRally.<br />
            5. <strong>Sugestie i propozycje</strong> - masz pomysły jak ulepszyć FastRally? Podziel się nim z innymi. Szczegółowo monitorujemy tą sekcje aby uczynić nasza grę jak najbardziej przyjazną użytkownikom. Bądź pewien,że każdy pomysł umieszczony w tym dziale będzie rozważona przez nasz zespół FastRally.<br />
            <br />
            W tej sekcji członkowie pakietu Gold mogą także zobaczyć ikonkę <i class="fa fa-star"></i>, która dodaje kategorie do ulubionych. To pozwala menedżerom na śledzenie ostatnich tematów z tej kategorii na stronie głównej. <br />

        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>