<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Wolni zawodnicy - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Ta strona daje Ci szansę na zatrudnienie nowych kierowców lub pilotów. <br />
            Koszt takiej operacji zależy od poziomu Twojej drużyny. Ceny są następujące: <br /><br />
            <ul>
                <li>$30000 - Drużyny z ligi 1</li>
                <li>$25000 - Drużyny z ligi 2</li>
                <li>$20000 - Drużyny z ligi 3</li>
                <li>$15000 - Drużyny z ligi 4</li>
                <li>$10000 - Drużyny z ligi 5</li>
            </ul>
            <br />
            W rezultacie otrzymujesz losowego gracza. <br />
            Możesz otrzymać kierowce z czołowej ligi ale masz taką samą szanse aby otrzymać kierowce z ligi 5 <br />
            Zatrudnienie zawodnika jest decyzją nieodwracalną. <br /> Przed zatrudnieniem, upewnij się że masz pieniądze nie tylko by opłacić jego zakup, ale także aby zapłacić jego tygodniową pensje.<br />

        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>