<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Gold Membership - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            On this page you can manage your gold membership. <br /><br />Gold membership allows you to get access to additional in-game features. Gold membership can be purchased only by using your premium points.<br />
            <br />
            All features which are a part of gold membership are listed on this page. <br />
            <br />
            We offer different length of our gold package : <br />
            - 30 days (cost:80 premium points),<br />
            - 90 days (230 points),<br />
            - 180 days (430 points), <br />
            - 360 days (760 points). <br />
            <br />
          
           
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>