<div class="mainUserBox">

    <h4 class="boxHeader"><?= $this->translate('Pakiet Gold - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Ta strona pozwala na zarządzanie Twoim pakietem gold. <br /> <br/> Pakiet gold pozwala korzystać z dodatkowych elementów gry.
            Pakiet gold może być zakupiony przy użyciu punktów premium. <br /> 
            <br />
            Na tej stronie wyszczególnione są także wszystkie bonusy pakietu gold. <br />
            Oferujemy różną długość pakietu : <br />
            - 30 dni (koszt: 80 punktów premium), <br />
            - 90 dni (230 punktów), <br />
            - 180 dni (430 punktów), <br />
            - 360 dni (760 punktów). <br />
          
           
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>