<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Strona główna - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Strona główna pokazuje najświeższe newsy i liste twoich przyjaciół. <br /><br />Strona ta pozwoli Ci być na bieżąco z najnowszymi update'ami i informacjami. Możesz także sprawdzić czy Twój przyjaciel jest online i wysłać mu wiadomość używając prostych ikonek <br /> <br /> 

            Członkowie pakietu gold mogą także pozostać na bieżąco z ich ulubionymi kategoriami na forum jak i z ofertami transferowymi w których biorą udział.
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>