<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Liga - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Na tej stronie znajduje się Twoja tabela ligowa<br />
            Zawiera ona następujące informacje : <br />
            - pozycje <br />
            - nazwe drużyny <br />
            - ilość punktów zdobytych w każdym z rajdów <br />
            - łączna ilość punktów zdobytych w tym sezonie <br /> <br />
            W każdej lidze uczestniczy 16 drużyn. 
            Sezon składa się z 12 rajdów ligowych. Po zakończeniu każdego, 2 najlepsze drużyny awansują do wyższej ligi a 6 najsłabszych spada do niższej ligi. <br /><br />
            <h5 class="h3">Struktura lig w FastRally</h5> <br />
            <table class="table">
                <tr>
                    <th>Najwyzsza liga</th>
                    <td>Liga 1.0</td>
                </tr>
                
                <tr>
                    <th>Ligi poziomu 2</th>
                    <td>Liga 2.1</td>
                    <td>Liga 2.2</td>
                    <td>Liga 2.3</td>
                </tr>
                <tr>
                    <th>Ligi poziomu 3</th>
                    <td>Liga 3.1</td>
                    <td>Liga 3.2</td>
                    <td>...</td>
                    <td>Liga 3.9</td>
                </tr>
                <tr>
                    <th>Ligi poziomu 4</th>
                    <td>Liga 4.1</td>
                    <td>Liga 4.2</td>
                    <td>...</td>
                    <td>Liga 4.27</td>
                </tr>
                <tr>
                    <th>Ligi poziomu 5</th>
                    <td>Liga 5.1</td>
                    <td>Liga 5.2</td>
                    <td>...</td>
                    <td>Liga 5.81</td>
                </tr>
            </table>
            
           
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>