<ol class='manualLinks'>
    <li>
        <a href='/account/manual/homepage'>
            1.1 Strona główna
        </a>
    </li>
    <li>
        <a href='/account/manual/team'>
            1.2 Moja drużyna
        </a>
    </li>
    <li>
        <a href='/account/manual/people'>
            1.3 Moi ludzie
        </a>
    </li>
    <li>
        <a href='/account/manual/cars'>
            1.4 Moje auta
        </a>
    </li>
    <li>
        <a href='/account/manual/sponsor'>
            1.5 Sponsor
        </a>
    </li>
    <li>
        <a href='/account/manual/training-report'>
            1.6 Raport z treningu
        </a>
    </li>
    <li>
        <a href='/account/manual/finances'>
            1.7 Finanse
        </a>
    </li>
    <hr />
    <li>
        <a href='/account/manual/my-rallies'>
            2.1 Moje rajdy
        </a>
    </li>
    <li>
        <a href='/account/manual/rallies'>
            2.2 Rajdy
        </a>
    </li>
    <li>
        <a href='/account/manual/friendly-rallies'>
            2.3 Rajdy towarzyskie
        </a>
    </li>
    <li>
        <a href='/account/manual/league'>
            2.4 Liga
        </a>
    </li>
    <hr />
    <li>
        <a href='/account/manual/market-players'>
            3.1 Players
        </a>
    </li>
    <li>
        <a href='/account/manual/market-cars'>
            3.2 Zawodnicy
        </a>
    </li>
    <li>
        <a href='/account/manual/car-dealer'>
            3.3 Auta
        </a>
    </li>
    <li>
        <a href='/account/manual/player-monitor'>
            3.4 Monitor zawodników
        </a>
    </li>
    <li>
        <a href='/account/manual/car-monitor'>
            3.5 Monitor samochodów
        </a>
    </li>
    <li>
        <a href='/account/manual/free-agency'>
            3.6 Wolni zawodnicy
        </a>
    </li>
    <hr />
    <li>
        <a href='/account/manual/forum'>
            4.1 Forum
        </a>
    </li>
    <li>
        <a href='/account/manual/top-world-list'>
            4.2 Ranking menedżerów
        </a>
    </li>
    <li>
        <a href='/account/manual/national-ranking'>
            4.3 Ranking krajowy
        </a>
    </li>
    <li>
        <a href='/account/manual/search-user'>
            4.4 Znajdź gracza
        </a>
    </li>
    <hr />
    <li>
        <a href='/account/manual/play'>
            5.1 Graj
        </a>
    </li>
    <li>
        <a href='/account/manual/manage-cards'>
            5.2 Zarządzaj kartami
        </a>
    </li>
    <li>
        <a href='/account/manual/buy-cards'>
            5.3 Kup karty
        </a>
    </li>
    <li>
        <a href='/account/manual/top-list'>
            5.4 Najlepsi gracze
        </a>
    </li>
    <hr />
    <li>
        <a href='/account/manual/premium'>
            6.1 Moje premium
        </a>
    </li>
    <li>
        <a href='/account/manual/gold-membership'>
            6.2 Pakiet gold
        </a>
    </li>
    <li>
        <a href='/account/manual/invite-friends'>
            6.3 Zaproś znajomych
        </a>
    </li>
</ol>