<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Rynek samochodowy - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Na tej stronie pokazane są wszystkie samochody dostępne na rynku. <br />
            Oprócz podstawowych informacji (opisanych w sekcji 1.4 Moje samochody), możesz tam też zobaczyć następujące informacje: <br />
            <br />
            <strong>1. Najwyższa oferta</strong> - wartość najwyższej oferty wraz z nazwą drużyn, która ją złożyła i czasem złożenia oferty <br />
            <strong>2. Cena wywoławcza</strong> - cena ustalona przez właściciela samochodu. <br />
            <strong>3. Koniec aukcji</strong> - data zakończenia aukcji. <br />
            <strong>4. Pozostałe oferty</strong> - lista kilku ostatnich ofert. <br />
            <strong>5. Zalicytuj</strong> - przycisk, którego używamy do złożenia oferty. Ten przycisk nie jest widoczny dla właściciela samochodu. Każda oferta musi być o 10% wyższa od poprzedniej(poza ofertą równą cenie wywoławczej). <br />
            
            <br /><br />
            Samochody mogą przyciągać zainteresowanie wielu menedżerów. W związku z tym każda oferta złożona w ciągu ostatnich 3 minut trwania aukcji, 3 minuty zostają dodane do czasu trwania aukcji. Dzięki temu samochody zostają kupione przez najbardziej zdeterminowanych kupców. <br /> <br />

            
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>