<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Market Players - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            This is a page which shows all players available on the market. <br />
            Apart from basic player information(described in 1.3 People section), you can see there following information: <br />
            <br /> On every player's card appear following information: <br /> <br />
            <strong>1. Highest bid</strong> - value of highest bid as well as team who holds highest bid and time of bid placement  <br />
            <strong>2. Asking price</strong> - price set by manager who put player on transfer market. <br />
            <strong>3. Auction finish</strong> - date of auction finish. <br />
            <strong>4. Other offers</strong> - list of few previous highest bids. <br />
            <strong>4. Bid player</strong> - button which you can use to place your bid for player. This button is not visible for player owner. Bear in mind that every offer must be 10% greater than highest one(offer equal to asking price excluded). <br />
            
            <br /><br />
            Players might have several managers interested in their services. Therefore, for every bid placed within last 3 minutes of the auction, another 3 minutes are added to auction finish date. This operation allows players to be acquired by most interested suitors. <br /><br />
            
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>