<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Finances - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            On this page you can see all rallies that you are signed up for.  <br />
            You can see there following information : <br />
            - rally name<br />
            - date of rally <br />
            - time of rally start <br />
            - rally level - see details below <br />
            - number of crews signed up for rally <br />
            - additional info - information about your rallies <br /><br />
            
            In FastRally routes you can race in different types of rallies. : <br />
            <br />
            1. Normal rally - takes place Monday - Saturday.<br /><br />
            2. Friendly rally - rally created by players for players. <br />Can be private (<span class="label label-danger">Private</span>)
            - managers can join only by invitation of manager hosting the race, or 
            public (<span class="label label-success">Public</span>) - open to sign up for all managers. <br /><br />
            3. League rally (<span class="label label-warning">League</span>) - takes place on Sunday, every league has its own league rally.
            During these rallies teams compete not only for money, but for points to league table aswell. Every season consist of 12 league rallies.
            After each season top 2 teams are promoted to higher leage while bottom 6 teams are relegated <br /><br />
            4. Big rally <img src="/images/b_letter_small.gif" alt="Big awards" title="Big awards" /> - these rallies are held once a time.
            Those rallies give you a chance to win unique rewards - one and only cars in FastRally, as well as premium points.
           <br /> <Br />
           In additional info field you can also meet 2 other flags : <span class='label label-info'>Joined</span> - which tags rallies that you participate in, and <span class="label label-primary">Rally finished</span>, which shows that the rally has been finished.
           <br /><br />
           Each rally has its own level. Below you can see all available rally levels.
           <ul>
               <li>Open - available to sign up for everybody</li>
               <li>Second - teams of league 2 and below are eligible to sign up</li>
               <li>Third - teams of league 3 and below are eligible to sign up</li>
               <li>Fourth - teams of league 4 and below are eligible to sign up</li>
               <li>Fifth - teams of league 5 and below are eligible to sign up</li>
           </ul>
           
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>