<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('National Ranking - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            In this section you can see flags of countries which have active FastRally users.<br />
            Each FastRally user might assign their country of residence or origin to their account. <br />
            After clicking country flag, you can see its top 100 managers list. <br />
            
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>