<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Ranking krajowy - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            W tej sekcji pokazane są flagi krajów mających swoich graczy w świecie FastRally. <br />
            Każdy użytkownik może przypisać flagę swojego kraju pochodzenia bądź zamieszkania w sekcji Moje konto. <br />
            Po kliknięciu we flagę, można zobaczyć 100 najlepszych menedżerów danego kraju. <br />
            
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>