<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('People - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            On My Team page you can see drivers and pilots which are employed by your team. <br /> On every player's card appear following information: <br /> <br />
            <strong>1. Job</strong> - driver/pilot  <br />
            <strong>2. Age</strong> - age is changed every season. <br />
            <strong>3. Value</strong> - how much your player is worth. <br />
            <strong>4. Salary</strong> - players' salary are taken out of your team's finances every week. It is calculated accordingly to every player's value. <br />
            <strong>5. Sell</strong> - allows you to put unwanted player on the market. Be careful, this decision is irreversible. <br />
            <strong>6. Player skills</strong> - they show you actual player abilities. Every skill may assume values 1-10 stars. Some players might be less talented and therefore not able to train above certain skill  <br />
            <strong>7. Improve</strong> - this allows you to choose player's skill you want to be trained.  You can see daily training reports in Training Report section. Every player has own unique talent level and train certain skills faster/slower than others. <br />
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>