<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Moi ludzie - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Na stronie Moi ludzie można zobaczyć kierowców i pilotów zatrudnionych przez swoją drużynę. <br /> Na karcie każdego zawodnika umieszczone są następujące informacje: <br /> <br />
            
            <strong>1. Rola</strong> - kierowca/pilot  <br />
            <strong>2. Wiek</strong> - wiek zmienia się co sezon. <br />
            <strong>3. Wartość</strong><br />
            <strong>4. Pensja</strong> - pensja zawodników jest pobierana z konta drużyny co tydzień. Jest obliczana na podstawie wartości zawodnika. <br />
            <strong>5. Sprzedaj</strong> - pozwala umieścić niechcianego zawodnika na rynku transferowym. Uwaga! Ta decyzja jest nieodwracalna. <br />
            <strong>6. Umiejętności</strong> - pokazuja aktualne umiejętności zawodnika. Każda umiejętność może mieć wartość od 1 do 10. Niektórzy gracze mogą być mniej utalentowani i przez to nie być w stanie trenować ponad pewien poziom umiejętności.<br />
            <strong>7. Trenuj</strong> - pozwala wybrać umiejętność która chcesz aby Twój zawodnik trenował. Dzienne raporty z postępu w treningu zobaczysz w sekcji Raport z treningu. Każdy zawodnik ma określony poziom talentu i trenuje różne umiejętności w różnym tempie tzn jedna umiejętność może być trenowana szybciej a inna wolniej. <br />
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>