<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Monitor zawodników - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Na tej stronie znajdują się informacje o aktywnych ofertach zawodników powiązanych z Twoim zespołem. <br /><br />
            Możesz zobaczyć tam oferty, które zalicytowałeś jak i oferty, które wystawiłeś na rynek transferowy. <Br />
            
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>