<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Moje premium - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Ta strona pozwala zarządzać punktami premium. <br /> Punkty premium pozwalają Ci korzystać z dodatkowych funkcji w grze. <br />
            <br />
            Możesz tam zobaczyć ceny premium jak i doładować swoje konto tymi punktami. Ceny podane są w Twojej lokalnej walucie. <Br />
            <br />
            Aby zakupić punkty premium należy skorzystać z formularza na dole strony. <br />
            <br />
            <strong>Krok 1</strong>
            Wybierz ilość punktów, jaką chcesz zakupić <br /> <br />
            <strong>Krok 2</strong>
            Wybierz opcje płatności za punkty premium. <br />
            <br />
            Obecnie oferujemy następujące płatności: <br /><br />
            1. <strong>Paypal</strong> - jeden z najbardziej popularnych serwisów płatniczych na świecie. Pozwala płacić Ci kartą kredytową/debetową bądź przelewem z rachunku bankowego z całego świata.  <br />
            <br />
            2. <strong>Tpay.com(dawniej Transferuj.pl)</strong> - czołowy polski serwis płatniczy. Pozwala zapłacić przelewem z rachunku bankowego bądź transferem pocztowym. Obecnie dostępny w języku polskim,angielskim i niemieckim. Akceptuje płatności główniej w złotówkach, jednak można płacić także w euro używając opcji SEPA(Euro payments).
             <br />
            
           
           
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>