<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Szukaj gracza - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Na tej stronie możesz wyszukiwać innych graczy FastRally. 
            
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>