<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Sponsor - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            On this page you can choose your team's sponsor. <br /><br />Your sponsor will donate your team every week with certain amount of money. His logo will follow your team throughout FastRally world. <br /><br /> Every sponsor provides your team with the same amount of money. <br /> <br />
            
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>