<div class="mainUserBox">

    <h4 class="boxHeader"><?= $this->translate('Sponsor - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Na tej stronie wybierz sponsora swojego zespołu. <br/> <br />
            Twój sponsor dofinasowuje Twój zespół co tydzień pewną sumą pieniędzy. Jego logo podąża za Tobą w świecie FastRally. <br /> <br />
            Każdy sponsor dostarcza taką samą ilość pieniędzy. <br /> <br />

            
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>