<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Moja drużyna - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Na tej stronie wyświetlane są podstawowe informacje o Twojej drużynie. Działa ona na zasadzie wizytówki Twojego zespołu <br /><br />
            <strong>1. Nazwa drużyny</strong> - możesz zmienić nazwe swojej drużyny używając ikony <i class="fa fa-pencil-square-o"></i>. <br />
            <strong>2. Właściciel</strong> - pokazuje Twoje imię i nazwisko oraz login w nawiasie. Możesz ukryć swoje dane przechodząc do sekcji Zmień Dane w dziale Moje Konto. <br />
            <strong>3. Kraj</strong> - pokazuje flage Twojego kraju. Możesz zmienić swój kraj przechodząc do sekcji Zmień Dane w dziale Moje Konto. <br />
            <strong>4. Ranking</strong> - pokazuje ranking globalny Twojego zespołu. Ranking jest obliczany raz w tygodniu. <br />
            <strong>5. Liga</strong> - informacja do której ligi należysz. <br />
            <strong>6. Nagrody rajdowe</strong> - to jest Twoja prywatna gablotka z nagrodami. Nagrody zdobywasz wygrywając w rajdach. Nagrody mogą się róznić w zależności od rodzaju rajdu. <br />
            <strong>7. Samochody</strong> - w tej części możesz pochwalić się swoimi samochodami. Zdobywaj najlepsze auta i błyszcz nimi pośród znajomych. <br />
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>