<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Ranking menedżerów - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            W tej sekcji pokazana jest lista najlepszych menedżerów FastRally. <br />
            Ich ranking jest obliczany na podstawie ostatnich występów. Obliczenia dokonywane są raz na tydzień. <br />
            Możesz tutaj także zobaczyć jak ich ranking zmienił się w ciągu poprzedniego tygodnia.
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>