<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Raport treningowy - Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Na tej stronie możesz zobaczyć raport z postępów w treningu Twoich zawodników. <br /> <br />
            Raport jest obliczany codziennie. Twoje biuro dostarcza Ci raport z dnia poprzedniego tzn. we wtorek zobaczysz postęp zawodników w poniedziałkowych rajdach. <br />
            <br /> <br />
            Aby otrzymać raport z treningu musisz zrobić następujące rzeczy : <br />
            1. Idź na stronę Moi ludzie <br />
            2. Wybierz umiejętność, którą Twój zawodnik ma trenować klikając przycisk trenuj. <br />
            3. Zapisz się do rajdu <br />
            <br />
            Wykres pokazuje jak intensywnie trenował dany zawodnik. Każdy zawodnik posiada określony talent w każdej umiejętność. <br />
            Znaczy to,że każda umiejętność może być łatwiejsza lub trudniejsza do trenowania. <br />
            <br />
            <br />
            Niektóre raporty z treningu mogą pojawiać się puste. To znaczy, że gracz osiągnął maksymalny poziom gwiazdek w danej umiejętności.
            Powinieneś rozważyć zmiane trenowanej umiejętności. 
           
            
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>