<?php

/**
 * User_Model_Doctrine_Friends
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User_Model_Doctrine_Friends extends User_Model_Doctrine_BaseFriends
{
    public function setUp()
    {
        parent::setUp();
	$this->hasOne('User_Model_Doctrine_User as UserFriends', array(
             'local' => 'friend_id',
             'foreign' => 'id'));
        
	$this->hasOne('User_Model_Doctrine_User as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
	
    }
}