<?php

/**
 * user_Model_Doctrine_User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User_Model_Doctrine_User extends User_Model_Doctrine_BaseUser
{
    public static $goldPackages = array(
        7 => 20,
        30 => 40,
        90 => 80,
        180 => 160,
        360 => 320
    );
    
    public static function getGoldPackagePrices(){
        return self::$goldPackages;
    }
    
    public static function getGoldPackagePrice($days){
        if(!isset(self::$goldPackages[$days]))
            return false;
        return self::$goldPackages[$days];
    }
    
    public function setUp()
    {
        parent::setUp();
	$this->hasOne('Team_Model_Doctrine_Team as Team', array(
             'local' => 'id',
             'foreign' => 'user_id'));
	
    }
}