<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Market Cars - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            On this page your can buy a brand new car straight from a car dealer. <br /> <br />
            Every car has its dealer price. Cars are priced accordingly to their in-game value.This means that car priced $56000 would be slightly better than car priced $41000. <br /><br />
            Bear in mind that not every car is available at car dealer. Buying a car from dealer is an irreversible decision. <br />Before you buy a new car, make sure you have enough money not only to pay for car, but also to pay its weekly upkeep. <br />
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>