<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Cars - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            On Cars page you can your garage. <br /> On every car's card appear following information: <br /> <br />
            <strong>1. Car name</strong> - your very own car name  <br />
            <strong>2. Brand</strong> - real car brand. <br />
            <strong>3. Capacity</strong> <br />
            <strong>4. Horse power</strong> <br />
            <strong>5. V-max</strong> - maximum speed of your car <br />
            <strong>6. Acceleration</strong> - how quick your car can accelerate from 0 to 100 km/h <br />
            <strong>7. Mileage</strong> - shows number of km that you car has passed. Too high mileage will affect your car on rallies.<br />
            <strong>8. Value</strong> - how much your car is worth. <br />
            <strong>9. Upkeep</strong> - cars' upkeep are taken out of your team's finances every week. It is calculated accordingly to every car's value. <br />
            <strong>10. Sell</strong> - allows you to put unwanted car on the market. Be careful, this decision is irreversible. <br />
            <strong>11. Change name</strong> - allows you to change your car's name once a time  <br />
            <strong>12. Scrap car</strong> - remove unwanted car from your garage. This action will reduce your weekly expenses. Be careful, this decision is irreversible.  <br />
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>