<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Free Agency - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            This page gives you an opportunity to hire new drivers or pilots. <br />
            The cost of such operation depends on your team level. Prices are as following : <br /><br />
            <ul>
                <li>$50000 - League 1 teams</li>
                <li>$40000 - League 2 teams</li>
                <li>$30000 - League 3 teams</li>
                <li>$20000 - League 4 teams</li>
                <li>$10000 - League 5 teams</li>
            </ul>
            <br />
            In result you will get random skilled player. <br />
            You can get top league level driver but there is an equal chance that you will get league 5 level driver <br />
            Signing a player through free agency is an irreversible decision. <br />Before you sign a new player, make sure you have enough money not only to pay for free agency, but also to pay his weekly salary. <br />
            
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>