<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Office Home - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Office home displays you latest game news and your friend list. <br /><br /> On this page you can stay up-to-date with latest game updates and information. You can also check your friend's status and go to their message box using simple icon shortcuts. <br /><br />
            
            Gold Member users can also stay up-to-date with their favourite forum categories as well as market offers. 
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>