<ol class='manualLinks'>
    <li>
        <a href='/account/manual/homepage'>
            1.1 Office home
        </a>
    </li>
    <li>
        <a href='/account/manual/team'>
            1.2 My team
        </a>
    </li>
    <li>
        <a href='/account/manual/people'>
            1.3 People
        </a>
    </li>
    <li>
        <a href='/account/manual/cars'>
            1.4 Cars
        </a>
    </li>
    <li>
        <a href='/account/manual/sponsor'>
            1.5 Sponsor
        </a>
    </li>
    <li>
        <a href='/account/manual/training-report'>
            1.6 Training report
        </a>
    </li>
    <li>
        <a href='/account/manual/finances'>
            1.7 Finances
        </a>
    </li>
    <hr />
    <li>
        <a href='/account/manual/my-rallies'>
            2.1 My rallies
        </a>
    </li>
    <li>
        <a href='/account/manual/rallies'>
            2.2 Rallies
        </a>
    </li>
    <li>
        <a href='/account/manual/friendly-rallies'>
            2.3 Friendly rallies
        </a>
    </li>
    <li>
        <a href='/account/manual/league'>
            2.4 League
        </a>
    </li>
    <hr />
    <li>
        <a href='/account/manual/players'>
            3.1 Players
        </a>
    </li>
    <li>
        <a href='/account/manual/cars'>
            3.2 Cars
        </a>
    </li>
    <li>
        <a href='/account/manual/car-dealer'>
            3.3 Car dealer
        </a>
    </li>
    <li>
        <a href='/account/manual/player-monitor'>
            3.4 Player monitor
        </a>
    </li>
    <li>
        <a href='/account/manual/car-monitor'>
            3.5 Car monitor
        </a>
    </li>
    <li>
        <a href='/account/manual/free-agency'>
            3.6 Free agency
        </a>
    </li>
    <hr />
    <li>
        <a href='/account/manual/forum'>
            4.1 Forum
        </a>
    </li>
    <li>
        <a href='/account/manual/top-world-list'>
            4.2 Top world list
        </a>
    </li>
    <li>
        <a href='/account/manual/national-ranking'>
            4.3 National ranking
        </a>
    </li>
    <li>
        <a href='/account/manual/search-user'>
            4.4 Search user
        </a>
    </li>
    <hr />
    <li>
        <a href='/account/manual/premium'>
            4.1 My premium
        </a>
    </li>
    <li>
        <a href='/account/manual/gold-membership'>
            4.2 Gold membership
        </a>
    </li>
    <li>
        <a href='/account/manual/invite-friends'>
            4.3 Invite friends
        </a>
    </li>
</ol>