<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Player monitor - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            This page gives you information about all active player market actions related to your team. <br /><br />
            You can see there all active player offers which you have bid for as well as all active offers of your players. <br />
            
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>