<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('My premium - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            On this page you can manage your premium points. <br />Premium points allows you to get access to additional in-game features. <br />
            <br />
            You can see there premium prices as well as you can top-up your premium points. Premium prices are displayed in currency of your location.<br />
            <br />
            In order to buy premium points you need to fill form at the bottom of this page. <br />
            <br />
            <strong>Step 1</strong>
            Select requested amount of points <br /> <br />
            <strong>Step 2</strong>
            In second step you can choose provider you want to use to pay for premium points. <br />
            <br />
            Currently we offer following providers: <br /><br />
            1. <strong>Paypal</strong> - one of world's most popular payment services. Allows you to pay with credit/debit cards or your bank account from all over the world.  <br />
            <br />
            2. <strong>Tpay.com (former Transferuj.pl)</strong> - polish top payment service. Allows you to pay with your bank account or postal transfer. Currently available in polish, english and german languages. It accept payments mainly in PLN, however you can pay also in EUR using SEPA(Euro payments) option on their payment page.
           
            
           
           
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>