<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Search User - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            This page gives you an opportunity to search other FastRally managers.
            
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>