<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('My Team - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            On My Team page you can see team's basic information. It is working like a business card of your team. <br /> <br />
            <strong>1. Team name</strong> - you can change your team's name using <i class="fa fa-pencil-square-o"></i> icon. <br />
            <strong>2. Owner</strong> - it shows your name and login in brackets. You can remain anonymous using Edit Details page in My Account section. <br />
            <strong>3. Country</strong> - it shows a flag of your country. You can change it using Edit Details page in My Account section. <br />
            <strong>4. Rank</strong> - it shows your team's global ranking. Ranking is calculated once a week. <br />
            <strong>5. League</strong> - it shows your team's league. <br />
            <strong>6. Rally awards</strong> - it is a cabinet for your awards. You are awarded trophies after you win a rally. Awards can differ depending on type of won rally <br />
            <strong>7. Cars</strong> - in this section of My Team your cars are promoted throughout other players. You can shine among your friends with your cars. <br />
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>