<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Top World List - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            In this section you can see top FastRally managers. <br />
            Their ranking is calculated on their recent rally performances. It is calculated once a week. <br />
            On this list you can also see how manager's ranking has changed since last week.
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>