<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Training Report - FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            On this page you can see everyday training report of your players.  <br /><br />
            Training report is calculated on a daily basis. Your office provides you with a training report from a previous day. It means that Tuesday training report shows you players' progress during Monday rallies.<br />
            <br /><br />In order to receive training reports you must do following things : <br />
            1. Go to People page in Office section. <br />
            2. Choose the skill you want your player to train by clicking button Improve. <Br />
            3. Sign up for a rally <br />
            <br />
            The graph you receive shows you how hard did the player train. Every player has certain amount of talent in every skill. <br />This means that some skills might be easier trainable and some harder. <br />
            <br />
            Some training reports means might come up empty. This means that player has reached maximum amount of stars in this skill. You should consider choosing different training skill <br />
           
            
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>