<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * 
 * @Author = Tomasz Kardas <kardi31@tlen.pl>
 */
?>

<html>
    <head>
	<?php echo $this->showFile('_head.phtml'); ?>
    </head>
    <body>
	<div class="mainContainer">
                <header>
                    <?php echo $this->showFile('_header.phtml'); ?>
                </header>
                <div class="mainContent mainUserContent">
                    <?php echo $this->responseSegment['menu']; ?>
                    
	    
	<?php // echo $this->showFile('_header.phtml'); ?>
                    
            <div class='col-md-3'>
                <?php echo $this->responseSegment['calendar']; ?>
                <?php echo $this->responseSegment['left-banner']; ?>
                <?php echo $this->responseSegment['friends']; ?>
            </div>
            <div class='col-md-9'>
                <?php echo $this->content; ?>
            </div>
            <!--<div class="col-md-3">-->
                <?php // echo $this->responseSegment['forum']; ?>
                <?php // echo $this->responseSegment['right-banner']; ?>
                <?php // echo $this->responseSegment['market']; ?>
            <!--</div>-->
                    <div class="clearfix"></div>
                </div>
                <?php echo $this->showFile('_footer_main.phtml'); ?>
        </div>
    </body>
</html>
