<?php

/* 
 * @Author = Tomasz Kardas <kardi31@tlen.pl>
 */
?>

<html>
    <head>
	<?php echo $this->showFile('_head.phtml'); ?>
    </head>
    <body>
	<div class="mainContainer">
                <header>
                    <?php echo $this->showFile('_header.phtml'); ?>
                </header>
                <div class="mainContent mainUserContent">
                    <?php echo $this->responseSegment['menu']; ?>
                    
                    <div>
                        <?php echo $this->content; ?>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <?php echo $this->showFile('_footer_main.phtml'); ?>
        </div>
    </body>
</html>
