<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * 
 * @Author = Tomasz Kardas <kardi31@tlen.pl>
 */
?>

<html>
    <head>
	<?php echo $this->showFile('_head.phtml'); ?>
    </head>
    <body>
	<header class="h10 sticky-enabled no-topbar">
      
	</header>
	<section class="main">
	    
	<?php echo $this->showFile('_header.phtml'); ?>
            <div class='col-md-3'>
                
                <?php echo $this->responseSegment['friends']; ?>
                <?php echo $this->responseSegment['forum']; ?>
            </div>
            <div class='col-md-9'>
                <?php echo $this->content; ?>
            </div>
	</section>
	
    </body>
</html>
