<?php

/**
 * League_Model_Doctrine_BaseLeague
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $league_name
 * @property integer $league_level
 * @property League_Model_Doctrine_Season $Season
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class League_Model_Doctrine_BaseLeague extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('league_league');
        $this->hasColumn('league_name', 'varchar', 255, array(
             'type' => 'varchar',
             'primary' => true,
             'length' => '255',
             ));
        $this->hasColumn('league_level', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('League_Model_Doctrine_Season as Season', array(
             'local' => 'league_name',
             'foreign' => 'league_name'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}