<?php

/**
 * People_Model_Doctrine_People
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class People_Model_Doctrine_People extends People_Model_Doctrine_BasePeople
{
    private static $skillName = array(
        'composure' => 'Composure',
        'speed' => 'Speed',
        'regularity' => 'Regularity',
        'reflex' => 'Reflex',
        'on_gravel' => 'Driving on gravel',
        'on_tarmac' => 'Driving on tarmac',
        'on_snow' => 'Driving on snow',
        'talent' => 'Talent',
        'form' => 'Form',
        'composure' => 'Composure',
        'dictate_rhytm' => 'Dictate rhytm',
        'diction' => 'Diction',
        'route_description' => 'Route description'
    );
    
    
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Team_Model_Doctrine_Team as Driver1Team', array(
             'local' => 'id',
             'foreign' => 'driver1_id'));
	
	$this->hasOne('Team_Model_Doctrine_Team as Driver2Team', array(
             'local' => 'id',
             'foreign' => 'driver2_id'));
	
	$this->hasOne('Team_Model_Doctrine_Team as Pilot1Team', array(
             'local' => 'id',
             'foreign' => 'pilot1_id'));
	
	$this->hasOne('Team_Model_Doctrine_Team as Pilot2Team', array(
             'local' => 'id',
             'foreign' => 'pilot2_id'));
        
        $this->hasOne('Team_Model_Doctrine_Team as Team', array(
             'local' => 'team_id',
             'foreign' => 'id'));
	
	$this->hasMany('Rally_Model_Doctrine_Crew as PilotRallies', array(
             'local' => 'id',
             'foreign' => 'pilot_id'));
	
        
	$this->hasMany('Rally_Model_Doctrine_Crew as DriverRallies', array(
             'local' => 'id',
             'foreign' => 'driver_id'));
	
    }
    
    public static function showSkillName($skill){
        return self::$skillName[$skill];
    }
}