<?php

/**
 * People_Model_Doctrine_TrainingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class People_Model_Doctrine_TrainingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object People_Model_Doctrine_TrainingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('People_Model_Doctrine_Training');
    }
}