<?php

/**
 * People_Model_Doctrine_Training
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class People_Model_Doctrine_Training extends People_Model_Doctrine_BaseTraining
{

}