<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Faq'); ?></h4>
    <div class='staticWrapper'>
        <div class="panel-group" id="accordion"> <!-- accordion 1 -->
            <div class="panel panel-custom">

                 <div class="panel-heading"> <!-- panel-heading -->
                     <h4 class="panel-title"> <!-- title 1 -->
                     <a data-toggle="collapse" data-parent="#accordion" href="#accordionOne">
                       Do czego służą ikony w lewym górnym rogu? 
                     </a>
                    </h4>
                 </div>
                         <!-- panel body -->
                 <div id="accordionOne" class="panel-collapse collapse">
                   <div class="panel-body">
                        <i class="fa fa-car"></i> - ta ikonka świeci, gdy jeden z rajdów z Twoim udziałem właśnie trwa <br />
                        <i class="fa fa-info-circle"></i> - ta ikonka otwiera okno powiadomień. Kiedy świeci oznacza,że czekają na Ciebie nieprzeczytane powiadomienia <br />
                        <i class="fa fa-user-plus"></i> - oznacza aktywne zaproszenia od rajdów towarzyskich <br />
                        <i class="fa fa-envelope-o"></i> - ta ikonka przenosi do Twojej skrzynki wiadomości. Kiedy świeci, oznacza nieprzeczytaną wiadomość. <br />
                       <img class="coin" src="/images/layout/coin.png"> - numer przed tą ikonką pokazuje stan Twoich punktów premium
                   </div>
                 </div>
           </div>
  
            <div class="panel panel-custom" id="trainingReport">  <!-- accordion 2 -->

                   <div class="panel-heading"> 
                   <h4 class="panel-title"> <!-- title 2 -->
                     <a data-toggle="collapse" data-parent="#accordion" href="#accordionTwo">
                       Jak działa raport z treningu?
                     </a>
                   </h4>
                   </div>
                          <!-- panel body -->
                 <div id="accordionTwo" class="panel-collapse collapse">
                   <div class="panel-body">
                       Gracze mogą poprawiać swoje umiejętności poprzez udział w rajdach <br />
                       Aby otrzymać raport z treningu musisz wybrać umiejętność która zawodnik ma trenować. Możesz to zrobić w sekcji Moi ludzie. <br />
                       Wykres treningowy pokazuje jak ciężko dany zawodnik trenował. <br /> <br />
                       Przykład : <br />
                       Kierowca 1 trenował jazde po asfalcie na poziomie 91%. <br />
                       Kierowca 2 trenował jazde po śniegu na poziomie 25%. <br />
                       Znaczy to,że kierowca 1 jest bardzo utalentowany w jeździe po asfalcie i następną gwiazdke otrzyma stosunkowo szybko. <br />
                       Kierowca 2, w przeciwieństwie do kierowcy 1, nie jest bardzo utalentowany w jeździe po śniegu i ta umiejętność nie poprawi mu się szybko.
  
                   </div>
                 </div>

            </div>
   
            <div class="panel panel-custom">  <!-- accordion 3 -->

                <div class="panel-heading">
                  <h4 class="panel-title"> <!-- title 3 -->
                    <a data-toggle="collapse" data-parent="#accordion" href="#accordionThree">
                        Mój zawodnik nie trenował dzisiaj. Co się stało? 
                    </a>
                  </h4>
                </div>

                <div id="accordionThree" class="panel-collapse collapse">
                  <!-- panel body -->
                    <div class="panel-body">
                        Może być to spowodowane kilkoma rzeczami. <br /> <br />
                        1. Nie zapisałeś gracza do rajdu w dniu poprzednim. <br />
                        2. Nie wybrałeś umiejętności, którą ma trenować gracz (aby to zrobić - idź do sekcji Moi ludzie i kliknij przycisk trenuj). <br />
                        3. Umiejętność, którą wybrałeś osiągnęła u tego gracza swój maksymalny poziom. Nie każdy gracz może wytrenować swoje umiejętności na 10 gwiazdek. Niektórzy mogą nie być w stanie dalej trenować pewnych umiejętności. <br />
                        W takiej sytuacji powinieneś się skupić na trenowaniu innych umiejętności u tego gracza bądź kupnie innego gracza. 
                  </div>

               </div>

            </div>
            
            
        <div class="panel panel-custom">  <!-- accordion 3 -->

            <div class="panel-heading">
                <h4 class="panel-title"> <!-- title 3 -->
                  <a data-toggle="collapse" data-parent="#accordion" href="#accordionFour">
                      Nie otrzymałem zakupionego gracza / samochodu. Co się stało? 
                  </a>
                </h4>
            </div>

            <div id="accordionFour" class="panel-collapse collapse">
                  <!-- panel body -->
                <div class="panel-body">
                    Zakończenie aukcji nie oznacza automatycznego przejścia zawodnika/samochodu do nowego zespołu. Zakupione auto/zawodnik dołączy do swojej nowej drużyny w nocy dnia następnego. 
                </div>

            </div>

         </div>
            
        <div class="panel panel-custom">  <!-- accordion 3 -->

            <div class="panel-heading">
                <h4 class="panel-title"> <!-- title 3 -->
                  <a data-toggle="collapse" data-parent="#accordion" href="#accordionFive">
                      Ile można wygrać w pojedynczym rajdzie?
                  </a>
                </h4>
            </div>

            <div id="accordionFive" class="panel-collapse collapse">
                  <!-- panel body -->
                <div class="panel-body">
                    Pula nagród zależy od liczby  graczy. Podstawowa pula nagród dla rajdów kategorii Open wynosi $140 000. Za każdego uczestnika pula nagród wzrasta o $2 000. <br /><br />
                    Nagrody zależą także w inny sposób od liczby użytkowników. Jeżeli rajd ma ponad 10 uczestników, nagradzane jest 8 najlepszych miejsc. Jeżeli liczba uczestników jest mniejsza, nagradzane są 3 czołowe miejsca. 
                </div>

            </div>

         </div>
            
        <div class="panel panel-custom">  <!-- accordion 3 -->

            <div class="panel-heading">
                <h4 class="panel-title"> <!-- title 3 -->
                  <a data-toggle="collapse" data-parent="#accordion" href="#accordionSix">
                      Mój zespół ryzykuje bankructwo. Co powinienem zrobić?
                  </a>
                </h4>
            </div>

            <div id="accordionSix" class="panel-collapse collapse">
                  <!-- panel body -->
                <div class="panel-body">
                    Jest kilka sposobów na zapobiegnięcie bankructwu. <br />
                    1. Wybieraj swoje ustawienia ostrożniej dołączając do rajdów. Drużyny, które nie ukończą rajdu nie są nagradzane. <br />
                    2. Postaraj się brać udział w większej ilości rajdów. Da Ci to większe szanse na nagrode. <br />
                    3. Sprzedaj / zezłomuj niechcianych zawodników bądź samochody. <br />
                    <br />
                    Te akcje pomogą Twojej drużynie osiągnąć dodatni stan konta.
                </div>

            </div>

         </div>
        <div class="panel panel-custom">  <!-- accordion 3 -->

            <div class="panel-heading">
                <h4 class="panel-title"> <!-- title 3 -->
                  <a data-toggle="collapse" data-parent="#accordion" href="#accordionSeven">
                      Czemu zmieniła się data zakończenia mojej aukcji?
                  </a>
                </h4>
            </div>

            <div id="accordionSeven" class="panel-collapse collapse">
                  <!-- panel body -->
                <div class="panel-body">
                    Każda oferta w ciągu ostatnich 3 minut aukcji przedłuża jej czas zakończenia o kolejne 3 minuty. <br />
                    Daje to menedżerom bardziej uczciwe szanse na wygranie aukcji a sprzedającemu na zarobienie więcej pieniędzy. <br />
                </div>

            </div>

         </div>
            
        <div class="panel panel-custom">  <!-- accordion 3 -->

            <div class="panel-heading">
                <h4 class="panel-title"> <!-- title 3 -->
                  <a data-toggle="collapse" data-parent="#accordion" href="#accordionEight">
                    This field contain forbidden characters. Co to znaczy?
                  </a>
                </h4>
            </div>

            <div id="accordionEight" class="panel-collapse collapse">
                  <!-- panel body -->
                <div class="panel-body">
                    Formularze, które pokazują taki błąd mogą zawierać tylko określone znaki . <br />
                    Wśród tych znaków są : litery,cyfry,spacje, # oraz -.
                </div>

            </div>

         </div>
        </div>
    </div>
</div>