<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Faq'); ?></h4>
    <div class='staticWrapper'>
        <div class="panel-group" id="accordion"> <!-- accordion 1 -->
            <div class="panel panel-custom">

                 <div class="panel-heading"> <!-- panel-heading -->
                     <h4 class="panel-title"> <!-- title 1 -->
                     <a data-toggle="collapse" data-parent="#accordion" href="#accordionOne">
                       What are icons in left top corner for?
                     </a>
                    </h4>
                 </div>
                         <!-- panel body -->
                 <div id="accordionOne" class="panel-collapse collapse">
                   <div class="panel-body">
                        <i class="fa fa-car"></i> - when this icon is shining, one of rallies that you have signed up for , is in progress <br />
                        <i class="fa fa-info-circle"></i> - This icon opens up your notification box. When it is shining, you have got unread notifications <br />
                        <i class="fa fa-user-plus"></i> - when this icon is shining, you have pending invitation for a friendly rally <br />
                        <i class="fa fa-envelope-o"></i> - this icon brings you to your message box. When it is shining, you have got unread messages <br />
                       <img class="coin" src="/images/layout/coin.png"> - number before this icon informs you about your premium coin balance
                   </div>
                 </div>
           </div>
  
            <div class="panel panel-custom" id="trainingReport">  <!-- accordion 2 -->

                   <div class="panel-heading"> 
                   <h4 class="panel-title"> <!-- title 2 -->
                     <a data-toggle="collapse" data-parent="#accordion" href="#accordionTwo">
                       How training report works?
                     </a>
                   </h4>
                   </div>
                          <!-- panel body -->
                 <div id="accordionTwo" class="panel-collapse collapse">
                   <div class="panel-body">
                       Players can improve their skills by racing in rallies <br />
                       In order to receive training reports, you need to choose which player skills you want to train. You can do it in my players section. <br />
                       
                       Graph on your training report illustrates how hard did your player train today. <br /> <br />
                       Example : <br />
                       Player 1 trained his 'on tarmac' skill at 91% level.<br />
                       Player 2 trained his 'on snow' skill at 25% level <br />
                       This means that player 1 is very talented in driving on tarmac and he will gain next star relatively quickly. <br />
                       Unlike player 2, who is not very talented in driving on snow and this skill will not be improved quickly. 
                   </div>
                 </div>

            </div>
   
            <div class="panel panel-custom">  <!-- accordion 3 -->

                <div class="panel-heading">
                  <h4 class="panel-title"> <!-- title 3 -->
                    <a data-toggle="collapse" data-parent="#accordion" href="#accordionThree">
                      My player did not train today. What happened?
                    </a>
                  </h4>
                </div>

                <div id="accordionThree" class="panel-collapse collapse">
                  <!-- panel body -->
                    <div class="panel-body">
                        There might be few reasons of it. <br /><br />
                        1. You did not sign up player for rally the previous day. <br />
                        2. You did not choose skill which you want to train(to do so - go to my players and click button 'improve').<br />
                        3. The skill you wanted to train has reached its maximum level. Not every player might improve his skills to 10 stars. Some of them might not be able to learn certain skill anymore. <br />
                        In such situation you should focus on training other skills or buying a better player.
                  </div>

               </div>

            </div>
            
            
        <div class="panel panel-custom">  <!-- accordion 3 -->

            <div class="panel-heading">
                <h4 class="panel-title"> <!-- title 3 -->
                  <a data-toggle="collapse" data-parent="#accordion" href="#accordionFour">
                    I did not receive player / car which I have bought
                  </a>
                </h4>
            </div>

            <div id="accordionFour" class="panel-collapse collapse">
                  <!-- panel body -->
                <div class="panel-body">
                    Transfers are not completed immidately. Your new player/car will join your team following day at night.
                </div>

            </div>

         </div>
            
        <div class="panel panel-custom">  <!-- accordion 3 -->

            <div class="panel-heading">
                <h4 class="panel-title"> <!-- title 3 -->
                  <a data-toggle="collapse" data-parent="#accordion" href="#accordionFive">
                    How much can you win in single rally?
                  </a>
                </h4>
            </div>

            <div id="accordionFive" class="panel-collapse collapse">
                  <!-- panel body -->
                <div class="panel-body">
                    Prize pool in rally depends on number of participants. Basic prize pool is $140 000. For every participant, prize pool increases by $2 000. <br /> <br />
                    Prizes depends on number of participants of single rally aswell. If rally has 10 or more participants, top 8 places are rewarded. If the number of participants is less than 10, top 3 places are rewarded.
                </div>

            </div>

         </div>
            
        <div class="panel panel-custom">  <!-- accordion 3 -->

            <div class="panel-heading">
                <h4 class="panel-title"> <!-- title 3 -->
                  <a data-toggle="collapse" data-parent="#accordion" href="#accordionSix">
                    My team risks going bankrupt. What should I do? 
                  </a>
                </h4>
            </div>

            <div id="accordionSix" class="panel-collapse collapse">
                  <!-- panel body -->
                <div class="panel-body">
                    There are several actions you might take to prevent going bankrupt.<br/> 
                    1. When joining rallies, try to choose your settings more carefully. Teams which not finish rally are not rewarded. <br />
                    2. Try to join more rallies. This will give you a better chance to be rewarded. <br />
                    3. Sell / scrap unneeded players or cars. <br />
                    <br />
                    These actions will help your team reach positive account balance.
                </div>

            </div>

         </div>
        <div class="panel panel-custom">  <!-- accordion 3 -->

            <div class="panel-heading">
                <h4 class="panel-title"> <!-- title 3 -->
                  <a data-toggle="collapse" data-parent="#accordion" href="#accordionSeven">
                    Why has finish date of my offer has changed?
                  </a>
                </h4>
            </div>

            <div id="accordionSeven" class="panel-collapse collapse">
                  <!-- panel body -->
                <div class="panel-body">
                    Every bid within last 3 minutes of auction increases finish date by another 3 minutes. <br />
                    This gives every manager more fair chances of winning auction. Also it allows player/car owner to earn more money. <br />
                </div>

            </div>

         </div>
            
        <div class="panel panel-custom">  <!-- accordion 3 -->

            <div class="panel-heading">
                <h4 class="panel-title"> <!-- title 3 -->
                  <a data-toggle="collapse" data-parent="#accordion" href="#accordionEight">
                    This field contain forbidden characters. What does it mean?
                  </a>
                </h4>
            </div>

            <div id="accordionEight" class="panel-collapse collapse">
                  <!-- panel body -->
                <div class="panel-body">
                    Form fields which shows you this error message may include just certain characters.<br />
                    Among those characters are : letters, numbers, spaces, # and -.
                </div>

            </div>

         </div>
        </div>
    </div>
</div>