	    <div class="companyAccountMenu">
		<a href="/user/register">Register</a>
		<a href="/user/login">Login</a>
		<a href="/account/my-account">My account</a>

		<a href="/rally/list-rally">Rallies</a>
<!--		<a href="/people/create-random-player/type/pilot">Create random pilot</a>
		<a href="/car/create-random-car">Create random car</a>
		<a href="/people/create-random-player/type/driver">Create random driver</a>-->
	    </div>