<div class="col-md-12">
    <div class="col-md-6 mainPageBox leftMainPageBox">
        <h2><?= $this->translate('ABOUT'); ?></h2>
        
        <img src="/images/layout/fotolia_78706818.jpg" alt='Race with FastRally' title='Race with FastRally' />
         
        <?= $this->translate('FastRally world gives you opportunity to become the manager of your very own rally team. Hire drivers and pilots, buy cars and race with others. Compete with managers all around the world, win trophies,collect unique cars and become a FastRally legend.'); ?>
       
        <div class='clearfix'></div>
        <br />
        <img src="/images/layout/fastrally_cards.png" id='fastRallyCardsImg' alt='FastRally card game' title='FastRally card game' />
         <?= $this->translate('Want to win new cars faster? Try our FastRally card game. Get to the tables, win playing cards and turn them to cars. Climb up in card rankings and represent your country in national rankings.'); ?>
        <br /><br />
        <div class='clearfix'></div>
        <br />
        <strong><?= $this->translate('Do not hesitate! Register and join the unique and mysterious world of FastRally.'); ?></strong> <br />

        <div class="clearfix"></div>
    </div>
    <div class="col-md-1"></div>
    <div class="col-md-4 mainPageBox rightMainPageBox">
        <?php
            if(isset($_GET['msg'])){
                if($_GET['msg']=="email exists"){
                    $this->showError($this->translate('Sorry. This email is already registered.'));
                }
                elseif($_GET['msg']=="username exists"){
                    $this->showError($this->translate('Sorry. This user is already registered.'));
                }
                elseif($_GET['msg']=="no user"){
                    $this->showError($this->translate('Incorrect login'));
                }
                elseif($_GET['msg']=="wrong password"){
                    $this->showError($this->translate('Incorrect password'));
                }
                elseif($_GET['msg']=="not active"){
                    $this->showError('Your account is not active. Check your mail and spam box. In case of problems, write to activate@fastrally.eu');
                }
            }
        ?>
        <h2><?= $this->translate('REGISTRATION'); ?></h2>
        <form method="POST" action="/user/register">
            
            <label for="username"><?= $this->translate('Login'); ?><sup>*</sup>
                <i class='fa fa-info-circle pull-right' title='Login must be 4-12 characters long. It must contain at least 3 letters.'></i>
            </label>
            <?= $form->getElement('username')->renderElement(); ?>
            <label for="login">
            <?= $this->translate('Password'); ?><sup>*</sup>
            <i class='fa fa-info-circle pull-right' title='Password must be 4-12 characters long.'></i>
            </label>
            <?= $form->getElement('password')->renderElement(); ?>
            <label for="login"><?= $this->translate('Repeat password'); ?><sup>*</sup></label>
            <?= $form->getElement('password2')->renderElement(); ?>
            <label for="login"><?= $this->translate('E-mail address'); ?><sup>*</sup></label>
            <?= $form->getElement('email')->renderElement(); ?>
            <?= $form->getElement('invite')->renderElement(); ?>
            <span class="acceptRules">
                <input type="checkbox" required name="rules" id='acceptRules'/> 
                <label for='acceptRules'><?= $this->translate('I accept'); ?> <a href="/rules" target='_blank'><?= $this->translate('rules'); ?></a></label>
            </span>

            <button type="submit" name="submit" class='logIn btn'>REGISTER</button>
        </form>
    </div>
</div>
<div class="clearfix"></div>