<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Instrukcja FastRally'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            Ta instrukcja jest kompletnym przewodnikiem po świecie FastRally. <br />
            Dla Twojej wygody jest ona podzielona na sekcje, które odpowiadają menu gry <br />
            Pierwsza cyfra każdego artykułu instrukcji pokazuje kategorie do której należy: <br /><br />
            1 - Biuro<br />
            2 - Moje rajdy <br />
            3 - Rynek <br />
            4 - Społeczność <br />
            5 - Gra w karty <br />
            6 - Premium <br />
            7 - Pomoc <br/> <br />
            Jeżeli nie znalazłeś tutaj odpowiedzi na swoje pytanie, sprawdź sekcje FAQ bądź kategorie 'pytania i odpowiedzi' na forum.
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual-pl/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>