<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('FastRally Manual'); ?></h4>
    <div class='staticWrapper'>
        <div class='col-md-9'>
            This manual is an ultimate guide to FastRally. <br /> For your convenience, it is divided into sections which reflects menu navigation of the game.
            <br />The first digit of every manual link shows you the category : <br /><br />
            1 - Office<br />
            2 - My rallies <br />
            3 - Market <br />
            4 - Community <br />
            5 - Premium <br />
            6 - Help <br/> <br />
            If you cannot find answer to your question, check FAQ section or Question & Answers section in the Forum.
        </div>
        <div class='col-md-3'>
            <?php include(BASE_PATH."/modules/index/views/manual/manual-menu.phtml"); ?>
        </div>
        <div class='clearfix'></div>
    </div>
</div>