<script type="text/javascript">
  $(document).ready(function(){
 
        $("#tMenu > li > a").click(function (e) { // binding onclick
                var li = $(this).parent();
                var ul = $(this).next('ul');
                
                $('li.selected ul').slideUp(100);
	        $('li.selected ul').removeClass("selected");
	        if (li.hasClass('selected')) {
	            ul.slideUp(200); // hiding popups
	            li.removeClass("selected");
	        } else {
	            ul.slideDown(200); // hiding popups
	            li.addClass("selected");
	        }
	        e.stopPropagation();
	    });

  });
  
</script>

<div id="menu">
    <ul id="tMenu">
        <li>
            <a href="javascript:void(0)"><?= $this->translate('Office'); ?></a>
            <ul>
                <li>
                    <a href="/team/show-team/id/<?= $authenticatedUser['Team']['id']; ?>"><?= $this->translate('My team'); ?></a>
                </li>
                <li>
                    <a href="/account/my-account"><?= $this->translate('Account'); ?></a>
                </li>
                <li>
                    <a href="/account/my-people"><?= $this->translate('People'); ?></a>
                </li>
<!--                <li>
                    <a href="/account/tactics"><?= $this->translate('Taktyka'); ?></a>
                </li>-->
                <li>
                    <a href="/account/my-cars"><?= $this->translate('Cars'); ?></a>
                </li>
                <li>
                    <a href="/account/sponsor"><?= $this->translate('Sponsor'); ?></a>
                </li>
                <li>
                    <a href="/account/my-training-report"><?= $this->translate('Training report'); ?></a> 
                </li>
                <li>
                    <a href="/account/my-finances"><?= $this->translate('Finances');?></a> 
                </li>
            </ul>
        </li>
        <li>
            <a href="javascript:void(0)"><?= $this->translate('My rallies') ;?></a>
            <ul>
                <li>
                    <a href="/rally/my-rallies"><?= $this->translate('My rallies'); ?></a>
                </li>
                <li>
                    <a href="/rally/list-rally"><?= $this->translate('Rallies'); ?></a>
                </li>
<!--                <li>
                    <a href="/rally/my-friendly-rallies"><?= $this->translate('My friendly rallies'); ?></a>
                </li>-->
                <li>
                    <a href="/rally/list-friendly-rally"><?= $this->translate('Friendly rallies'); ?></a>
                </li>
                <li>
                    <a href="/league/show-table/id/<?= TK_Text::dotDash($user['Team']['league_name']); ?>"><?= $this->translate('League'); ?></a> 
                </li>
<!--                <li>
                    <a href="/rally/my-league-rallies"><?= $this->translate('My league rallies'); ?></a>
                </li>-->
                
            </ul>
        </li>
        <li>
            <a href="javascript:void(0)"><?= $this->translate('Market'); ?></a>
            <ul>
                <li>
                    <a href="/market/show-market"><?= $this->translate('Players'); ?></a> 
                </li>
                <li>
                    <a href="/market/show-car-market"><?= $this->translate('Cars',1); ?></a> 
                </li>
                <li>
                    <a href="/market/car-dealer"><?= $this->translate('Car dealer'); ?></a>
                </li>
                <li>
                    <a href="/market/player-monitor"><?= $this->translate('Player monitor'); ?></a> 
                </li>
                <li>
                    <a href="/market/car-monitor"><?= $this->translate('Car monitor'); ?></a> 
                </li>
                
            </ul>
        </li>
        <li>
            <a href="javascript:void(0)"><?= $this->translate('Community'); ?></a>
            <ul>
                <li>
                    <a href="/forum/show-forum"><?= $this->translate('Forum'); ?></a> 
                </li>
                <li>
                    <a href="#"><?= $this->translate('Top world list'); ?></a> 
                </li>
                <li>
                    <a href="#"><?= $this->translate('National ranking'); ?></a>
                </li>
                <li>
                    <a href="/search-users"><?= $this->translate('Search user'); ?></a> 
                </li>
            </ul>
        </li>
        <li>
            <a href="javascript:void(0)"><?= $this->translate('Premium');?></a>
            <ul>
                <li>
                    <a href="/account/premium"><?= $this->translate('My premium');?></a> 
                </li>
                <li>
                    <a href="/account/gold-membership"><?= $this->translate('Gold membership');?></a> 
                </li>
                <li>
                    <a href="/user/invite-to-game"><?= $this->translate('Invite friends');?></a> 
                </li>
                <li>
                    <a href="#"><?= $this->translate('Premium benefits');?></a> 
                </li>
                <li>
                    <a href="#"><?= $this->translate('Earn premium');?></a>
                </li>
            </ul>
        </li>
        <li>
            <a href="javascript:void(0)"><?= $this->translate('Help');?></a>
            <ul>
                <li>
                    <a href="/faq"><?= $this->translate('Faq');?></a> 
                </li>
                <li>
                    <a href="/privacy-policy"><?= $this->translate('Privacy Policy');?></a> 
                </li>
                <li>
                    <a href="/rules"><?= $this->translate('Rules');?></a>
                </li>
                <li>
                    <a href="/support"><?= $this->translate('Support');?></a> 
                </li>
            </ul>
        </li>
<!--        <li>
             <a href="/user/logout"><?= $this->translate('Log out');?></a>
        </li>-->
    </ul>
</div>