<script type="text/javascript">
  $(document).ready(function(){
 
        $("#tMenu > li > a").click(function (e) { // binding onclick
                var li = $(this).parent();
                var ul = $(this).next('ul');
                
                $('li.selected ul').slideUp(100);
	        $('li.selected ul').removeClass("selected");
	        if (li.hasClass('selected')) {
                    console.log('has');
	            ul.slideUp(200); // hiding popups
	            li.removeClass("selected");
	        } else {
                    console.log('nohas');
	            ul.slideDown(200); // hiding popups
	            li.addClass("selected");
	        }
	        e.stopPropagation();
	    });

  });
  
</script>

<div id="menu">
    <ul id="tMenu">
        <li>
            <a href="#">Office</a>
            <ul>
                <li>
                    <a href="/team/show-team/id/<?= $authenticatedUser['Team']['id']; ?>">Mój zespół</a>
                </li>
                <li>
                    <a href="/account/my-account">My account</a>
                </li>
                <li>
                    <a href="/account/my-people">Moi ludzie</a>
                </li>
<!--                <li>
                    <a href="/account/tactics">Taktyka</a>
                </li>-->
                <li>
                    <a href="/account/my-cars">Moje auta</a>
                </li>
                <li>
                    <a href="/account/sponsor">Sponsor</a>
                </li>
                <li>
                    <a href="/account/my-training-report">Raport z treningu</a> 
                </li>
                <li>
                    <a href="/account/my-finances">Moje finanse</a> 
                </li>
            </ul>
        </li>
        <li>
            <a href="#">My rallies</a>
            <ul>
                <li>
                    <a href="/rally/my-rallies">My rallies</a>
                </li>
                <li>
                    <a href="/rally/list-rally">Rallies</a>
                </li>
                <li>
                    <a href="/rally/list-friendly-rally">Friendly rallies</a>
                </li>
                <li>
                    <a href="/league/show-table">Moja tabela</a> 
                </li>
                
            </ul>
        </li>
        <li>
            <a href="#">Market</a>
            <ul>
                <li>
                    <a href="/market/my-cars-market">My cars on market</a> 
                </li>
                <li>
                    <a href="/market/show-car-market">Rynek samochodowy</a> 
                </li>
                <li>
                    <a href="/market/car-dealer">Salon samochodowy</a>
                </li>
                <li>
                    <a href="/market/show-market">Rynek transferowy</a> 
                </li>
                <li>
                    <a href="/market/my-players-market">My players on market</a> 
                </li>
                <li>
                    <a href="/market/my-player-offers">My player offers</a> 
                </li>
                <li>
                    <a href="/market/my-car-offers">My car offers</a> 
                </li>
                
            </ul>
        </li>
        <li>
            <a href="#">Community</a>
            <ul>
                <li>
                    <a href="/forum/show-forum">Forum</a> 
                </li>
                <li>
                    <a href="/market/show-car-market">Top world list</a> 
                </li>
                <li>
                    <a href="/market/car-dealer">National ranking</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#">Premium</a>
            <ul>
                <li>
                    <a href="/market/my-cars-market">Moje premium</a> 
                </li>
                <li>
                    <a href="/market/show-car-market">Korzysci z premium</a> 
                </li>
                <li>
                    <a href="/market/car-dealer">Zarob zlote monety</a>
                </li>
                <li>
                    <a href="/market/show-market">Zlote monety</a> 
                </li>
            </ul>
        </li>
        <li>
            <a href="#">Help</a>
            <ul>
                <li>
                    <a href="/market/my-cars-market">Faq</a> 
                </li>
                <li>
                    <a href="/market/show-car-market">Privacy Policy</a> 
                </li>
                <li>
                    <a href="/market/car-dealer">Rules</a>
                </li>
                <li>
                    <a href="/market/show-market">Support</a> 
                </li>
            </ul>
        </li>
        <li>
             <a href="/user/logout">Wyloguj</a>
        </li>
    </ul>
</div>