<script type="text/javascript">
  $(document).ready(function(){
 
        $("#tMenu > li > a").click(function (e) { // binding onclick
                var li = $(this).parent();
                var ul = $(this).next('ul');
                
                $('li.selected ul').slideUp(100);
	        $('li.selected ul').removeClass("selected");
	        if (li.hasClass('selected')) {
                    console.log('has');
	            ul.slideUp(200); // hiding popups
	            li.removeClass("selected");
	        } else {
                    console.log('nohas');
	            ul.slideDown(200); // hiding popups
	            li.addClass("selected");
	        }
	        e.stopPropagation();
	    });

  });
  
</script>

<div id="menu">
    <ul id="tMenu">
        <li>
            <a href="javascript:void(0)">Office</a>
            <ul>
                <li>
                    <a href="/team/show-team/id/<?= $authenticatedUser['Team']['id']; ?>">My team</a>
                </li>
                <li>
                    <a href="/account/my-account">My account</a>
                </li>
                <li>
                    <a href="/account/my-people">My people</a>
                </li>
<!--                <li>
                    <a href="/account/tactics">Taktyka</a>
                </li>-->
                <li>
                    <a href="/account/my-cars">My cars</a>
                </li>
                <li>
                    <a href="/account/sponsor">Sponsor</a>
                </li>
                <li>
                    <a href="/account/my-training-report">Training report</a> 
                </li>
                <li>
                    <a href="/account/my-finances">My finances</a> 
                </li>
            </ul>
        </li>
        <li>
            <a href="javascript:void(0)">My rallies</a>
            <ul>
                <li>
                    <a href="/rally/my-rallies">My rallies</a>
                </li>
                <li>
                    <a href="/rally/list-rally">Rallies</a>
                </li>
                <li>
                    <a href="/rally/my-friendly-rallies">My friendly rallies</a>
                </li>
                <li>
                    <a href="/rally/list-friendly-rally">Friendly rallies</a>
                </li>
                <li>
                    <a href="/league/show-table/id/<?= TK_Text::dotDash($user['Team']['league_name']); ?>">My league</a> 
                </li>
                
            </ul>
        </li>
        <li>
            <a href="javascript:void(0)">Market</a>
            <ul>
                <li>
                    <a href="/market/show-market">People market</a> 
                </li>
                <li>
                    <a href="/market/show-car-market">Car market</a> 
                </li>
                <li>
                    <a href="/market/car-dealer">Car dealer</a>
                </li>
                <li>
                    <a href="/market/my-players">My players</a> 
                </li>
                <li>
                    <a href="/market/my-player-offers">My player offers</a> 
                </li>
                <li>
                    <a href="/market/my-cars">My cars</a> 
                </li>
                <li>
                    <a href="/market/my-car-offers">My car offers</a> 
                </li>
                
            </ul>
        </li>
        <li>
            <a href="javascript:void(0)">Community</a>
            <ul>
                <li>
                    <a href="/forum/show-forum">Forum</a> 
                </li>
                <li>
                    <a href="/market/show-car-market">Top world list</a> 
                </li>
                <li>
                    <a href="/market/car-dealer">National ranking</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="javascript:void(0)">Premium</a>
            <ul>
                <li>
                    <a href="/market/my-cars-market">My premium</a> 
                </li>
                <li>
                    <a href="/market/show-car-market">Gold membership</a> 
                </li>
                <li>
                    <a href="/market/show-market">Premium benefits</a> 
                </li>
                <li>
                    <a href="/market/car-dealer">Earn premium</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="javascript:void(0)">Help</a>
            <ul>
                <li>
                    <a href="/market/my-cars-market">Faq</a> 
                </li>
                <li>
                    <a href="/market/show-car-market">Privacy Policy</a> 
                </li>
                <li>
                    <a href="/market/car-dealer">Rules</a>
                </li>
                <li>
                    <a href="/market/show-market">Support</a> 
                </li>
            </ul>
        </li>
        <li>
             <a href="/user/logout">Log out</a>
        </li>
    </ul>
</div>