<div class="col-md-12">
    <div class="col-md-10 mainPageBox leftMainPageBox">
        <?php if(isset($message)&&$message=='User not exists'){
            $this->showError('Error! User does not exists!');
        }
        else { ?>
        <h2>Password send</h2>
        <h4>We send you new password</h4>
        Check your email. <br />
        <?php } ?>
        <a href="/">Go back</a>
    </div>
    
</div>
<div class="clearfix"></div>
