<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Rules');?></h4>
    <div class="staticWrapper">
        Every FastRally user is obliged to abide by the following rules.
        The main purpose of following rules is to provide fair chances for every user to manage their teams.
        We actively monitor the game to ensure all our managers stick to these rules.
        Should you notice anyone failing to do so, we urge you to report your observations to our support team.
        Please let us deal with all such incidents – do not attempt to resolve them yourself or 
        expose them to the community.
        The punishment for anyone caught cheating will be far greater than any advantage 
        gained from the action and managers found guilty of serious foul play could lose control of their teams.

<ol>
<li><b>Do not open or use more than one account</b><br>
A specific account is assigned to each individual user when they register on FastRally. In order to prevent conflicts of interest and avoid breaching game rules, users are only permitted to hold one account and can only control a team belonging to that account. 

</li><li><b>Do not login to or take ownership of another account</b><br>
To avoid being suspected of managing more than one team, you must not log into any account other than your own. It is also forbidden to view any non-public team details without the owner’s or crew's permission, to hand over your account to someone else, to take permanent ownership of someone else’s account or register an account on behalf of someone else.</li>

<li><b>Do not try to gain an unfair advantage from the transfer market</b><br>
All transfers are monitored and we look into all irregularities, even after deals are completed. However we also welcome your feedback so, if you see a suspicious transfer, please report it to the support team. Should we consider a transfer to be unfair, we reserve the right to stop it and/or fine either the seller or buyer or both even when not breaking these rules.

<ol>
<li><b>No ‘price pushing’</b><br>
‘Price pushing’ is the practice of bidding for a player or car without having any intention of buying him, simply to raise his price.</li>

<li><b>No excessive bids</b><br>
Any bids for players / cars that are well over their market value will be investigated. If any suspicious circumstances are discovered, such transfers can be stopped, and/or one or both parties (seller and bidder) can be fined and/or suspended. We encourage you to inform the support team if you consider a bid for your player is excessively high.</li>

<li><b>What you see is what you get</b><br>
There is no guarantee that the skills of any player on the transfer market are improving. You should therefore always assume your target has reached his training limit. FastRally cannot be held responsible for any transfer deal based on incorrect information from the seller or another third party and you cannot make any claims against FastRally, the support team or the seller as a result.</li>

<li><b>Transfer deals are only complete when a player or car arrives at his new club</b><br>
Player and car transfers are only considered complete when a player arrives at his new club. This is due to the fact that, under certain circumstances, transfer deals can be reversed even after the deadline has passed.</li>

<li><b>No claims can be made against FastRally for losses incurred in the transfer market</b><br>
FastRally cannot be held responsible for any loss within the transfer market (e.g. a seller not receiving bids for a player or a buyer missing out on purchasing a target) resulting from technical issues, such as downtime or site instability or any non-technical reason. Depending upon the situation, we may choose to allow more time for affected transfer deals but this is in no way guaranteed.</li>
</ol> </li>

<li><b>Show sportsmanlike behaviour</b><br>
Fixing rallies is expressly forbidden. You are not allowed to try to aid another team by deliberately losing a rally by e.g. joining rally with significantly weaker crew or use purposely using worse rally setings. Using any such methods in order to gain an unfair advantage for yourself or someone else can be considered cheating.</li>

<li><b>Keep your account active</b><br>
Not logging in to your account can have several effects on your team:<br>
<ol>
<li>If your account shows no login for 35 consecutive days it will be considered inactive. This inactivity may lead to demotion after a seasons end.<br>
You can lose your current team and we may assign a new team when you next become active.</li>
<li>Inactive teams, that are not accessed after another 35 days will be deleted.</li>
<li>Players / cars from teams that are considered inactive may be transfer listed or deleted. </li></ol><br>
There is no appeal against actions taken in respect of inactive teams.<br><br>

</li>
<li><b>Do not exploit bugs to gain an unfair advantage</b><br>
If you discover any errors in the code or in the system in general (bugs), you must not attempt to benefit from them. Instead, please report these to the support team. Please note that formations and tactical adjustments are not considered bugs. Exploiting bugs in our payment system to illegally obtain Power Tokens, digital items or other services can lead to immediate suspension and legal claims against you.</li>

<li><b>Be honest when dealing with our support team</b><br>
If you have broken one or more of the above rules, the best and most honourable thing to do is to admit it to our support team. Should your team be suspended, you must also answer any questions they have fully and honestly. The more honest you are, the more sympathetic we are likely to be when considering your case and the greater your chances of receiving a "second chance". By the same token, the longer any cheating continues, the worse the punishment will be.</li>
<li><b>Manage your team finances properly</b><br>
Bear in mind that negative team balance for 5 consecutive weeks will mean that your team is bankrupt.This will result in following actions: :<br>
<ol>
<li>You will lose your current team and we may assign a new team when you next become active.</li>
<li>Players / cars from teams that are considered inactive may be transfer listed or deleted. </li></ol><br>
There is no appeal against actions taken in respect of bankrupt teams.<br><br>

</li>
</ol>

The management of FastRally, and its representatives, have the right to suspend a team or ban a user if it considers any of the above rules to have been broken. FastRally also has the right to take action for other reasons not mentioned here if it is considered necessary. In any case, ManagerZone always has the final say so you are advised not to test the limits of the rules. <br><br>
In cases where suspension is considered too harsh, we have the right to take other appropriate action. If you consider yourself innocent of any charge, you are welcome to appeal against the decision by contacting the support team from the e-mail address you used when you registered your team. Please note that, in order to uphold the rules and manage the game, FastRally Team has access to non-public team data and can grant such access to our representatives (e.g. partners, admins). 
<br><br>
Possible punishments:
<ul>
<li>Warning</li>
<li>Temporary transfer ban</li>
<li>Team fine</li>
<li>Removal of transferred player/car</li>
<li>Tea, closure</li>
<li>Account suspension</li>
</ul>
<br><br>
<center><b>Play tough but play fair!</b></center>
<br><br>
<i>The forum rules apply to all in-game communications. As the contents of these rules can be presented in several languages, English is always the deciding language in cases of translation differences. 
<br><br></i></div>
</div>