<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>Team name</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($users as $user):  ?>
        <tr>
            <td><?php echo $user['id']; ?></td>
            <td><a href="/team/show-team/id/<?php echo $user['Team']['id']; ?>"><?php echo $user['username']; ?></a></td>
            <td><?php echo $user['Team']['name']; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<form action="/index/search-friends" method="POST">
    <input type="text" name="username" id="username" placeholder="Enter user name" />
    <input type="submit" value="submit" name="submit" />
</form>