<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Search Users'); ?></h4>
    <div class='staticWrapper'>
        
        <form action="/search-users" method="POST">
            <div class="col-md-6">
                <?= $form->getElement('username')->renderElement(); ?>
                <!--<input class="form-control" type="text" name="username" id="searchUsername" placeholder="Enter user name" />-->
            </div>
            <div class="clearfix"></div>
            
                <?= $form->getElement('submit')->renderElement(); ?>
            <!--<input class="btn myBtn searchUsersBtn" type="submit" value="Search" name="submit" />-->
        </form>
        <?php
        if(isset($users)&&!is_null($users)){
        if(isset($users)&&count($users)>0){ ?>
        <table class="table searchTable">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Username</th>
                    <th>Team name</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($users as $user):  ?>
                <tr>
                    <td><?php echo $user['id']; ?></td>
                    <td><a href="/team/show-team/<?php echo $user['Team']['id']; ?>"><?php echo $user['username']; ?></a></td>
                    <td><?php echo $user['Team']['name']; ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php }
        else{
            echo "No results found";
        }
        }
        ?>
    </div>
</div>
 <script>
  $(function() {
    $( "#searchUsername" ).autocomplete({
      source: function( request, response ) {
        $.ajax({
          url: "/user/find-user",
          dataType: "json",
          type: "get",
          data: {
            q: request.term,
          },
          success: function( data ) {
            response( data );
          }
        });
      },
      minLength: 3
    });
  });
  </script>