<div class="mainUserBox boxFriends">
    <h4 class="boxHeader"><?= $this->translate('Friends'); ?></h4>
    <?php if(isset($friends)): ?>
    <div class="subboxFriends">
        <ul>
        <?php foreach($friends as $friend): ?>
                <?php 
                if($friend['user_id']==$user['id']){
                    if(strtotime($friend['UserFriends']['last_active'])>strtotime("-2 minutes")){
                        echo "<li class='active'>";
                    }
                    else{
                        echo "<li>";
                    }

//                    echo '<img src="http://placehold.it/20x20" />';
                    echo '<a href="/team/show-team/id/'.$friend['UserFriends']['Team']['id'].'">'.TK_Text::truncate($friend['UserFriends']['username'],15).'</a>'; 
                    echo "<i class='fa fa-circle-thin'></i>";
                    echo '<a href="/user/show-message-box/id/'.$friend['UserFriends']['id'].'#sendMessage"><i class="fa fa-envelope-o"></i></a>';
                }
                else{
                    if(strtotime($friend['User']['last_active'])>strtotime("-2 minutes")){
                        echo "<li class='active'>";
                    }
                    else{
                        echo "<li>";
                    }
//                    echo '<img src="http://placehold.it/20x20" />';

                    echo '<a href="/team/show-team/id/'.$friend['User']['Team']['id'].'">'.TK_Text::truncate($friend['User']['username'],15).'</a>'; 
                    echo "<i class='fa fa-circle-thin'></i>";
                    echo '<a href="/user/show-message-box/id/'.$friend['User']['id'].'#sendMessage"><i class="fa fa-envelope-o"></i></a>';
                }
                ?>
            </li>

        <?php endforeach; ?>
        </ul>
    </div>
    <?php endif; ?>
</div>