   
    <script>
        $(document).ready(function(){
            var position = $('.messageIcons').position().left;
            var new_position = position-80;
           $('.messageIcons').css('left',new_position);
           
           $('.messageIconWrapper').click(function(){
               var button = $(this);
               var element = $(this).attr('rel');
               if($('#'+element).is(':visible')){
                    $('#'+element).fadeOut(500);
               }
               else{
                    $('#'+element).fadeIn(1000);
                }
               
               if(element == 'mainNotificationMessageBox'){
                   button.removeClass('active');
                   $.ajax({
                       url: "/user/read-notifications"
                   });
               }
               
           });
           
           $('.inviteLink').click(function(){
               var element = $(this).attr('rel');
                   $.ajax({
                       url: "/user/delete-notification/"+element
                   });
               
           });
        });
    </script>
<div class='messageIcons'>
    <?php if($hasRallyNow): ?>
        <a href='/rally/show-rally/<?= $hasRallyNow['slug']; ?>' class='messageIconWrapper active'  title='<?= $this->translate('Rally in progress'); ?>'>
            <i class='fa fa-car'></i>
        </a>
    <?php else: ?>
        <a href='#' class='messageIconWrapper' title='<?= $this->translate('No rally in progress'); ?>'>
            <i class='fa fa-car'></i>
        </a>
    <?php endif; ?>
    <a href='javascript:void(0)' class='messageIconWrapper <?= ($notReadedNotifications>0)?"active":""; ?>' rel='mainNotificationMessageBox' title='Notification'>
        <i class='fa fa-info-circle'></i>
    </a>
    <?php if($hasFriendlyInvitation): ?>
        <a href='/rally/list-friendly-rally/' class='messageIconWrapper active' title='<?= $this->translate('Pending friendly invitations');?>'>
            <i class='fa fa-user-plus'></i>
        </a>
    <?php else: ?>
        <a href='#' class='messageIconWrapper' title='<?= $this->translate('No friendly invitations'); ?>'>
            <i class='fa fa-user-plus'></i>
        </a>
    <?php endif; ?>
    <a href='/user/show-message-box/<?= $authenticatedUser['id']; ?>' class='messageIconWrapper <?php echo count($notReadedMessages)>0?'active':''; ?>'>
        <i class='fa fa-envelope-o'></i>
    </a>
    <a href='#' class='messageIconWrapper premiumIconWrapper'>
        <?= (int)$authenticatedUser['premium']; ?> <img class="coin" src="/images/layout/coin.png">
    </a>
    
    <div class="clearfix"></div>
    <span class="cashInfo">
        <?= $this->translate('Balance'); ?>: <strong class="<?php echo ($authenticatedUser['Team']['cash']>=0)?'green':''; ?> <?php echo ($authenticatedUser['Team']['cash']<0)?'red':''; ?>"><?= "$".number_format($authenticatedUser['Team']['cash']); ?></strong>
    </span>
</div>

<div class="mainUserBox boxNotification mainPageNotification" id='mainNotificationMessageBox'>
    <h4 class="boxHeader"><?= $this->translate('Message box'); ?></h4>
    <div class="boxNotificationInner">
        <?php foreach($notifications as $notification): 
                ?>
        <div>
            <span><?= TK_Text::timeFormat($notification['created_at'], 'd/m/y'); ?></span>
            <?= $notification['message']; ?>
            <div class="clearfix"></div>
            <?php // user friend invite
            if($notification['type']==2&&!empty($notification['link'])){ ?>
                <a href="/user/accept-invite/<?= $notification['link']; ?>" class="pull-left green inviteLink" rel="<?= $notification['id']; ?>">Accept <i class="fa fa-thumbs-up"></i></a>
                <a href="/user/reject-invite/<?= $notification['link']; ?>" class="pull-right red inviteLink" rel="<?= $notification['id']; ?>">Reject <i class="fa fa-thumbs-down"></i></a>
            <?php
            }
            ?>
        </div>
         <?php endforeach; ?>
    </div>
</div>