<div class="mainUserBox boxFriends">
    <h4 class="boxHeader"><?= $this->translate('Friends'); ?></h4>
    <?php if(isset($friends)): ?>
    <div class="subboxFriends">
        <ul>
        <?php foreach($friends as $friend): ?>
                <?php 
                if($friend['user_id']==$user['id']){
                    if(!empty($friend['UserFriends']['last_active'])&&strtotime($friend['UserFriends']['last_active'])>strtotime("-5 minutes")){
                        echo "<li class='active'>";
                    }
                    else{
                        echo "<li>";
                    }

                    echo '<a href="/team/show-team/'.$friend['UserFriends']['Team']['id'].'">'.TK_Text::truncate($friend['UserFriends']['username'],15).'</a>'; 
                    
                    if(!empty($friend['UserFriends']['last_active'])&&strtotime($friend['UserFriends']['last_active'])>strtotime("-5 minutes")){
                        echo "<img src='/images/layout/user-active.png' alt='User active' title='User active' />";
                    }
                    else{
                        echo "<img src='/images/layout/user-inactive.png' alt='User inactive' title='User inactive' />";
                    }
                    echo '<a href="/user/show-message-box/'.$friend['UserFriends']['id'].'#sendMessage"><i class="fa fa-envelope-o"></i></a>';
                    }
                else{
                    if(!empty($friend['User']['last_active'])&&strtotime($friend['User']['last_active'])>strtotime("-5 minutes")){
                        echo "<li class='active'>";
                    }
                    else{
                        echo "<li>";
                    }
//                    echo '<img src="http://placehold.it/20x20" />';

                    echo '<a href="/team/show-team/'.$friend['User']['Team']['id'].'">'.TK_Text::truncate($friend['User']['username'],15).'</a>'; 
                    
                    if(!empty($friend['User']['last_active'])&&strtotime($friend['User']['last_active'])>strtotime("-5 minutes")){
                        echo "<img src='/images/layout/user-active.png' alt='User active' title='User active' />";
                    }
                    else{
                        echo "<img src='/images/layout/user-inactive.png' alt='User inactive' title='User inactive' />";
                    }
                    echo '<a href="/user/show-message-box/'.$friend['User']['id'].'#sendMessage"><i class="fa fa-envelope-o"></i></a>';
                }
                
                ?>
                <a onclick="if(!confirm('Are you sure you want to remove this user from your friendlist?')){ return false}" href="/user/remove-friend/<?= $friend['id']; ?>"><i class="fa fa-trash-o"></i></a>
                
            </li>

        <?php endforeach; ?>
        </ul>
    </div>
    <?php endif; ?>
</div>