<style>
    .messageIcons{
        position:fixed;
        z-index:100000;
        /*left:-10px;*/
    }
    .messageIconWrapper{
        display:block;
        text-align:center;
        margin:5px 0px;
    }
    .messageIconWrapper{
        font-size:16px;
    }
    .mainPageNotification{
        display:none;
    }
    .messageIconWrapper.active i{
        color:yellow;
    }
    .premiumIconWrapper{
        font-size:12px;
    }
    </style>
    
    <script>
        $(document).ready(function(){
            var position = $('.messageIcons').position().left;
            var new_position = position-80;
           $('.messageIcons').css('left',new_position);
           
           $('.messageIconWrapper').click(function(){
               var element = $(this).attr('rel');
               if($('#'+element).is(':visible')){
                    $('#'+element).fadeOut(500);
               }
               else{
                    $('#'+element).fadeIn(1000);
                }
               
               
           });
           
        });
    </script>
<div class='messageIcons'>
    <?php if($hasRallyNow): ?>
        <a href='/rally/show-rally/slug/<?= $hasRallyNow['slug']; ?>' class='messageIconWrapper active'  title='Rally in progress'>
            <i class='fa fa-car'></i>
        </a>
    <?php else: ?>
        <a href='#' class='messageIconWrapper' title='No rally in progress'>
            <i class='fa fa-car'></i>
        </a>
    <?php endif; ?>
    <a href='javascript:void(0)' class='messageIconWrapper' rel='mainNotificationMessageBox' title='Notification'>
        <i class='fa fa-envelope-o'></i>
    </a>
    <?php if($hasFriendlyInvitation): ?>
        <a href='/rally/list-friendly-rally/' class='messageIconWrapper active' title='Pending friendly invitations'>
            <i class='fa fa-user-plus'></i>
        </a>
    <?php else: ?>
        <a href='#' class='messageIconWrapper' title='No friendly invitations'>
            <i class='fa fa-user-plus'></i>
        </a>
    <?php endif; ?>
    <a href='#' class='messageIconWrapper premiumIconWrapper'>
        <?= (int)$authenticatedUser['premium']; ?> <img class="coin" src="/images/layout/coin.png">
    </a>
</div>

<div class="mainUserBox boxNotification mainPageNotification" id='mainNotificationMessageBox'>
    <h4 class="boxHeader">Message box</h4>
    <div class="boxNotificationInner">
        <?php foreach($notifications as $notification): 
                ?>
        <div>
            <span><?= TK_Text::timeFormat($notification['created_at'], 'd/m/y'); ?></span>
            <?= $notification['message']; ?>
        </div>
         <?php endforeach; ?>
    </div>
</div>