<?php if(isset($_GET['msg'])){
        if($_GET['msg']=="too fast"){
            $this->showError($this->translate('You can post once every 30 seconds'));
        }
        elseif($_GET['msg']=="enquiry send"){
            $this->showSuccess($this->translate('Your enquiry has been sent to support. We will reply as soon as possible.'));
        }
    }
    ?>
<div class="mainUserBox showForumWrapper">
    <h4 class="boxHeader"><?= $this->translate('Support'); ?></h4>
    <div class='staticWrapper'>
        <div class="supportWrapper">
            <h5>Please fill in the contact form to get our support.</h5>
            <form method="POST">
                <label>Choose support category</label>
                <?php echo $form->getElement('section')->renderElement(); ?>
                <label>Please provide a clear description of your issue</label>
                <?php echo $form->getElement('content')->renderElement(); ?>
                <?php // echo $form->getElement('active')->renderElement(); ?>
                <?php echo $form->getElement('submit')->renderElement(); ?>
            </form>
        </div>
    </div>
</div>