<?php

/**
 * Forum_Model_Doctrine_FavouriteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Forum_Model_Doctrine_FavouriteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Forum_Model_Doctrine_FavouriteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Forum_Model_Doctrine_Favourite');
    }
}