<?php

/**
 * Forum_Model_Doctrine_Thread
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Forum_Model_Doctrine_Thread extends Forum_Model_Doctrine_BaseThread
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User_Model_Doctrine_User as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

    }
}