<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>

<div class="row">
	<div class="col-md-12">
		<!-- BEGIN VALIDATION STATES-->
		<div class="portlet box purple">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i>Add sponsor
				</div>
				<div class="tools">
					<a href="javascript:;" class="collapse" data-original-title="" title="">
					</a>
					<a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title="">
					</a>
					<a href="javascript:;" class="reload" data-original-title="" title="">
					</a>
					<a href="javascript:;" class="remove" data-original-title="" title="">
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form action="" id="form_sample_1" class="form-horizontal" method="POST" enctype="multipart/form-data">
					<div class="form-body">
                                                <?php echo $form->getElement('id')->renderAdminElement(); ?>
                                                <?php echo $form->getElement('name')->renderAdminElement(); ?>
						<?php echo $form->getElement('description')->renderAdminElement(); ?>
						<?php echo $form->getElement('active')->renderAdminElement(); ?>
                                                <input type="hidden" name="form_send" value="1" />
					
                                                <div class="form-group">
                                                        <label class="control-label col-md-3">Logo</label>
                                                        <div class="col-md-3">
                                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                                        <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
                                                                        </div>
                                                                        <div>
                                                                                <span class="btn default btn-file">
                                                                                <span class="fileinput-new">
                                                                                Select image </span>
                                                                                <span class="fileinput-exists">
                                                                                Change </span>
                                                                                <input type="file" name="logo">
                                                                                </span>
                                                                                <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput">
                                                                                Remove </a>
                                                                        </div>
                                                                </div>
                                                        </div>
                                                </div>
					</div>
                                    
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="submit" class="btn green">Submit</button>
								<button type="submit" name="saveAndAddNew" class="btn blue"><i class="fa fa-plus"></i> Save and add new </button>
								<button type="submit" name="saveAndStay" class="btn purple"><i class="fa fa-edit"></i> Save and stay</button>
								<button type="button" class="btn default">Cancel</button>
							</div>
						</div>
					</div>
				</form>
				<!-- END FORM-->
			</div>
		</div>
		<!-- END VALIDATION STATES-->
	</div>
</div>