<?php 
if(isset($_GET['msg'])&&$_GET['msg']=="cant afford"){
    $this->showError("Sorry. You don't have enough money to buy this car.");
}
?>
<div class="mainUserBox myCarsBox">
    <h4 class="boxHeader">Car dealer</h4>
    <div class="myCars">
        <?php foreach($carsForSale as $car): ?>
            <div class="carCard carDealer">

                <?php if(isset($car['photo'])&&strlen($car['photo'])){ ?>
                    <img src="/media/cars/<?php echo $car['photo']; ?>" alt="<?php echo $car['name']; ?>" class="carCardPhoto" />
               <?php } 
                    else{ ?>
                        <img src="http://dummyimage.com/340x220&amp;text=No+photo" class="carCardPhoto" />
                <?php } ?>
                <strong><?= $car['name']; ?></strong>


                <div class="col-md-6">

            <!--    Car name: <?php echo $car['name']; ?> <a href="javascript:void(0)" id="btnChangeCarNameButton1">change name</a><br />
                <div class="changeCarName" id="changeCarName1">
                    <?php // echo $formCar1->renderForm(); ?>
                </div>-->
                    
                    <div class="carParameters">
                        <table>
                           <tr>
                               <td>brand:</td>
                               <td><?php echo $car['name']; ?></td>
                           </tr>
                           <tr>
                               <td>capacity</td>
                               <td><?php echo $car['capacity'];?></td>
                           </tr>
                           <tr>
                               <td>horse power</td>
                               <td><?php echo $car['horsepower'];?></td>
                           </tr>
                           <tr>
                               <td>v-max</td>
                               <td><?php echo $car['max_speed'];?></td>
                           </tr>
                           <tr>
                               <td>acceleration</td>
                               <td><?php echo $car['acceleration'];?></td>
                           </tr>

                       </table>
                   </div>
                    <div class="clearfix"></div>
                <div class="carBtn">
                    Car price : <?= $car['price']; ?>$<br />
                    <a class='btn' href="/market/buy-car/id/<?php echo $car['id']; ?>"><i class="fa fa-shopping-cart"></i> Buy this car</a>

                </div>

                </div>
                <div class="clearfix"></div>
            </div>
        <?php endforeach; ?>
    </div>
</div>