<div class="mainUserBox myCarsBox">
    <h4 class="boxHeader"><?= $this->translate('Show car offer')." #".$offer['id']; ?></h4>
    <?php
        if(isset($message)){
            if(!$message['status'])
                $this->showError($message['message']);
            else
                $this->showSuccess($message['message']);
        }

        if(isset($_GET['msg'])){
            if($_GET['msg']=="bid placed")
                $this->showSuccess($this->translate('Congratulations. You hold the highest bid.'));
            elseif($_GET['msg']=="not highest")
                $this->showError($this->translate('Your bid must be greater than the highest one.'));
            elseif($_GET['msg']=="already highest")
                $this->showError($this->translate('You already hold the highest bid.'));
            elseif($_GET['msg']=="finished")
                $this->showError($this->translate('Sorry, the auction has been finished.'));
            elseif($_GET['msg']=="greater than asking")
                $this->showError($this->translate('Offer must be greater than asking price.'));
            elseif($_GET['msg']=="no money")
                $this->showError($this->translate('Sorry, You don\'t have enough money.'));
            elseif($_GET['msg']=="not enough money")
                $this->showError($this->translate('Sorry, You don\'t have enough money for all of your bids'));
            elseif($_GET['msg']=="10 greater")
                $this->showError($this->translate('Your offer must be 10% greater than the highest offer.'));

            
           
        }
    ?>
    <div class='col-md-12'>
        <div class="myPeople peopleList driverList carMarketList">
            <?php $car = $offer['Car']; 
            ?>
            <ul>
                <li class="active"><?php echo $car['name']; ?> 

                    <?php if($car['Team']['id']!=$authenticatedUser['Team']['id']): ?>
                            <a class="btn myBtn bidPlayer bidCar" data-toggle="modal" data-target="#bidPlayer" data-name="<?= $car['name']; ?>" rel="<?= $offer['id']; ?>"><?= $this->translate('Bid car'); ?></a>
                    <?php endif; ?>
                </li>
            </ul>
            <div class="carCard carMarketCard col-md-8 active peopleMarketCard mr0">

                <div class="col-md-7">

                    <?= TK_Helper::showCarParameters($car,$offer['Car']['Team']); ?>

                    <div class="clearfix"></div>
                </div>

                <div class='col-md-5 mr0'>
                    <?php if(isset($car['Model']['photo'])&&strlen($car['Model']['photo'])){ ?>
                        <img src="/media/cars/<?php echo $car['Model']['photo']; ?>" alt="<?php echo $car['Model']['name']; ?>" class="carCardPhoto" />
                    <?php } 
                        else{ ?>
                            <img src="http://dummyimage.com/340x220&amp;text=No+photo"  class="carCardPhoto" />
                    <?php } ?>
                </div>

            <div class='clearfix'></div>
            </div>
            <div class='col-md-1'></div>
            <div class="col-md-3 peopleMarketSmallCard">

                <table>
                    <tr>
                        <th><?= $this->translate('Highest bid'); ?>: </th>
                    </tr>
                    <tr>
                        <td>
                            <?php
                                if(isset($offer['Bids'][0])&&$offer['Bids'][0]['active']){
                                    echo "$".(int)$offer['Bids'][0]['value']." - ".$offer['Bids'][0]['Team']['name']; 
                                }
                                else
                                    echo $this->translate("no offers");
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Asking price'); ?>:</th>
                    </tr>
                    <tr>
                        <td><?= $offer['asking_price']; ?>$</td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Auction finish'); ?>: </th>
                    </tr>
                    <tr>
                        <td>
                            <?php echo TK_Text::timeFormat($offer['finish_date'],'d/m/y H:i'); ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('Other offers'); ?>: </th>
                    </tr>
                    <tr>
                        <td>
                            <?php foreach($offer['Bids'] as $key => $bid):
                                if($bid['active']==0)
                                    continue;

                                if($key==0)
                                    continue;
                                if($key>3)
                                    break;

                                echo "$".$bid['value']." - ".$bid['Team']['name']."<br />"; 
                            endforeach; ?>
                        </td>
                    </tr>
                </table>
            </div>
            <div class='clearfix'></div>
        </div>
    </div>
</div>

<div id="bidCar" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <form method="POST" action="/market/bid-car">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"><?= $this->translate('Bid car'); ?> <span id="bidCarName"></span></h4>
                </div>
                <div class="modal-body">
                    <label for="asking_price"><?= $this->translate('Your offer'); ?></label>
                    <?php echo $form->getElement('bid')->renderElement(); ?>
                    <?php echo $form->getElement('offer_id')->renderElement(); ?>
                </div>
                <div class="modal-footer">
                    <?php echo $form->getElement('submit')->renderElement(); ?>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->translate('Close'); ?></button>
                </div>
            </div>
        </form>

    </div>
</div>


<script>
    $(document).ready(function(){
        
        $('.bidCar').click(function(){
           var rel = $(this).attr('rel');
           $('#offer_id').val(rel);
           $('#bidCarName').html($(this).attr('data-name'));
        });
    });
</script>