<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('People offer'); ?></h4> 
    <?php
        if(isset($message)){
            if(!$message['status'])
                $this->showError($message['message']);
            else
                $this->showSuccess($message['message']);
        }

        if(isset($_GET['msg'])){
            if($_GET['msg']=="bid placed")
                $this->showSuccess($this->translate('Congratulations. You hold the highest bid.'));
            elseif($_GET['msg']=="not highest")
                $this->showError($this->translate('Your bid must be greater than the highest one.'));
            elseif($_GET['msg']=="already highest")
                $this->showError($this->translate('You already hold the highest bid.'));
            elseif($_GET['msg']=="finished")
                $this->showError($this->translate('Sorry, the auction has been finished'));
            elseif($_GET['msg']=="greater than asking")
                $this->showError($this->translate('Offer must be greater than asking price'));
            elseif($_GET['msg']=="no money")
                $this->showError($this->translate('Sorry, You don\'t have enough money.'));
            elseif($_GET['msg']=="not enough money")
                $this->showError($this->translate('Sorry, You don\'t have enough money for all of your bids'));

            
           
        }
    ?>
    <div class="myPeople peopleList driverList col-md-12">
        
        <?php $person = $offer['Player']; ?>
        <ul>
            <li class="active"><?php echo $person['last_name']." ".$person['first_name']; ?> </li>
           
                <?php if($person['Team']['id']!=$authenticatedUser['Team']['id']): ?>
                    <li class="bidPlayerWrapper">
                        <a class="btn myBtn bidPlayer" data-toggle="modal" data-target="#bidPlayer" data-name="<?= $person['last_name']." ".$person['first_name']; ?>" rel="<?= $offer['id']; ?>"><?= $this->translate('Bid player'); ?></a>
                    </li>
             <?php endif; ?>
        </ul>
        <div class="peopleMarketCard peopleCard col-md-8 active">
                
                <div class="col-md-5 peopleLeft peopleMarketLeft">
                    <table>
                        <tr>
                            <td>
                                <?= $this->translate('Team'); ?>:
                            </td>
                            <td>
                                <?php echo $person['Team']['name']; ?><br />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->translate('Job'); ?>:
                            </td>
                            <td>
                                <?= $person['job']; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->translate('Age'); ?>:
                            </td>
                            <td>
                                <?php echo $person['age']; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->translate('Value'); ?>:
                            </td>
                            <td>
                                <?php echo $person['value']; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->translate('Salary'); ?>:
                            </td>
                            <td>
                                <?php echo $person['salary']; ?>
                            </td>
                        </tr>
                    </table>
                     
                </div>
            
                <div class="col-md-7 peopleRight peopleMarketRight">
                    <?= TK_Helper::showPersonDetails($person,false); ?>
                </div>
        </div>
            <div class='col-md-1'></div>
        <div class="col-md-3 peopleMarketSmallCard">
            <table>
                <tr>
                    <th><?= $this->translate('Highest bid');?>: </th>
                </tr>
                <tr>
                    <td>
                        <?php
                            if(isset($offer['Bids'][0])&&$offer['Bids'][0]['active']){
                                echo (int)$offer['Bids'][0]['value']."$ - ".$offer['Bids'][0]['Team']['name']; 
                            }
                            else
                                echo $this->translate("no offers");
                        ?>
                    </td>
                </tr>
                <tr>
                    <th><?= $this->translate('Asking price'); ?>:</th>
                </tr>
                <tr>
                    <td><?= $offer['asking_price']; ?>$</td>
                </tr>
                <tr>
                    <th><?= $this->translate('Auction finish'); ?>: </th>
                </tr>
                <tr>
                    <td>
                        <?php echo TK_Text::timeFormat($offer['finish_date'],'d/m/y H:i'); ?>
                    </td>
                </tr>
                <tr>
                    <th><?= $this->translate('Other offers'); ?>: </th>
                </tr>
                <tr>
                    <td>
                        <?php foreach($offer['Bids'] as $key => $bid):
                            if($bid['active']==0)
                                continue;

                            if($key==0)
                                continue;
                            if($key>3)
                                break;

                            echo $bid['value']."$ - ".$bid['Team']['name']."<br />"; 
                        endforeach; ?>
                    </td>
                </tr>
            </table>            
        </div>
    </div>
    <div class="clearfix"></div>
</div>



<div id="bidPlayer" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <form method="POST" action="/market/bid-player">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"><?= $this->translate('Bid player'); ?> <span id="bidPlayerName"></span></h4>
                </div>
                <div class="modal-body">
                    <label for="asking_price"><?= $this->translate('Your offer'); ?></label>
                    <?php echo $form->getElement('bid')->renderElement(); ?>
                    <?php echo $form->getElement('offer_id')->renderElement(); ?>
                </div>
                <div class="modal-footer">
                    <?php echo $form->getElement('submit')->renderElement(); ?>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->translate('Close'); ?></button>
                </div>
            </div>
        </form>

    </div>
</div>


<script>
    $(document).ready(function(){
        
        $('.bidPlayer').click(function(){
           var rel = $(this).attr('rel');
           $('#offer_id').val(rel);
           $('#bidPlayerName').html($(this).attr('data-name'));
        });
    });
</script>