<div class="mainUserBox myPeopleWrapper">
    <h4 class="boxHeader">People market</h4> 
    <div class="myPeople">
        <?php foreach($marketOffers as $offer):
        $person = $offer['Player'];
        ?>
        <div class="peopleCard">
            <strong><?php echo $person['last_name']." ".$person['first_name']; ?></strong><br />
                <div class="col-md-5 peopleLeft">
                    <table>
                        <tr>
                            <td>
                                Team:
                            </td>
                            <td>
                                <?php echo $person['Team']['name']; ?><br />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Job:
                            </td>
                            <td>
                                <?php
                                    if($person['job']=="driver"):
                                        echo '<img src="/images/layout/driving-wheel.png" title='.$person['job'].'  lt='.$person['job'].' />';
                                    else:
                                        echo '<i class="fa fa-book" title='.$person['job'].' ></i>';
                                    endif;
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Age:
                            </td>
                            <td>
                                <?php echo $person['age']; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Value:
                            </td>
                            <td>
                                <?php echo $person['value']; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Salary:
                            </td>
                            <td>
                                <?php echo $person['salary']; ?>
                            </td>
                        </tr>
                    </table>
                     
                </div>
            
                <div class="col-md-7 peopleRight">
                    <?php if($person['job'] == "driver"): ?>
                    <table>
                        <tr>
                            <td>Composure</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'composure'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Speed</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'speed'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Regularity</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'regularity'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Reflex</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'reflex'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Driving on gravel</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'on_gravel'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Driving on tarmac</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'on_tarmac'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Driving on snow</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'on_snow'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Driving in rain</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'in_rain'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Talent</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'talent'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Form</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'form'); ?>
                            </td>
                        </tr>
                    </table>
                    <?php else: ?>
                    <table>
                        <tr>
                            <td>Composure</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'composure'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Dictate rhytm</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'dictate_rhytm'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Diction</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'diction'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Route description</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'route_description'); ?>
                            </td>
                        </tr>

                        <tr>
                            <td>Talent</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'talent'); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>Form</td>
                            <td>
                                <?php TK_Helper::displayPeopleSkillsOnList($person, 'form'); ?>
                            </td>
                        </tr>
                    </table>
                    <?php endif; ?>

                </div>
            <div class="clearfix"></div>
            <div class="col-md-6">
                <table>
                    <tr>
                        <td>Asking price:</td>
                        <td><?= $offer['asking_price']; ?>$</td>
                    </tr>
                    <tr>
                        <td>Highest bid </td>
                        <td>
                            <?php
                                if(isset($offer['Bids'][0])&&$offer['Bids'][0]['active']){
                                    echo (int)$offer['Bids'][0]['value']."$ - ".$offer['Bids'][0]['Team']['name']; 
                                }
                                else
                                    echo "brak ofert";
                            ?>
                        </td>
                    </tr>
                </table>
                <!--<h3>Oferty</h3>-->
                Highest bid: 
                
                <span>Koniec aukcji - <?php echo TK_Text::timeFormat($offer['finish_date'],'d/m/Y H:i:s'); ?></span>
                <br /><br />
                Pozostałe oferty<br />
                <?php foreach($offer['Bids'] as $key => $bid):
                    if($bid['active']==0)
                        continue;

                    if($key==0)
                        continue;
                    if($key>5)
                        break;

                    echo $bid['value']."$ - ".$bid['Team']['name']."<br />"; 
                endforeach; ?>
            </div>
            <div class="clearfix"></div>
        </div>
        <? /*
    <div class="col-md-4">
        Cena wywoławacza : <?= $offer['asking_price']; ?><br />
        <h3>Oferty</h3>
        Najwyższa oferta 
        <strong><?php
        if(isset($offer['Bids'][0])&&$offer['Bids'][0]['active']){
            echo (int)$offer['Bids'][0]['value']."$ - ".$offer['Bids'][0]['Team']['name']."<br />"; 
        }
        else
            echo "brak ofert";
        ?></strong>
        <span>Koniec aukcji - <?php echo TK_Text::timeFormat($offer['finish_date'],'d/m/Y H:i:s'); ?></span>
        <br /><br />
        Pozostałe oferty<br />
        <?php /*foreach($offer['Bids'] as $key => $bid):
            if($bid['active']==0)
                continue;

            if($key==0)
                continue;
            if($key>5)
                break;

            echo $bid['value']."$ - ".$bid['Team']['name']."<br />"; 
        endforeach;  ?>
        <br />
        <?php // if($player['Team']['id']!=$user['Team']['id']): ?>
        <a href="/market/bid-player/id/<?php echo $offer['id']; ?>">Zalicytuj</a>
        <?php // endif; ?>
    </div>-->
    <div class='clearfix'></div>
    <?php */ endforeach; ?>
    </div>
</div>