<div class="mainUserBox boxTransfer">
    <h4 class="boxHeader"><?= $this->translate('Transfers'); ?></h4>
    <?php if(!$authenticatedUser['gold_member']){ ?>
        <div class="goldOverlay">
            <a href="#">
                <img src="/images/layout/gc_big.png" />
            </a>
        </div>
    <?php }
    else{ ?>
        <?php foreach($marketOffers as $offer):
            if(isset($offer['Player'])){
                $player = true;
                $element = $offer['Player'];
            }
            else{
                $player = false;
                $element = $offer['Car'];
            }
            ?>
            <div class="item">
                <a href="/market/show-<?php echo ($player?'':'car-');?>offer/<?= $offer['id']; ?>">
                    <?php 
                    if($player){
                        echo '<i class="fa fa-user" title="Player"></i>';
                        echo $element['last_name']." ".$element['first_name']; 
                    }
                    else{
                        echo '<i class="fa fa-car" title="Car"></i>';
                        echo $element['name'];
                    }
                    ?>
                </a>
                <?php
                if(isset($offer['Bids'][0]))
                    echo '<i title="Highest bid" class="fa fa-money"></i> $'.(int)$offer['Bids'][0]['value']." - <span class='transferTeam'>".$offer['Bids'][0]['Team']['name']."</span><br />"; 
                else
                    echo "no offers<br />";
                ?>
                <span>
                    <i class="fa fa-clock-o" title="Auction finish"></i>
                    <?php echo TK_Text::timeFormat($offer['finish_date'],'d/m/Y H:i'); ?>
                </span>
            </div>
        <?php endforeach; ?>
        <div class="bottom">
            <?php if($player)
                $link = "/market/player-monitor";
            else
                $link = "/market/car-monitor";
            ?>
            <a href="<?= $link; ?>" class="logIn btn seeAllTransfer"><?= $this->translate('SEE ALL'); ?></a>
        </div>
    <?php } ?>
</div>

