<?php
    if(isset($_GET['msg'])){
        if($_GET['msg']=="no exist"){
            $this->showError('This offer does not exist');
        }
        elseif($_GET['msg']=="offer expired"){
            $this->showError('This offer has expired');
        }
    }
    ?>
<div class="mainUserBox myCarsBox">
    <h4 class="boxHeader"><?= $this->translate('Cars market');?></h4>
    
        <?php foreach($marketOffers as $offer):
        $car = $offer['Car'];
        ?>
    
    <div class='col-md-12 mb20'>
        <div class="myPeople peopleList driverList carMarketList">
            <ul>
                <li class="active">
                    <a class="offerLink" href="/market/show-car-offer/<?= $offer['id']; ?>">
                        <?php echo $car['name']; ?> 
                    </a>
                    <?php if($car['Team']['id']!=$authenticatedUser['Team']['id']):
                        
                        if(strlen($offer['highest_bid'])&&$offer['highest_bid']!=0){
                            $populateBid = (int)($offer['highest_bid']*1.1);
                        }
                        else{
                            $populateBid = $offer['asking_price'];
                        }
                    ?>
                             <a class="btn myBtn bidCar" data-toggle="modal" data-bid="<?= $populateBid; ?>" data-target="#bidCar" data-name="<?= $car['name']; ?>" rel="<?= $offer['id']; ?>"><?= $this->translate('Bid car'); ?></a>
                    <?php endif; ?>
                </li>
            </ul>
                 
        <div class="carCard carMarketCard col-md-8 active peopleMarketCard mr0">
           
                        
            
            <div class="col-md-7">
                <?= TK_Helper::showCarParameters($car,$offer['Car']['Team']); ?>

                    <div class="clearfix"></div>
                
                <div class="clearfix"></div>
            </div>
            
            <div class="col-md-5 pr0 pl0 carParametersWrapper">
                 <?php if(isset($car['Model']['photo'])&&strlen($car['Model']['photo'])){ ?>
                <img src="/media/cars/<?php echo $car['Model']['photo']; ?>" alt="<?php echo $car['Model']['name']; ?>" class="carCardPhoto" />
            <?php } 
                else{ ?>
                    <img src="http://dummyimage.com/340x220&amp;text=No+photo"  class="carCardPhoto" />
            <?php } ?>
            </div>
        <div class='clearfix'></div>
        </div>
            <div class='col-md-1'></div>
        <div class="col-md-3 peopleMarketSmallCard">
            
            <table>
                <tr>
                    <th><?= $this->translate('Highest bid'); ?>: </th>
                </tr>
                <tr>
                    <td>
                        <?php
                            if(isset($offer['Bids'][0])&&$offer['Bids'][0]['active']){
                                echo "$".(int)$offer['Bids'][0]['value']." - ".$offer['Bids'][0]['Team']['name']; 
                            }
                            else
                                echo $this->translate("no offers");
                        ?>
                    </td>
                </tr>
                <tr>
                    <th><?= $this->translate('Asking price'); ?>:</th>
                </tr>
                <tr>
                    <td>$<?= $offer['asking_price']; ?></td>
                </tr>
                <tr>
                    <th><?= $this->translate('Auction finish'); ?>: </th>
                </tr>
                <tr>
                    <td>
                        <?php echo TK_Text::timeFormat($offer['finish_date'],'d/m/y H:i'); ?>
                    </td>
                </tr>
                <tr>
                    <th><?= $this->translate('Other offers'); ?>: </th>
                </tr>
                <tr>
                    <td>
                        <?php foreach($offer['Bids'] as $key => $bid):
                            if($bid['active']==0)
                                continue;

                            if($key==0)
                                continue;
                            if($key>3)
                                break;

                            echo "$".$bid['value']." - ".$bid['Team']['name']."<br />"; 
                        endforeach; ?>
                    </td>
                </tr>
            </table>
        </div>
        <div class='clearfix'></div>
        </div>
    </div>
    <?php endforeach; ?>
</div>

<div id="bidCar" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <form method="POST" action="/market/bid-car">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"><?= $this->translate('Bid car'); ?> <span id="bidCarName"></span></h4>
                </div>
                <div class="modal-body">
                    <label for="asking_price"><?= $this->translate('Your offer'); ?></label>
                    <?php echo $form->getElement('bid')->renderElement(); ?>
                    <?php echo $form->getElement('offer_id')->renderElement(); ?>
                </div>
                <div class="modal-footer">
                    <?php echo $form->getElement('submit')->renderElement(); ?>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->translate('Close'); ?></button>
                </div>
            </div>
        </form>

    </div>
</div>


<script>
    $(document).ready(function(){
        
        $('.bidCar').click(function(){
           var rel = $(this).attr('rel');
           $('#offer_id').val(rel);
           $('#bid').val($(this).attr('data-bid'));
           $('#bidCarName').html($(this).attr('data-name'));
        });
    });
</script>