<h2>Market</h2>
<hr />
<?php foreach($marketOffers as $offer):
    $car = $offer['Car'];
    ?>
<div class="col-md-8">
   <?php if(isset($car['Model']['photo'])&&strlen($car['Model']['photo'])){ ?>
        <img src="/media/cars/<?php echo $car['Model']['photo']; ?>" alt="<?php echo $car['Model']['name']; ?>" style="width:300px;float:right;margin-right:100px;" />
   <?php } ?>
Car name: <?php echo $car['name']; ?> <br />
    <div class="changeCarName" id="changeCarName1">
	<?php // echo $formCar1->renderForm(); ?>
    </div>
    Marka: <?php echo $car['Model']['name']; ?><br />
    Przebieg: <?php echo $car['mileage']; ?><br />
    Wartość: <?php echo $car['value']; ?><br />
    Koszty utrzymania: <?php echo $car['upkeep']; ?><br />
    <fieldset>
        <table>
            <tr>
                <td>Pojemność silnika</td>
                <td><?php echo $car['Model']['capacity'];?></td>
            </tr>
            <tr>
                <td>Moc</td>
                <td><?php echo $car['Model']['horsepower'];?></td>
            </tr>
            <tr>
                <td>V max</td>
                <td><?php echo $car['Model']['max_speed'];?></td>
            </tr>
            <tr>
                <td>Przyspieszenie</td>
                <td><?php echo $car['Model']['acceleration'];?></td>
            </tr>
            <tr>
                <td>Napęd</td>
		<td><?php echo $car['Model']['wheel_drive'];?></td>
            </tr>
            
        </table>
    </fieldset>
</div>
<div class="col-md-4">
    <h3>Oferty</h3>
    Najwyższa oferta 
    <strong><?php
    if(isset($offer['Bids'][0]))
        echo (int)$offer['Bids'][0]['value']."$ - ".$offer['Bids'][0]['Team']['name']."<br />"; 
    else
        echo "brak ofert";
    ?></strong>
    <span>Koniec aukcji - <?php echo TK_Text::timeFormat($offer['finish_date'],'d/m/Y H:i:s'); ?></span>
    <br /><br />
    Pozostałe oferty<br />
    <?php foreach($offer['Bids'] as $key => $bid):
        if($key==0)
            continue;
        if($key>5)
            break;
        
        echo $bid['value']."$ - ".$bid['Team']['name']."<br />"; 
    endforeach; ?>
    <br />
    <?php if($car['Team']['id']!=$user['Team']['id']): ?>
    <a href="/market/bid-car/id/<?php echo $offer['id']; ?>">Zalicytuj</a>
    <?php endif; ?>
</div>
<div class='clearfix'></div>
<hr />
<?php endforeach; ?>