<?php

/**
 * People_Model_Doctrine_People
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class People_Model_Doctrine_People extends People_Model_Doctrine_BasePeople
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Team_Model_Doctrine_Team as Team as Driver1', array(
             'local' => 'id',
             'foreign' => 'driver1_id'));
	
	$this->hasOne('Team_Model_Doctrine_Team as Team as Driver2', array(
             'local' => 'id',
             'foreign' => 'driver2_id'));
	
	$this->hasOne('Team_Model_Doctrine_Team as Team as Pilot1', array(
             'local' => 'id',
             'foreign' => 'pilot1_id'));
	
	$this->hasOne('Team_Model_Doctrine_Team as Team', array(
             'local' => 'id',
             'foreign' => 'pilot2_id'));

	
	
    }
}