<?php

/**
 * People_Model_Doctrine_PeopleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class People_Model_Doctrine_PeopleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object People_Model_Doctrine_PeopleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('People_Model_Doctrine_People');
    }
}