<div class="row">
    <div class="col-md-12">
        <h3 class="page-title">
            Edit car model <?= $carModel['id']; ?>
        </h3>
        <div class="page-bar">
            <ul class="page-breadcrumb breadcrumb">
                    <li>
                            <i class="fa fa-home"></i>
                            <a href="/">Home</a>
                            <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                            <a href="/admin/car/list-car">List car</a>
                            <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                            <a href="#">Edit car <?= $carModel['id']; ?></a>
                    </li>
            </ul>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 ">
            <!-- BEGIN SAMPLE FORM PORTLET-->
            <div class="portlet box blue">
                    <div class="portlet-title">
                            <div class="caption">
                                    <i class="fa fa-car"></i> Edit car
                            </div>
                            <div class="tools">
                                    <a href="" class="collapse" data-original-title="" title="">
                                    </a>
                                    <a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title="">
                                    </a>
                                    <a href="" class="reload" data-original-title="" title="">
                                    </a>
                                    <a href="" class="remove" data-original-title="" title="">
                                    </a>
                            </div>
                    </div>
                    <div class="portlet-body form">
                            <form role="form" method="POST">
                                    <div class="form-body">
                                        <input type="hidden" value="<?= $carModel['id']; ?>" name="id" />
                                        <?php echo $form->getElement('name')->renderAdminElement(); ?>
                                        <?php echo $form->getElement('acceleration')->renderAdminElement(); ?>
                                        <?php echo $form->getElement('max_speed')->renderAdminElement(); ?>
                                        <?php echo $form->getElement('horsepower')->renderAdminElement(); ?>
                                        <?php echo $form->getElement('capacity')->renderAdminElement(); ?>
                                        <?php echo $form->getElement('league')->renderAdminElement(); ?>
                                        <?php echo $form->getElement('on_market')->renderAdminElement(); ?>
                                        <?php echo $form->getElement('price')->renderAdminElement(); ?>
                                        <?php echo $form->getElement('photo')->renderAdminElement(); ?>
                                            
                                    </div>
                                    <div class="form-actions">
                                            <button type="submit" name="submit" class="btn green"><i class="fa fa-mail-forward"></i> Submit</button>
                                            <button type="submit" name="save_and_add_new" class="btn blue"><i class="fa fa-plus"></i> Save and add new</button>
                                            <button type="submit" name="save_and_stay" class="btn purple"><i class="fa fa-floppy-o"></i> Save and stay</button>
                                            <a type="button" href="/admin/car/list-car" class="btn default"><i class="fa fa-level-up"></i> Cancel</a>
                                    </div>
                            </form>
                    </div>
            </div>
            <!-- END SAMPLE FORM PORTLET-->
    </div>
</div>