<script>
    $(document).ready(function(){
        var grid = new Datatable();
            grid.init({
                src: $("#datatable_ajax"),
                dataTable: {   
                "aoColumns": [
                        { sWidth: '5%' },
                        { sWidth: '5%' },
                        { sWidth: '15%' },
                        { sWidth: '5%' },
                        { sWidth: '10%' },
                        { sWidth: '5%' },
                        { sWidth: '5%' },
                        { sWidth: '5%' },
                        { sWidth: '5%' },
                        { sWidth: '5%' },
                        { "bSortable": false, sWidth: '5%' }
                    ],
                    "aLengthMenu": [
                        [20, 50, 100, 150, -1],
                        [20, 50, 100, 150, "All"] // change per page values here
                    ],
                    "iDisplayLength": 20, // default record count per page
                    "bServerSide": true, // server side processing
                    "bLengthChange": false,
                    "bFilter": true,
                    "bDestroy": true,
                    "bProcessing": true,
                    "sAjaxSource": "/admin/car/list-car-data", // ajax source
                    "aaSorting": [[ 1, "asc" ]] // set first column as a default sort by asc
                }
            });
              grid.getDataTable().yadcf([
                 {
                   column_number: 1,
                   filter_type: "text"
                 },
                 {
                   column_number: 2,
                   filter_type: "text"
                 },
                 {
                   column_number: 3,
                   filter_type: "text"
                 },
                 {
                   column_number: 4,
                   filter_type: "text"
                 },
                 {
                   column_number: 5,
                   filter_type: "text"
                 },
                 {
                   column_number: 6,
                   filter_type: "text"
                 },
                 {
                   column_number: 7,
                   filter_type: "text"
                 },
                {
                    column_number: 8,
                    data: [{
                        value: '1',
                        label: 'Tak'
                    }, {
                        value: '0',
                        label: 'Nie'
                    }],
                },
                 {
                   column_number: 9,
                   filter_type: "text"
                 }
        ]);
                
        customDataTableFunctions();
    });
</script>
<div class="row">
    <div class="col-md-12">
        <h3 class="page-title">
            Car models
        </h3>
        <ul class="page-breadcrumb breadcrumb">
                <li>
                        <i class="fa fa-home"></i>
                        <a href="/admin">
                        Home </a>
                        <i class="fa fa-angle-right"></i>
                </li>
                <li>
                        <a href="#">Car models</a>
                </li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="portlet box purple">
            <div class="portlet-title">
                <div class="caption">
                        <i class="fa fa-car"></i>Car models
                </div>
                <div class="actions">
                        
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <div class="row">
                            <div class="col-md-6">
                                    <div class="btn-group">
                                            <a href="/admin/car/add-car" id="sample_editable_1_new" class="btn green">
                                            Add New <i class="fa fa-plus"></i>
                                            </a>
                                    </div>
                            </div>
                            <div class="col-md-6"></div>
                    </div>
                </div>
                <div class="table-container">
                    <table class="table table-striped table-bordered table-hover" id="datatable_ajax">
                        <thead>
                            <tr role="row" class="heading">
                                <th><input type="checkbox" class="group-checkable"></th>
                                <th>Id</th>
                                <th>Auto</th>
                                <th>Poj. skokowa</th>
                                <th>KM</th>
                                <th>vMax</th>
                                <th>Przyspieszenie</th>
                                <th>Liga</th>
                                <th>W sklepie</th>
                                <th>Cena</th>
                                <th>Options</th>
                            </tr>
                            <tr role="row" class="filter">
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th>
                                    <div class="margin-bottom-5">
                                            <button class="btn btn-sm yellow filter-submit margin-bottom"><i class="fa fa-search"></i> Search</button>
                                    </div>
                                    <button class="btn btn-sm red filter-cancel"><i class="fa fa-times"></i> Reset</button>
                                </th>
                            </tr> 
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>