<?php

/**
 * Card_Model_Doctrine_PackageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Card_Model_Doctrine_PackageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Card_Model_Doctrine_PackageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Card_Model_Doctrine_Package');
    }
}