<div class="mainUserBox showLeagueTable">
    <h4 class="boxHeader"><?= $this->translate('League')." ".$league; ?></h4> 
   <div class="showLeagueTableWrapper"> 
       <div>
            <?php
                $leagueExpl = explode('.',$league);
                $leagueLevel = $leagueExpl[0];
                if($leagueLevel!=1){
                    echo $this->translate('Top 2 teams are promoted to league ').($leagueLevel-1);
                }
                else{
                    echo $this->translate('Last 6 teams are downgraded to league ').($leagueLevel+1);
                }
            ?>
       </div>
       <br />
        <table>
            <thead>
                <tr>
                    <th><?= $this->translate('Position');?></th>
                    <th><?= $this->translate('Team');?></th>
                    <?php foreach($leagueResults as $leagueResult): ?>
                        <th class="thVertical">
                            <div>
                                <?= $leagueResult['name']; ?>
                            </div>
                        </th>
                    <?php endforeach; ?>
                    <th><?= $this->translate('Points');?></th>
                </tr>
            </thead>
            <tbody>
                <?php 
                $rows = count($leagueTable);
                $green = array(0,1,2);
                $red = array($rows-1,$rows-2,$rows-3);
                foreach($leagueTable as $key => $team): ?>
                    <tr
                        class="
                        <?php
                        if(in_array($key,$green)): 
                            echo "lightgreen";
                        elseif(in_array($key,$red)):
                            echo "lightred";
                        endif;
                            ?>"
                        >
                        <td><?php echo $key+1; ?></td>
                        <td><?php echo $team['Team']['name']; ?></td>
                        <?php foreach($leagueResults as $leagueResult): ?>
                            <td><?= (int)$leagueResult['teams'][$team['Team']['id']]; ?></td>
                        <?php endforeach; ?>
                        <td><?php echo $team['points']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>