<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>

<div class="row">
	<div class="col-md-12">
		<!-- BEGIN VALIDATION STATES-->
		<div class="portlet box purple">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i>Add stage
				</div>
				<div class="tools">
					<a href="javascript:;" class="collapse" data-original-title="" title="">
					</a>
					<a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title="">
					</a>
					<a href="javascript:;" class="reload" data-original-title="" title="">
					</a>
					<a href="javascript:;" class="remove" data-original-title="" title="">
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form action="" id="form_sample_1" class="form-horizontal" method="POST">
					<div class="form-body">
                                                <?php echo $form->getElement('name')->renderAdminElement(); ?>
						<?php echo $form->getElement('surface1')->renderAdminElement(); ?>
						<input type="hidden" name="form_send" value="1" />
					</div>
                                    
					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" name="submit" class="btn green">Submit</button>
								<button type="submit" name="saveAndAddNew" class="btn blue"><i class="fa fa-plus"></i> Save and add new </button>
								<button type="submit" name="saveAndStay" class="btn purple"><i class="fa fa-edit"></i> Save and stay</button>
								<button type="button" class="btn default">Cancel</button>
							</div>
						</div>
					</div>
				</form>
				<!-- END FORM-->
			</div>
		</div>
		<!-- END VALIDATION STATES-->
	</div>
</div>