<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
    <?= $form->getElement('cmd')->renderElement(); ?>
    <?= $form->getElement('business')->renderElement(); ?>
    <?= $form->getElement('item_name')->renderElement(); ?>
    <?= $form->getElement('amount')->renderElement(); ?>
    <?= $form->getElement('currency_code')->renderElement(); ?>
    <?= $form->getElement('quantity')->renderElement(); ?>
<!--    <input type="hidden" name="cmd" value="_s-xclick">
    <input type="hidden" name="hosted_button_id" value="TYLEQLX6DV4D8">
    <table>
    <tr><td><input type="hidden" name="on0" value="Amount">Amount</td></tr><tr><td>
            <input type="radio" name="os0" value="100 points -" />100 points - £2.00 GBP
            <input type="radio" name="os0" value="315 points -" />315 points - £6.00 GBP
            <input type="radio" name="os0" value="550 points -" />550 points - £10.00 GBP
            <input type="radio" name="os0" value="1150 points" />1150 points £20.00 GBP
     </td></tr>
    </table>
    <input type="hidden" name="currency_code" value="GBP">
-->    <input type="image" src="https://www.sandbox.paypal.com/en_US/GB/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online.">
    <img alt="" border="0" src="https://www.sandbox.paypal.com/en_GB/i/scr/pixel.gif" width="1" height="1">
</form>

<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_xclick">
<input type="hidden" name="business" value="biuro@kardimobile.pl" >
<input type="hidden" name="item_name" value="100 points">
<input type="hidden" name="amount" value="20">
<input type="hidden" name="quantity" value="1">
<input type="hidden" name="currency_code" value="EUR">
<input type="image" src="https://www.sandbox.paypal.com/en_GB/i/btn/x-click-butcc.gif" border="0" name="submit" width="73" height="44">
</form>