<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
    <?= $form->getElement('cmd')->renderElement(); ?>
    <?= $form->getElement('hosted_button_id')->renderElement(); ?>
    <?= $form->getElement('on0')->renderElement(); ?>
    <?= $form->getElement('os0')->renderElement(); ?>
    <?= $form->getElement('currency_code')->renderElement(); ?>
    <?php // $form->getElement('submit')->renderElement(); ?>
<!--    <input type="hidden" name="cmd" value="_s-xclick">
    <input type="hidden" name="hosted_button_id" value="TYLEQLX6DV4D8">
    <table>
    <tr><td><input type="hidden" name="on0" value="Amount">Amount</td></tr><tr><td>
            <input type="radio" name="os0" value="100 points -" />100 points - £2.00 GBP
            <input type="radio" name="os0" value="315 points -" />315 points - £6.00 GBP
            <input type="radio" name="os0" value="550 points -" />550 points - £10.00 GBP
            <input type="radio" name="os0" value="1150 points" />1150 points £20.00 GBP
     </td></tr>
    </table>
    <input type="hidden" name="currency_code" value="GBP">
-->    <input type="image" src="https://www.sandbox.paypal.com/en_US/GB/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online.">
    <img alt="" border="0" src="https://www.sandbox.paypal.com/en_GB/i/scr/pixel.gif" width="1" height="1">
</form>
<!--<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="TYLEQLX6DV4D8">
<table>
<tr><td><input type="hidden" name="on0" value="Amount">Amount</td></tr><tr><td><select name="os0">
	<option value="100 points -">100 points - £2.00 GBP</option>
	<option value="315 points -">315 points - £6.00 GBP</option>
	<option value="550 points -">550 points - £10.00 GBP</option>
	<option value="1150 points">1150 points £20.00 GBP</option>
</select> </td></tr>
</table>
<input type="hidden" name="currency_code" value="GBP">
<input type="image" src="https://www.sandbox.paypal.com/en_US/GB/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online.">
<img alt="" border="0" src="https://www.sandbox.paypal.com/en_GB/i/scr/pixel.gif" width="1" height="1">
</form>-->
