<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
    <?= $form->getElement('cmd')->renderElement(); ?>
    <?= $form->getElement('business')->renderElement(); ?>
    <?= $form->getElement('item_name')->renderElement(); ?>
    <?= $form->getElement('amount')->renderElement(); ?>
    <?= $form->getElement('currency_code')->renderElement(); ?>
    <?= $form->getElement('quantity')->renderElement(); ?>
    <?= $form->getElement('rm')->renderElement(); ?>
    <?= $form->getElement('return')->renderElement(); ?>
    <input type="image" src="https://www.sandbox.paypal.com/en_US/GB/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online.">
    <img alt="" border="0" src="https://www.sandbox.paypal.com/en_GB/i/scr/pixel.gif" width="1" height="1">
</form>
