<form action="https://secure.transferuj.pl" method="post" target="_top">
    <?= $form->getElement('md5sum')->renderElement(); ?>
    <?= $form->getElement('id')->renderElement(); ?>
    <?= $form->getElement('crc')->renderElement(); ?>
    <?= $form->getElement('opis')->renderElement(); ?>
    <?= $form->getElement('kwota')->renderElement(); ?>
    <?= $form->getElement('wyn_url')->renderElement(); ?>
    <?= $form->getElement('pow_url')->renderElement(); ?>
    <?= $form->getElement('jezyk')->renderElement(); ?>
    <?= $form->getElement('submit')->renderElement(); ?>
</form>
