<table style="background:#333;width:600px;margin:0 auto;">
    <tr>
        <td style="padding:15px;"><img src="http://<?= $domain;?>/images/layout/logo-fastrally.png" /></td>
        <td>
            
        </td>
    </tr>
    <tr>
        <td style="padding:10px;padding-top:30px;border-top:1px solid #f3f3f3; color:#f3f3f3;width:450px;border-right:1px solid #f3f3f3;">
            <?= $text; ?>
        </td>
        <td style="border-top:1px solid #f3f3f3; color:#f3f3f3;
    vertical-align: top;
    padding: 10px;
    padding-top: 30px;">
            Follow us for latest promotions and contests.
            <br />
            <div style="margin:0 auto;display:block;text-align:center;margin-top:10px;">
            <a href="<?php $facebookUrl; ?>" class="fb social_icon_link">
                <img src="http://<?= $domain;?>/images/layout/fb.png" />
            </a>
            <a href="<?php $twitterUrl; ?>" class="twitter social_icon_link">
                <img src="http://<?= $domain;?>/images/layout/tw.png" />
            </a>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="2" style="padding:15px 10px;border-top:1px solid #f3f3f3;margin-bottom:10px;color:#f3f3f3;">
            Did you know that in Big Rallies you can win unique cars? <a style="color:#f3f3f3;" href="#">Sign up for next big rally</a> on 24/07/2015 and 
            give yourself a chance to win unique and only Ferrari 650 Quatro. 
        </td>
    </tr>
</table>