<?php
Service::loadModels('car', 'car');
Service::loadModels('rally', 'rally');
$rallyService = Controller::getService('rally', 'rally');
$nextBigRally = $rallyService->getNextBigRallyWithAwards();
?>
<table style="font-family: tahoma; border: 3px solid #000000; margin-top: 0px; width: 600px;" cellspacing="0" cellpadding="0" align="center">
    <tbody>
        <tr>
            <td width="600">
                <table style="font-family: tahoma;background:#333;width:600px;margin:0 auto;">

                    <tr>
                        <td colspan="2" valign="top" colspan='2' width="600">
                            <a href="http://fastrally.eu/" target="_blank" style='position:absolute;background:rgba(51, 51, 51, 0.65);padding:5px;'>
                                <img src="http://fastrally.eu/images/layout/logo-fastrally.png" alt="" align="absbottom" border="0" />
                            </a>
                            <img src="http://fastrally.eu/images/layout/car_email2.jpg" alt="" width=""  align="absbottom" />
                        </td>
                       
                    </tr>
                    <tr>
                        <td colspan="2" style="padding:10px;padding-top:30px; color:#f3f3f3;font-size:14px;line-height:28px;">
                            <?= $text; ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table style="width:300px;border:3px solid #000000;border-spacing:0px;">
                                <tr>
                                    <td style="background-color:#000000;color:#ffffff;text-align:center;padding:5px 10px;" bgcolor="#000000">Śledź nas</td>
                                </tr>

                                <tr>
                                    <td style="color:#eaeaea;text-align:center;padding-top:10px;
                                        padding-bottom:10px;">Bądź na bieżąco z najnowszymi konkursami i promocjami</td>
                                </tr>
                                <tr>
                                    <td style="text-align:center;">
                                        <a href="<?php $facebookUrl; ?>" class="fb social_icon_link">
                                            <img src="http://fastrally.eu/images/layout/fb_med.jpg" alt="FastRally Facebook" title="FastRally Facebook" />
                                        </a>
                                        <a href="<?php $twitterUrl; ?>" class="twitter social_icon_link" alt="FastRally Twitter" title="FastRally Twitter">
                                            <img src="http://fastrally.eu/images/layout/tw_med.jpg" />
                                        </a>
                                    </td>
                                </tr>
                            </table>
                        </td>
                        
                        <td>
                            <table style="width:300px;border:3px solid #000000;border-spacing:0px;">
                                <tr>
                                    <td style="background-color:#000000;color:#ffffff;text-align:center;padding:5px 10px;" bgcolor="#000000">Karty FastRally</td>
                                </tr>

                                <tr>
                                    <td style="text-align:center;">
                                        <img src="http://fastrally.eu/images/layout/fastrally_cards_mail.png" />
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <?php if ($nextBigRally) { ?>
                            <td colspan="2" style="padding:15px 10px;border-top:1px solid #f3f3f3;margin-bottom:10px;color:#f3f3f3;">

                                Did you know that in Big Rallies you can win unique cars? <a style="color:#f3f3f3;" href="/rally/show-rally/<?= $nextBigRally['slug']; ?>/">Sign up for next big rally</a> on <?= TK_Text::timeFOrmat($nextBigRally['date'], 'd/m/Y'); ?> and 
                                give yourself a chance to win unique and only <?= $nextBigRally['BigAwards'][0]['Car']['name']; ?>. 

                            </td>
                        <?php } else { ?>
                            <td colspan="2">
                                
                                
                            </td>
                        <?php } ?>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>