
<table style="width: 100%;" border="0" bgcolor="#DCDCDC">
    <tbody>
        <tr>
            <td>
                <table style="font-family: tahoma; border: 3px solid #000000; margin-top: 0px; width: 600px;" cellspacing="0" cellpadding="0" align="center">
                    <tbody>
                        <tr>
                            <td width="600">
                                <table style="width: 77%;" border="0" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF">
                                    <tbody>
                                        <tr>
                                            <td style="padding: 0px;" colspan="5" align="left" valign="top">
                                                <table style="width: 600px;" border="0" cellspacing="0" cellpadding="0">
                                                    <tbody>
                                                        <tr>
                                                            <td valign="top" width="422"><a href="http://www.managerzone.com/" target="_blank"><img src="http://static.managerzone.com/img/newsletter/soccer/soccer_02.jpg" alt="" width="227" height="58" align="absbottom" border="0" /></a><img src="http://static.managerzone.com/img/newsletter/soccer/soccer_03.jpg" alt="" width="195" height="58" align="absbottom" /><img src="http://static.managerzone.com/img/newsletter/soccer/soccer_06.jpg" alt="" width="422" height="165" align="top" /><br />
                                                                <h1 style="color: #006600; font-size: 20px; padding: 20px 10px 0px 20px;">Witaj w ManagerZone!</h1>
                                                            </td>
                                                            <td valign="top" width="178"><img style="float: right;" src="http://static.managerzone.com/img/newsletter/soccer/soccer_04.jpg" alt="" width="178" height="300" /></td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                                <p style="color: #444444; padding: 0px 10px 0px 20px; line-height: 22px; font-size: 12px;">Gratulacje, jesteś teraz dumnym managerem drużyny <strong>Klatki</strong> !<br /><br />Aby czuć się komfortowo na Twoim nowym stanowisku, mamy kilka wskazówek, które pomogą Ci uporać się z nową pracą.</p>
                                                <p style="color: #444444; padding: 0px 10px 0px 20px; line-height: 22px; font-size: 12px;">Najlepszym sposobem, aby nauczyć się podstaw ManagerZone jest użycie <a href="http://www.managerzone.com/?p=tutorial" target="_blank">Przewodnika</a>, gdzie można zarobić pieniądze dla zespołu w zamian za wypełnianie zadań. Jeśli nadal nie jesteś pewien co do niektórych obszarów gry, zapoznaj się z <a href="http://www.managerzone.com/?p=manual_faq" target="_blank">szczegółową instrukcją</a> lub zapytać w <a href="http://www.managerzone.com/?p=forum" target="_blank">P i O</a> na Forum.</p>
                                                <p style="color: #444444; padding: 0px 10px 0px 20px; line-height: 22px; font-size: 12px;">Teraz, kiedy jesteś odpowiedzialny za swój własny klub, możesz natychmiast zacząć działać na cztery sposoby:<br /><br /></p>
                                            </td>
                                        </tr>
                                        <tr style="margin: 0; padding: 0;">
                                            <td align="left" valign="top" width="5"> </td>
                                            <td align="left" valign="top" width="290" height="39">
                                                <table style="width: 290px; background-color: #000000;" bgcolor="#000000">
                                                    <tbody>
                                                        <tr>
                                                            <td width="35" height="29"><img src="http://blog.managerzone.com/wp-content/uploads/2011/07/Untitled-3.png" alt="" width="29" height="29" /></td>
                                                            <td style="color: #ffffff; font-size: 16px; text-align: left;" width="200">SPOTKAJ SIĘ Z ZESPOŁEM</td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                            <td align="left" valign="top" width="10" height="39"> </td>
                                            <td align="left" valign="top" width="290" height="39">
                                                <table style="width: 290px; background-color: #000000;" bgcolor="#000000">
                                                    <tbody>
                                                        <tr>
                                                            <td width="35" height="29"><img src="http://blog.managerzone.com/wp-content/uploads/2011/07/Untitled-3.png" alt="" width="29" height="29" /></td>
                                                            <td style="color: #ffffff; font-size: 16px; text-align: left;" width="200">ODWIEDŹ BIURO</td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                            <td align="left" valign="top" width="5"> </td>
                                        </tr>
                                        <tr style="margin: 0; padding: 0;">
                                            <td align="left" valign="top" width="5"> </td>
                                            <td style="font-size: 11px; padding: 0px;" align="left" valign="top" bgcolor="#FFFFFF">
                                                <p style="margin: 0px 0px 2px 5px;"> </p>
                                                <h2 style="margin: 0px; color: #900000; font-size: 11px;"><a href="http://www.managerzone.com/?p=clubhouse" target="_blank"><img src="http://static.managerzone.com/img/newsletter/soccer/soccer_14.jpg" alt="" width="290" height="101" /></a></h2>
                                                <p style="color: #444444; margin: 5px 10px 10px 10px; line-height: 20px; font-size: 12px;">Najważniejszą częścią klubu są zawodnicy. Udaj się do Budynku Klubowego aby zobaczyć zawodników, plan strategii szkolenia i ustawić taktykę, która doprowadzi Cię do zwycięstwa.</p>
                                            </td>
                                            <td width="10"> </td>
                                            <td class="header" style="font-size: 11px; padding: 0px;" align="left" valign="top" bgcolor="#FFFFFF">
                                                <p style="margin: 0px 0px 2px 5px;"> </p>
                                                <h2 style="margin: 0px; color: #900000; font-size: 11px;"><a href="http://www.managerzone.com/?p=office" target="_blank"><img src="http://managerzone.com/dynimg/pic.php?type=news&amp;id=briefcase_sm" alt="" width="290" height="101" /></a></h2>
                                                <p style="color: #444444; margin: 5px 10px 10px 10px; line-height: 20px; font-size: 12px;">Żaden menedżer nie może odnieść sukcesu bez efektywnego zarządzania aktywami klubu. Odwiedź Biuro, aby zobaczyć swoje finanse i budować stadion.</p>
                                            </td>
                                            <td align="left" valign="top" width="5"> </td>
                                        </tr>
                                        <tr style="margin: 0; padding: 0;">
                                            <td align="left" valign="top" width="5"> </td>
                                            <td align="left" valign="top" width="290" height="39">
                                                <table style="width: 290px; background-color: #000000;" bgcolor="#000000">
                                                    <tbody>
                                                        <tr>
                                                            <td width="35" height="29"><img src="http://blog.managerzone.com/wp-content/uploads/2011/07/Untitled-3.png" alt="" width="29" height="29" /></td>
                                                            <td style="color: #ffffff; font-size: 16px; text-align: left;" width="200">GRAJ W ROZGRYWKACH</td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                            <td align="left" valign="top" width="10" height="39"> </td>
                                            <td align="left" valign="top" width="290" height="39">
                                                <table style="width: 290px; background-color: #000000;" bgcolor="#000000">
                                                    <tbody>
                                                        <tr>
                                                            <td width="35" height="29"><img src="http://blog.managerzone.com/wp-content/uploads/2011/07/Untitled-3.png" alt="" width="29" height="29" /></td>
                                                            <td style="color: #ffffff; font-size: 16px; text-align: left;" width="200">DOŁĄCZ DO SPOŁECZNOŚCI</td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                            <td align="left" valign="top" width="5"> </td>
                                        </tr>
                                        <tr style="margin: 0; padding: 0;">
                                            <td align="left" valign="top" width="5"> </td>
                                            <td style="font-size: 11px; padding: 0px;" align="left" valign="top" bgcolor="#FFFFFF">
                                                <p style="margin: 0px 0px 2px 5px;"> </p>
                                                <h2 style="margin: 0px; color: #900000; font-size: 11px;"><a href="http://www.managerzone.com/?p=match%E2%8A%82=scheduled" target="_blank"><img src="http://managerzone.com/dynimg/pic.php?type=news&amp;id=fans_sm" alt="" width="290" height="101" /></a></h2>
                                                <p style="color: #444444; margin: 5px 10px 10px 10px; line-height: 20px; font-size: 12px;">Sprawdź swoje strategie na boisku! Oprócz oficjalnych meczów Ligi należy konkurować w Pucharach, Ligach Towarzyskich i Szybkich Meczach by uzyskać przewagę nad konkurencją.</p>
                                            </td>
                                            <td width="10"> </td>
                                            <td class="header" style="font-size: 11px; padding: 0px;" align="left" valign="top" bgcolor="#FFFFFF">
                                                <p style="margin: 0px 0px 2px 5px;"> </p>
                                                <h2 style="margin: 0px; color: #900000; font-size: 11px;"><a href="http://www.managerzone.com/?p=community" target="_blank"><img src="http://static.managerzone.com/img/newsletter/soccer/soccer_16.jpg" alt="" width="290" height="101" /></a></h2>
                                                <p style="color: #444444; margin: 5px 10px 10px 10px; line-height: 20px; font-size: 12px;">Większość Managerów powie Ci, że najlepszą rzeczą jaką zrobili było odwiedzenie Forum. Uzyskaj wskazówki, przyjaciół czy nowych rywali przez dołączenie do naszej aktywnej społeczności</p>
                                            </td>
                                            <td align="left" valign="top" width="5"> </td>
                                        </tr>
                                        <tr>
                                            <td colspan="5">
                                                <h1 style="color: #006600; font-size: 20px; padding: 20px 10px 10px 20px; text-align: center;">Twój klub czeka. Powodzenia w nowej pracy!</h1>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <table style="color: #787878; font-family: Verdana, Geneva, sans-serif; font-size: 10px; width: 600px;" border="0" align="center">
                    <tbody>
                        <tr>
                            <td valign="middle" width="77" height="30"><a href="http://www.facebook.com/managerzone" target="_blank"><img src="http://static.managerzone.com/img/newsletter/general/manager_16.jpg" alt="" width="19" height="23" /></a><a href="http://twitter.com/managerzone" target="_blank"><img src="http://static.managerzone.com/img/newsletter/general/manager_17.jpg" alt="" width="24" height="23" /></a><a href="http://www.youtube.com/managerzone" target="_blank"><img src="http://static.managerzone.com/img/newsletter/general/manager_18.jpg" alt="" width="22" height="23" /></a></td>
                            <td valign="middle" width="304"><strong>Śledź nas w Internecie!</strong></td>
                            <td valign="middle" width="205">© Power Challenge AB 2014<br /><a href="http://www.managerzone.com/unsubscribe.php?uid=8273106&amp;val=8710bd854b3837e9f429a16c2ac7824a" target="_blank">Unsubscribe</a></td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>