<?php 

Service::loadModels('car', 'car');
Service::loadModels('rally', 'rally');
$rallyService = Controller::getService('rally','rally'); 
$nextBigRally = $rallyService->getNextBigRallyWithAwards();
?>

<table style="background:#333;width:600px;margin:0 auto;">
    <tr>
        <td style="padding:15px;"><img src="http://<?= $_SERVER['SERVER_NAME'];?>/images/layout/logo-fastrally.png" alt="FastRally Logo" title="FastRally Logo" /></td>
        <td>
            
        </td>
    </tr>
    <tr>
        <td style="padding:10px;padding-top:30px;border-top:1px solid #f3f3f3; color:#f3f3f3;width:450px;border-right:1px solid #f3f3f3; line-height:28px;">
            <?= $text; ?>
        </td>
        <td style="border-top:1px solid #f3f3f3; color:#f3f3f3;
    vertical-align: top;
    padding: 10px;
    padding-top: 30px;">
            Follow us for latest promotions and contests.
            <br />
            <div style="margin:0 auto;display:block;text-align:center;margin-top:10px;">
                <a href="<?php $facebookUrl; ?>" class="fb social_icon_link">
                    <img src="http://<?= $_SERVER['SERVER_NAME'];?>/images/layout/fb.png" alt="FastRally Facebook" title="FastRally Facebook" />
                </a>
                <a href="<?php $twitterUrl; ?>" class="twitter social_icon_link" alt="FastRally Twitter" title="FastRally Twitter">
                    <img src="http://<?= $_SERVER['SERVER_NAME'];?>/images/layout/tw.png" />
                </a>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="2" style="padding:15px 10px;border-top:1px solid #f3f3f3;margin-bottom:10px;color:#f3f3f3;">
            <?php if($nextBigRally){ ?>
            Did you know that in Big Rallies you can win unique cars? <a style="color:#f3f3f3;" href="/rally/show-rally/<?= $nextBigRally['slug']; ?>/">Sign up for next big rally</a> on <?= TK_Text::timeFOrmat($nextBigRally['date'],'d/m/Y'); ?> and 
            give yourself a chance to win unique and only <?= $nextBigRally['BigAwards'][0]['Car']['name']; ?>. 
            <?php } ?>
        </td>
    </tr>
</table>