<?php
Service::loadModels('car', 'car');
Service::loadModels('rally', 'rally');
$rallyService = Controller::getService('rally', 'rally');
$nextBigRally = $rallyService->getNextBigRallyWithAwards();
?>
<table style="font-family: tahoma; border: 3px solid #000000; margin-top: 0px; width: 600px;" cellspacing="0" cellpadding="0" align="center">
    <tbody>
        <tr>
            <td width="600">
                <table style="font-family: tahoma;background:#333;width:600px;margin:0 auto;">

                    <tr>
                        <td valign="top" colspan='2' width="600">
                            <a href="http://fastrally.eu/" target="_blank" style='position:absolute;background:#333;padding:5px;'>
                                <!--<img src="http://<?= $_SERVER['SERVER_NAME']; ?>/images/layout/logo-fastrally.png" alt="FastRally Logo" title="FastRally Logo" />-->
                                <img src="http://fastrally.eu/images/layout/logo-fastrally.png" alt="" align="absbottom" border="0" />
                            </a>
                            <img src="/images/layout/car_email2.jpg" alt="" width=""  align="absbottom" />
                            <!--<h1 style="color: #006600; font-size: 20px; padding: 20px 10px 0px 20px;">Witaj w ManagerZone!</h1>-->
                        </td>
                        <!--<td valign="top" width="178"><img style="float: right;" src="/images/layout/champagne_email.jpg" alt="" width="178" height="300" /></td>-->
                    </tr>
<!--                    <tr>
                        <td style="padding:15px;"><img src="http://<?= $_SERVER['SERVER_NAME']; ?>/images/layout/logo-fastrally.png" alt="FastRally Logo" title="FastRally Logo" /></td>
                        <td>

                        </td>
                    </tr>-->
                    <tr>
                        <td style="padding:10px;padding-top:30px; color:#f3f3f3;font-size:14px;
                            /*width:450px;*/line-height:28px;">
                            <?= $text; ?>
                        </td>
                    </tr>
                    <tr>
                        <td style="border-top:1px solid #f3f3f3; color:#f3f3f3;
                           
                            padding: 5px;
                            font-size:12px;" valign='middle'>
                            Follow us for latest promotions and contests.
                            <span>
                                <a href="<?php $facebookUrl; ?>" class="fb social_icon_link">
                                    <img src="http://<?= $_SERVER['SERVER_NAME']; ?>/images/layout/fb_mail.png" alt="FastRally Facebook" title="FastRally Facebook" />
                                </a>
                                <a href="<?php $twitterUrl; ?>" class="twitter social_icon_link" alt="FastRally Twitter" title="FastRally Twitter">
                                    <img src="http://<?= $_SERVER['SERVER_NAME']; ?>/images/layout/tw_mail.png" />
                                </a>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <?php if ($nextBigRally) { ?>
                        <td colspan="2" style="padding:15px 10px;border-top:1px solid #f3f3f3;margin-bottom:10px;color:#f3f3f3;">
                            
                                Did you know that in Big Rallies you can win unique cars? <a style="color:#f3f3f3;" href="/rally/show-rally/<?= $nextBigRally['slug']; ?>/">Sign up for next big rally</a> on <?= TK_Text::timeFOrmat($nextBigRally['date'], 'd/m/Y'); ?> and 
                                give yourself a chance to win unique and only <?= $nextBigRally['BigAwards'][0]['Car']['name']; ?>. 
                        
                        </td>
                                    <?php } else{ ?>
                        <td colspan='2'>
                        </td>
                                    <?php } ?>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>