<?php

/**
 * Rally_Model_Doctrine_Accident
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Rally_Model_Doctrine_Accident extends Rally_Model_Doctrine_BaseAccident
{
    protected static $riskAccidentFactor = array(
	'very-small' => 0.5,
	'small' => 0.8,
	'normal' => 1,
	'big' => 3,
	'very-big' => 8
    );
    
    public static function getRisks(){
	return self::$risks;
    }
    
    
}