<?php

/**
 * Rally_Model_Doctrine_BaseStageResult
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $stage_id
 * @property string $crew_id
 * @property time $base_time
 * @property decimal $random_factor
 * @property integer $accident_id
 * @property decimal $accident_random_factor
 * @property boolean $out_of_race
 * @property Rally_Model_Doctrine_Stage $Stage
 * @property Rally_Model_Doctrine_Crew $Crew
 * @property Rally_Model_Doctrine_Accident $Accident
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Rally_Model_Doctrine_BaseStageResult extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('rally_stage_result');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('stage_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('crew_id', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('base_time', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('random_factor', 'decimal', 4, array(
             'type' => 'decimal',
             'length' => '4',
             ));
        $this->hasColumn('accident_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('accident_random_factor', 'decimal', 4, array(
             'type' => 'decimal',
             'length' => '4',
             ));
        $this->hasColumn('out_of_race', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Rally_Model_Doctrine_Stage as Stage', array(
             'local' => 'stage_id',
             'foreign' => 'id'));

        $this->hasOne('Rally_Model_Doctrine_Crew as Crew', array(
             'local' => 'crew_id',
             'foreign' => 'id'));

        $this->hasOne('Rally_Model_Doctrine_Accident as Accident', array(
             'local' => 'accident_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}