<?php

/**
 * Rally_Model_Doctrine_BaseFriendly
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $rally_id
 * @property boolean $invite_only
 * @property datetime $start_friendly_date
 * @property text $description
 * @property Rally_Model_Doctrine_Rally $Rally
 * @property Rally_Model_Doctrine_FriendlyParticipants $Paricipants
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Rally_Model_Doctrine_BaseFriendly extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('rally_friendly');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'autoincrement' => true,
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('rally_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('invite_only', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('start_friendly_date', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));

        $this->option('type', 'MyISAM');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Rally_Model_Doctrine_Rally as Rally', array(
             'local' => 'rally_id',
             'foreign' => 'id'));

        $this->hasOne('Rally_Model_Doctrine_FriendlyParticipants as Paricipants', array(
             'local' => 'id',
             'foreign' => 'friendly_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}