<?php

/**
 * Rally_Model_Doctrine_BigAwards
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Rally_Model_Doctrine_BigAwards extends Rally_Model_Doctrine_BaseBigAwards
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Car_Model_Doctrine_CarModels as Car', array(
             'local' => 'car_model_id',
             'foreign' => 'id'));
    }
}