<?php

/**
 * Rally_Model_Doctrine_CrewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Rally_Model_Doctrine_CrewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Rally_Model_Doctrine_CrewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rally_Model_Doctrine_Crew');
    }
}