<?php

/**
 * Rally_Model_Doctrine_Crew
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Rally_Model_Doctrine_Crew extends Rally_Model_Doctrine_BaseCrew
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Team_Model_Doctrine_Team as Team', array(
             'local' => 'team_id',
             'foreign' => 'id'));
        
        $this->hasOne('Rally_Model_Doctrine_RallyResult as Result', array(
             'local' => 'id',
             'foreign' => 'crew_id'));
	
	$this->hasOne('People_Model_Doctrine_People as Pilot', array(
             'local' => 'pilot_id',
             'foreign' => 'id'));
	
	$this->hasOne('People_Model_Doctrine_People as Driver', array(
             'local' => 'driver_id',
             'foreign' => 'id'));
	
	$this->hasOne('Car_Model_Doctrine_Car as Car', array(
             'local' => 'car_id',
             'foreign' => 'id'));
    }
}