<?php

/**
 * rally_Model_Doctrine_Rally
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Rally_Model_Doctrine_Rally extends Rally_Model_Doctrine_BaseRally
{
    
    
    protected static $risks = array(
	'very-small' => 'Very small risk',
	'small' => 'Small risk',
	'normal' => 'Normal risk',
	'big' => 'Big risk',
	'very-big' => 'Very big risk'
    );
    
    protected static $riskTimeFactor = array(
	'very-small' => 1.10,
	'small' => 1.042,
	'normal' => 1,
	'big' => 0.956,
	'very-big' => 0.90
    );
    
    protected static $riskAccidentFactor = array(
	'very-small' => 0.5,
	'small' => 0.8,
	'normal' => 2,
	'big' => 6,
	'very-big' => 15
    );
    
    public static function getRisks(){
	return self::$risks;
    }
    
    public static function getRiskValues(){
	return array_keys(self::$risks);
    }
    
    // we must hide the risk numbers
    // so the people won't find out how we calculate the results of the race
    // we use text value as both keys and values
    public static function getFormRisks(){
	return self::$risks;
    }
    
    public static function getAccidentRisks(){
	return self::$riskAccidentFactor;
    }
    
    public static function getTimeRisks(){
	return self::$riskTimeFactor;
    }
    
    public static function getTimeRisk($risk){
	return self::$riskTimeFactor[$risk];
    }
    
    public static function getAccidentRisk($risk){
	return self::$riskAccidentFactor[$risk];
    }
    
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Rally_Model_Doctrine_BigAwards as BigAwards', array(
             'local' => 'id',
             'foreign' => 'rally_id'));
    }
}