<?php

/**
 * rally_Model_Doctrine_RallyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class rally_Model_Doctrine_RallyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object rally_Model_Doctrine_RallyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('rally_Model_Doctrine_Rally');
    }
}