<?php

/**
 * Rally_Model_Doctrine_Stage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Tomasz <kardi31@o2.pl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Rally_Model_Doctrine_Stage extends Rally_Model_Doctrine_BaseStage
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Rally_Model_Doctrine_StageResult as Results', array(
             'local' => 'id',
             'foreign' => 'stage_id'));
    }
}