<?php 
if(isset($_GET['msg'])){ 
    if($_GET['msg']=="user already ingame"){
        $this->showError($this->translate('This email is already registered in Fast Rally'));
    }
    elseif($_GET['msg']=="not email"){
        $this->showError($this->translate('This is not a valid email address.'));
    }
    elseif($_GET['msg']=="user already invited"){
        $this->showError($this->translate('Your have already invited this email address.'));
    }
    elseif($_GET['msg']=="user invited"){
        $this->showSuccess($this->translate('Your invitation has been send.'));
    }
}
?>
<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('Invite your friend to Fast Rally'); ?></h4>
    <div class='staticWrapper'>
        <?= $this->translate('If your friend is active for over a month, we will reward you with 10'); ?> <img class="coin" src="/images/layout/coin.png"><br />
        <?= $this->translate('If your friend during this month gets premium to access our great additional features, you will receive additional 100'); ?> <img class="coin" src="/images/layout/coin.png"> <br />
        <?= $this->translate("Don't hesitate! Tell your friends about Fast Rally!"); ?>
        <form class='inviteToGame' action="/user/invite-to-game" method="POST">
            <?php echo $form->getElement('email')->renderElement(); ?>
            <?php echo $form->getElement('submit')->renderElement(); ?>
        </form>
        
        <br />
        <?php if(count($userInvites)>0||count($userAcceptedInvites)>0){ ?>
            <span class='invitedToGame'>
            <strong><?= $this->translate('Send invitations'); ?></strong>
            <ol>
            <?php foreach($userInvites as $invitation): ?>
                <li><?= $invitation['email']; ?></li>

            <?php endforeach; ?>
            </ol>

            <strong><?= $this->translate('Accepted invitations');?></strong>
            <?php if(count($userAcceptedInvites)>0){ ?>
                <table>
                <thead>
                    <tr>
                        <th><?= $this->translate('Email');?></th>
                        <th><?= $this->translate('Registration date');?></th>
                        <th><?= $this->translate('Referer paid');?></th>
                    </tr>
                </thead>
                <?php foreach($userAcceptedInvites as $acceptedInvite): ?>
                    <tr>
                        <td>
                            <?= $acceptedInvite['email']; ?>
                        </td>
                        <td>
                            <?= TK_Text::timeFormat($acceptedInvite['created_at'],'d/m/y'); ?>
                        </td>
                        <td>
                            <?php
                                if(!$acceptedInvite['referer_paid']){
                                    echo '<span class="label label-danger">'.$this->translate('No').'</span>';
                                }
                                else{
                                    echo '<span class="label label-success">'.$this->translate('Yes').'</span>';
                                }
                            ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
            <?php } ?>
        </span>
        <?php } ?>
    </div>
</div>

