<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('My account');?></h4>
    <div class="staticWrapper">
        <div class="myAccountBtns">
            <a href="/user/edit-details" class="btn"><?php echo $this->translate('Edit details');?></a>
            <a href="/user/change-password" class="btn"><?php echo $this->translate('Change password');?></a>
            <a href="/user/change-email" class="btn"><?php echo $this->translate('Change email');?></a>
            <a href="#" class="btn"><?php echo $this->translate('Delete account');?></a>
        </div>
    </div>
</div>