<div class="mainUserBox">
    <h4 class="boxHeader"><?= $this->translate('My account');?></h4>
    <div class="staticWrapper">
        <div class="myAccountBtns">
            <a href="/user/edit-details" class="btn">Edit details</a>
            <a href="/user/change-password" class="btn">Change password</a>
            <a href="/user/change-email" class="btn">Change email</a>
            <a href="#" class="btn">Delete account</a>
        </div>
    </div>
</div>