<div class="col-md-12">
    <div class="col-md-10 mainPageBox leftMainPageBox">
        <h2>THANK YOU</h2>
        You have successfully created your account in FastRally.<br />
        To activate your account and enjoy the world of FastRally please click a link which we send you to your email. <br /><br />
        If you did not receive an email from us, please send us an email at activate@fast-rally.com with your login.
    </div>
    
</div>
<div class="clearfix"></div>
