<div class="col-md-12">
    <div class="col-md-10 mainPageBox leftMainPageBox">
        <h2><?= $this->translate('THANK YOU'); ?></h2>
        <?= $this->translate('You have successfully created your account in FastRally.'); ?><br />
        <?= $this->translate('To activate your account and enjoy the world of FastRally please click a link which we send you to your email.');?> <br /><br />
        <?= $this->translate('If you did not receive an email from us, please send us an email at activate@fastrally.eu with your login.'); ?>
    </div>
    
</div>
<div class="clearfix"></div>
