<div class="col-md-12">
    <div class="col-md-6 mainPageBox leftMainPageBox">
        <h2>ABOUT</h2>
        The game Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed cursus sagittis purus sit amet ultrices. In auctor, justo vitae rutrum convallis, arcu libero scelerisque ex, at lobortis metus ligula in tellus. In quis elit eros. Praesent semper dignissim ullamcorper. Phasellus ornare luctus porttitor. Fusce pharetra porta neque, quis tincidunt tellus vehicula ac. Quisque suscipit venenatis leo in vulputate:
        <ul>
            <li>felis tellus mollis orci,</li>
            <li>sed rhoncus sapien,</li>
            <li>nunc eget odio.</li>
        </ul>
        Lorem ipsum dolor sit amet,
        <img src="/images/layout/fotolia_78706818.jpg" />
        <div class="clearfix"></div>
        id posuere enim iaculis at. Vestibulum ante ipsum primis in faucibus leifend sapien, in viverra leo. 
    </div>
    <div class="col-md-1"></div>
    <div class="col-md-4 mainPageBox rightMainPageBox">
        <h2>REGISTRATION</h2>
        <form method="POST" action="/user/register">
            <label for="login">Login<sup>*</sup></label>
            <input type="text" name="login" class="textInput" />
            <label for="login">Password<sup>*</sup></label>
            <input type="password" name="password" class="textInput"  />
            <label for="login">Repeat password<sup>*</sup></label>
            <input type="password" name="password2" class="textInput" />
            <label for="login">E-mail address<sup>*</sup></label>
            <?= $form->getElement('email')->renderElement(); ?>
            <span class="acceptRules">
                <input type="checkbox" name="rules" id='acceptRules'/> 
                <label for='acceptRules'>I accept rules</label>
            </span>

            <button type="submit" name="submit" class='logIn btn'>REGISTER</button>
        </form>
    </div>
</div>
<div class="clearfix"></div>