<style>
    .postContent{
        border:1px solid black;
    }
    
    .breadcrumbs{
        margin-left:0px;
        padding-left:0px;
    }
    
    .breadcrumbs li{
        display:inline-block; 
    }
    
    .breadcrumbs li:not(:last-of-type):after{
        content: ">";
        display:inline-block;
        margin-left:5px;
    }
</style>
<h3>Forum</h3>
<ul class="breadcrumbs">
    <li><a href="/forum/show-forum">Forum</a></li>
    <li><a href="/forum/show-category/slug/<?php echo $thread['Category']['slug']; ?>"><?php echo $thread['Category']['name']; ?></a></li>
    <li><?php echo $thread['title']; ?></li>
</ul>
Created by : <?php echo TK_Text::timeFormat($thread['created_at'],'d/m/Y H:i'); ?> by
        '<?php echo $thread['User']['username']; ?>'
        <br />
    
<h5><?php echo $thread['title']; ?></h5>
<div class="postContent"><?php echo $thread['content']; ?></div>
<hr />
<?php

foreach($posts as $post):
    ?>
        <?php if(isset($post)&&!empty($post)):
        ?>
<div class="postContent">
    <?php echo $post['content']; ?>
</div>
        <?php 
        echo TK_Text::timeFormat($post['created_at'],'d/m/Y H:i');
        ?>
        by
        '<?php echo $post['User']['username']; ?>'
        <br />

        <?php

    endif;
    
?>
        
<hr />
<?php

endforeach;
?>
<h5>Respond to this thread</h5>
<form method="POST">
    <?php echo $form->getElement('content')->renderElement(); ?>
    <?php // echo $form->getElement('active')->renderElement(); ?>
    <?php echo $form->getElement('submit')->renderElement(); ?>
</form>