<?php if(isset($_GET['msg'])){
        if($_GET['msg']=="too fast"){
            $this->showError('You can post once every 30 seconds');
        }
    }
    ?>
<div class="mainUserBox showForumWrapper ">
    
    <div class="boxHeader">
        <span class="threadInfo">
            <i class="fa fa-clock-o"></i> <?php echo TK_Text::timeFormat($thread['created_at'],'d/m/y H:i'); ?> <br />
            <i class="fa fa-user"></i> '<?php echo $thread['User']['username']; ?>'
        </span>
        <h4><?php echo $thread['title']; ?></h4>
        <small><a href="/forum/show-forum">Forum</a> / <a href="/forum/show-category/slug/<?php echo $thread['Category']['slug']; ?>"><?php echo $thread['Category']['name']; ?></a></small>
        
    </div> 
    <div>
        <?php if($user['role']=="admin"||$user['role']=="moderator"||$user['id']==$thread['user_id']): ?>
        <div style='float:right;margin-right:50px;'>
            <a href="/forum/edit-thread/id/<?= $thread['id']; ?>">Edit</a>
            <a href="/forum/delete-thread/id/<?= $thread['id']; ?>">Remove</a>
        </div>
        <?php endif; ?>
    </div>
    <div class="threadContent">
        <div class="postContent threadMainContent"><?php echo $thread['content']; ?></div>
        <?php 
            if(strlen($thread['moderator_notes'])){
                echo "<span class='moderatorNotes'>".$thread['moderator_notes']."</span>";
            }

            if($thread['created_at']!=$thread['updated_at']): 
                if(strlen($thread['moderator_name'])){
                    echo "<span class='moderatorEdited'>Last edited by ".$thread['moderator_name']." on ".TK_Text::timeFormat($thread['moderator_date'], 'd/m/Y H:i')."</span>";
                }
            endif; ?>
            <hr />
            <?php 
            $postCount = count($posts);
                foreach($posts as $key => $post): ?>
                <?php if(isset($post)&&!empty($post)): ?>
                    <span class="threadInfo">
                        <i class="fa fa-clock-o"></i> <?php echo TK_Text::timeFormat($post['created_at'],'d/m/Y H:i'); ?> <br />
                        <i class="fa fa-user"></i> '<?php echo $post['User']['username']; ?>'
                    </span>
                    <div class="postContent">
                        <?php echo $post['content']; ?>
                    </div>
                    <?php if($user['role']=="admin"||$user['role']=="moderator"): //||$user['id']==$post['user_id'] ?>
                        <div style='float:right;margin-right:50px;'>
                            <a href="/forum/edit-post/id/<?= $post['id']; ?>">Edit</a>
                            <a href="/forum/delete-post/id/<?= $post['id']; ?>">Remove</a>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
                <?php 
                    if(strlen($post['moderator_notes'])){
                        echo "<span class='moderatorNotes'>".$post['moderator_notes']."</span><br />";
                    }

                    if($post['created_at']!=$post['updated_at']): 
                        if(strlen($post['moderator_name'])){
                            echo "<span class='moderatorEdited'>Last edited by ".$post['moderator_name']." on ".TK_Text::timeFormat($post['moderator_date'], 'd/m/Y H:i')."</span>";
                        }
                    endif; 
                ?>
                <div class="clearfix"></div>
                <?php if($key!=$postCount-1): ?>
                    <hr />
                <?php endif; ?>
            <?php endforeach; ?>
    </div>
    <div class="addThreadWrapper replyThreadWrapper">
        <h5><i class="fa fa-pencil"></i> Respond to this thread</h5>
        <form method="POST">
            <?php echo $form->getElement('content')->renderElement(); ?>
            <?php // echo $form->getElement('active')->renderElement(); ?>
            <?php echo $form->getElement('submit')->renderElement(); ?>
        </form>
    </div>
</div>