<?php

foreach($categories as $category):
    ?>
    <h3><a href="/forum/show-category/slug/<?php echo $category['slug']; ?>"><?php echo $category['name']; ?></a></h3>
    <?php if(isset($category['last_post'])&&!empty($category['last_post'])):
        ?>
        Last post:
        <?php 
        echo date(TK_Text::timeFormat($category['last_post']['created_at'],'d/m/Y H:i'));
        ?>
        by
        '<?php echo $category['last_post']['User']['username']; ?>'
        <br />

        <?php

    endif;
    
?>
        Number of posts: <?php echo $category['post_count']; ?><br />
        Number of threads: <?php echo $category['thread_count']; ?><br />
        <?php if(is_array($favouriteCategories)&&in_array($category['id'], $favouriteCategories)){ ?>
            Ta kategoria jest już jako twoja ulubiona. <a href="/forum/remove-favourite-forum/id/<?php echo $category['id']; ?>/">Remove category from favourites</a>
        <?php }
        elseif(is_string($favouriteCategories)&&$favouriteCategories==$category['id']){ ?>
            Ta kategoria jest już jako twoja ulubiona. <a href="/forum/remove-favourite-forum/id/<?php echo $category['id']; ?>/">Remove category from favourites</a>
        <?php } else { ?>
            <a href="/forum/add-favourite-forum/id/<?php echo $category['id']; ?>/">Add category to favourite</a>
        <?php } ?>
<hr />
<?php

endforeach;