<div class="mainUserBox showRallyWrapper">
    <h4 class="boxHeader"><?= $this->translate('Forum'); ?></h4> 
   
    <?php foreach($categories as $category): ?>
        <div class="forumGroup">
            <h6><a href="/forum/show-category/slug/<?php echo $category['slug']; ?>"><?php echo $category['name']; ?></a></h6>
            <div class="forumGroupInside">
                <div class="forumGroupRight">
                    <?php if(isset($category['last_post'])&&!empty($category['last_post'])): ?>
                        <?= $this->translate('Last post'); ?>: <br />
                        <i class="fa fa-clock-o"></i>
                        <?php 
                        echo date(TK_Text::timeFormat($category['last_post']['created_at'],'d/m/Y H:i'));
                        ?>
                        <br />
                        <i class="fa fa-user"></i>
                        '<?php echo $category['last_post']['User']['username']; ?>'
                        <br />
                    <?php endif; ?>
                </div>
                <?= $this->translate('Number of posts'); ?>: <strong><?php echo $category['post_count']; ?></strong><br />
                <?= $this->translate('Number of threads'); ?>: <?php echo $category['thread_count']; ?><br />
                <?php if($user['gold_member']){ ?>
                    <?php if(is_array($favouriteCategories)&&in_array($category['id'], $favouriteCategories)){ ?>
                        <a href="/forum/remove-favourite-forum/id/<?php echo $category['id']; ?>/"><i class="fa fa-star selected"></i></a>
                    <?php }
                    elseif(is_string($favouriteCategories)&&$favouriteCategories==$category['id']){ ?>
                        <a href="/forum/remove-favourite-forum/id/<?php echo $category['id']; ?>/"><i class="fa fa-star selected"></i></a>
                    <?php } else { ?>
                        <a href="/forum/add-favourite-forum/id/<?php echo $category['id']; ?>/">
                            <i class="fa fa-star"></i>
                        </a>
                    <?php } ?>
                <?php } ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>