<?php if(isset($_GET['msg'])){
        if($_GET['msg']=="too fast"){
            $this->showError($this->translate('You can post once every 30 seconds'));
        }
    }
    ?>
<div class="mainUserBox showForumWrapper">
    <div class="boxHeader">
        <h4><?php echo $category['name']; ?></h4>
        <small><a href="/forum/show-forum"><?= $this->translate('Forum'); ?></a></small>
    </div> 
    <div class="forumGroup">
        <?php foreach($threads as $thread): ?>

            <div class="forumListElem">
                <strong><a href="/forum/show-thread/<?php echo $thread['id']; ?>"><?php echo $thread['title']; ?></a></strong>
                <div>
            <?= $this->translate('Created'); ?>: 
                    <i class="fa fa-clock-o"></i> <?php echo TK_Text::timeFormat($thread['created_at'],'d/m/y H:i'); ?>
                    <i class="fa fa-user"></i>
                '<?php echo $thread['User']['username']; ?>' <br />
                <?php if(isset($thread['Posts'][0])&&!empty($thread['Posts'][0])&&$thread['Posts'][0]['active']): ?>
                    <?= $this->translate('Last post'); ?>:
                    <i class="fa fa-clock-o"></i>
                    <?php 
                    echo TK_Text::timeFormat($thread['Posts'][0]['created_at'],'d/m/y H:i');
                    ?>
                    <i class="fa fa-user"></i>
                    '<?php echo $thread['Posts'][0]['User']['username']; ?>'
                    <br />
                <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>
        <div class="addThreadWrapper">
            <h5><i class="fa fa-pencil"></i> <?= $this->translate('Add new thread'); ?></h5>
            <form method="POST">
                <?php echo $form->getElement('title')->renderElement(); ?>
                <?php echo $form->getElement('content')->renderElement(); ?>
                <?php // echo $form->getElement('active')->renderElement(); ?>
                <?php echo $form->getElement('submit')->renderElement(); ?>
            </form>
        </div>
    </div>
</div>