<div class="mainUserBox boxForum">
    
    <h4 class="boxHeader">Forum</h4>
    <?php if(!$authenticatedUser['gold_member']){ ?>
        <div class="goldOverlay">
            <a href="/gold-membership">
                <img src="/images/layout/gc_big.png" />
            </a>
        </div>
    <?php }
    else{ ?>
        <?php if(isset($friends)): ?>
            <ul>
                <?php foreach($favouriteCategories as $favourite): ?>
                    <li>
                        <a href="/forum/show-category/<?= $favourite['Category']['slug']; ?>" class="bold"><?php echo $this->translate($favourite['Category']['name']); ?></a>
                        <?php $thread = $lastThreads[$favourite['category_id']];
                        if(!$thread) continue;
                        if(isset($thread['Thread'])){
                            $threadItself = $thread['Thread'];
                        }
                        else{
                            $threadItself = $thread;
                        }
                        
                        ?>
                        <br />
                        <span class="category"><i class="fa fa-envelope-o" title="Thread with last post"></i>  <a href="/forum/show-thread/<?php echo $threadItself['id']; ?>"><?php echo $threadItself['title']; ?></a></span>

                        <?php if(isset($thread['Posts'][0])&&!empty($thread['Posts'][0])): ?>
                        <br />
                            Last post: 
                            <?php echo TK_Text::timeFormat($thread['Posts'][0]['created_at'],'d/m H:i'); ?>
                            <i class="fa fa-user-md"></i>
                            <?php echo TK_Text::truncate($thread['Posts'][0]['User']['username'],16); ?>
                            <br />
                        <?php else : ?>
                            <span>
                            <i class="fa fa-clock-o" title="Date of last post"></i> <?php echo TK_Text::timeFormat($thread['created_at'],'d/m H:i'); ?> <br />
                            <i class="fa fa-user-md" title="User who created last post"></i> <?php echo TK_Text::truncate($thread['User']['username'],16); ?> </span>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    <?php } ?>
</div>
