<div class="mainUserBox showRallyWrapper">
    <h4 class="boxHeader">Forum</h4> 
   
    <style>
        .forumGroup{
            border-radius: 6px;
            border: 6px solid #fff;
            background: #cad3e4;
            margin-bottom: 20px;
            color: #7774a9;
            padding: 0px 0px 15px;
            position: relative;
        }
        
        .forumGroup h6 a{
            display: block;
            background: #f4e973;
            padding-top: 10px;
            padding-left: 20px;
            font-size: 18px;
            padding-bottom: 10px;
            color: #7774a9;
        }
        
        .forumGroup h6{
            margin:0px;
        }
        
        .fa-star.selected{
            color: yellow;
        }
        
        .forumGroupInside{
            padding: 10px;
        }
        
        .forumGroup .forumGroupRight{
            float:right;
        }
        
        .forumGroup .forumGroupRight i{
            margin-right:5px;
        }
        
    </style>
<?php foreach($categories as $category): ?>
    <div class="forumGroup">
        <h6><a href="/forum/show-category/slug/<?php echo $category['slug']; ?>"><?php echo $category['name']; ?></a></h6>
        <div class="forumGroupInside">
            <div class="forumGroupRight">
                <?php if(isset($category['last_post'])&&!empty($category['last_post'])): ?>
                    Last post: <br />
                    <i class="fa fa-clock-o"></i>
                    <?php 
                    echo date(TK_Text::timeFormat($category['last_post']['created_at'],'d/m/Y H:i'));
                    ?>
                    <br />
                    <i class="fa fa-user"></i>
                    '<?php echo $category['last_post']['User']['username']; ?>'
                    <br />
                <?php endif; ?>
            </div>
            Number of posts: <strong><?php echo $category['post_count']; ?></strong><br />
            Number of threads: <?php echo $category['thread_count']; ?><br />
            <?php if(is_array($favouriteCategories)&&in_array($category['id'], $favouriteCategories)){ ?>
                <a href="/forum/remove-favourite-forum/id/<?php echo $category['id']; ?>/"><i class="fa fa-star selected"></i></a>
            <?php }
            elseif(is_string($favouriteCategories)&&$favouriteCategories==$category['id']){ ?>
                <a href="/forum/remove-favourite-forum/id/<?php echo $category['id']; ?>/"><i class="fa fa-star selected"></i></a>
            <?php } else { ?>
                <a href="/forum/add-favourite-forum/id/<?php echo $category['id']; ?>/">
                    <i class="fa fa-star"></i>
                </a>
            <?php } ?>
        </div>
    </div>
<?php endforeach; ?>
</div>